package pe.com.soul.core.bean;
// default package
// Generated 23/09/2015 09:32:07 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Modulo generated by hbm2java
 */
@Entity
@Table(name = "modulo", schema = "seguridad")
public class Modulo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int codModulo;
	private String nombre;
	private int orden;
	private Set<Rol> rols = new HashSet<Rol>(0);

	public Modulo() {
	}

	public Modulo(int codModulo, String nombre, int orden) {
		this.codModulo = codModulo;
		this.nombre = nombre;
		this.orden = orden;
	}

	public Modulo(int codModulo, String nombre, int orden, Set<Rol> rols) {
		this.codModulo = codModulo;
		this.nombre = nombre;
		this.orden = orden;
		this.rols = rols;
	}

	@Id
	@Column(name = "cod_modulo", unique = true, nullable = false)
	public int getCodModulo() {
		return this.codModulo;
	}

	public void setCodModulo(int codModulo) {
		this.codModulo = codModulo;
	}

	@Column(name = "nombre", nullable = false, length = 60)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "orden", nullable = false)
	public int getOrden() {
		return this.orden;
	}

	public void setOrden(int orden) {
		this.orden = orden;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "modulos")
	public Set<Rol> getRols() {
		return this.rols;
	}

	public void setRols(Set<Rol> rols) {
		this.rols = rols;
	}

}
