package pe.com.soul.core.bean;
// default package
// Generated 23/09/2015 09:32:07 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ProInstancia generated by hbm2java
 */
@Entity
@Table(name = "pro_instancia", schema = "proceso")
public class Proceso implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long codProceso;
	private ProcesoPlantilla proPlantilla;
	private char estado;
	private Set<Tarea> tarInstancias = new HashSet<Tarea>(0);

	public Proceso() {
	}

	public Proceso(long codProceso, ProcesoPlantilla proPlantilla, char estado) {
		this.codProceso = codProceso;
		this.proPlantilla = proPlantilla;
		this.estado = estado;
	}

	public Proceso(long codProceso, ProcesoPlantilla proPlantilla,
			char estado, Set<Tarea> tarInstancias) {
		this.codProceso = codProceso;
		this.proPlantilla = proPlantilla;
		this.estado = estado;
		this.tarInstancias = tarInstancias;
	}

	@Id
	@Column(name = "cod_proceso", unique = true, nullable = false)
	public long getCodProceso() {
		return this.codProceso;
	}

	public void setCodProceso(long codProceso) {
		this.codProceso = codProceso;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cod_pro_plantilla", nullable = false)
	public ProcesoPlantilla getProPlantilla() {
		return this.proPlantilla;
	}

	public void setProPlantilla(ProcesoPlantilla proPlantilla) {
		this.proPlantilla = proPlantilla;
	}

	@Column(name = "estado", nullable = false, length = 1)
	public char getEstado() {
		return this.estado;
	}

	public void setEstado(char estado) {
		this.estado = estado;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "proInstancia")
	public Set<Tarea> getTarInstancias() {
		return this.tarInstancias;
	}

	public void setTarInstancias(Set<Tarea> tarInstancias) {
		this.tarInstancias = tarInstancias;
	}

}
