package pe.com.soul.core.bean;
// default package
// Generated 23/09/2015 09:32:07 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Rol generated by hbm2java
 */
@Entity
@Table(name = "rol", schema = "seguridad")
public class Rol implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long codRol;
	private String nombre;
	private Set<Modulo> modulos = new HashSet<Modulo>(0);
	private Set<ProcesoPlantilla> proPlantillas = new HashSet<ProcesoPlantilla>(0);
	private Set<TareaPlantilla> tarPlantillas = new HashSet<TareaPlantilla>(0);

	public Rol() {
	}

	public Rol(long codRol, String nombre) {
		this.codRol = codRol;
		this.nombre = nombre;
	}

	public Rol(long codRol, String nombre, Set<Modulo> modulos,
			Set<ProcesoPlantilla> proPlantillas, Set<TareaPlantilla> tarPlantillas) {
		this.codRol = codRol;
		this.nombre = nombre;
		this.modulos = modulos;
		this.proPlantillas = proPlantillas;
		this.tarPlantillas = tarPlantillas;
	}

	@Id
	@Column(name = "cod_rol", unique = true, nullable = false)
	public long getCodRol() {
		return this.codRol;
	}

	public void setCodRol(long codRol) {
		this.codRol = codRol;
	}

	@Column(name = "nombre", nullable = false, length = 120)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "mod_rol", schema = "public", joinColumns = { @JoinColumn(name = "cod_rol", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "cod_modulo", nullable = false, updatable = false) })
	public Set<Modulo> getModulos() {
		return this.modulos;
	}

	public void setModulos(Set<Modulo> modulos) {
		this.modulos = modulos;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "rols")
	public Set<ProcesoPlantilla> getProPlantillas() {
		return this.proPlantillas;
	}

	public void setProPlantillas(Set<ProcesoPlantilla> proPlantillas) {
		this.proPlantillas = proPlantillas;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "rols")
	public Set<TareaPlantilla> getTarPlantillas() {
		return this.tarPlantillas;
	}

	public void setTarPlantillas(Set<TareaPlantilla> tarPlantillas) {
		this.tarPlantillas = tarPlantillas;
	}

}
