package pe.com.soul.core.bean;
// default package
// Generated 23/09/2015 09:32:07 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TarInstancia generated by hbm2java
 */
@Entity
@Table(name = "tar_instancia", schema = "proceso")
public class Tarea implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private long codTarea;
	private Proceso proInstancia;
	private TareaPlantilla tarPlantilla;
	private char estado;

	public Tarea() {
	}

	public Tarea(long codTarea, Proceso proInstancia,
			TareaPlantilla tarPlantilla, char estado) {
		this.codTarea = codTarea;
		this.proInstancia = proInstancia;
		this.tarPlantilla = tarPlantilla;
		this.estado = estado;
	}

	@Id
	@Column(name = "cod_tarea", unique = true, nullable = false)
	public long getCodTarea() {
		return this.codTarea;
	}

	public void setCodTarea(long codTarea) {
		this.codTarea = codTarea;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cod_proceso", nullable = false)
	public Proceso getProInstancia() {
		return this.proInstancia;
	}

	public void setProInstancia(Proceso proInstancia) {
		this.proInstancia = proInstancia;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cod_tar_plantilla", nullable = false)
	public TareaPlantilla getTarPlantilla() {
		return this.tarPlantilla;
	}

	public void setTarPlantilla(TareaPlantilla tarPlantilla) {
		this.tarPlantilla = tarPlantilla;
	}

	@Column(name = "estado", nullable = false, length = 1)
	public char getEstado() {
		return this.estado;
	}

	public void setEstado(char estado) {
		this.estado = estado;
	}

}
