package pe.com.soul.core.bean;
// default package
// Generated 23/09/2015 09:32:07 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TarPlantilla generated by hbm2java
 */
@Entity
@Table(name = "tar_plantilla", schema = "proceso")
public class TareaPlantilla implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long codTarPlantilla;
	private ProcesoPlantilla proPlantilla;
	private char estado;
	private Set<Rol> rols = new HashSet<Rol>(0);
	private Set<Tarea> tarInstancias = new HashSet<Tarea>(0);

	public TareaPlantilla() {
	}

	public TareaPlantilla(long codTarPlantilla, ProcesoPlantilla proPlantilla,
			char estado) {
		this.codTarPlantilla = codTarPlantilla;
		this.proPlantilla = proPlantilla;
		this.estado = estado;
	}

	public TareaPlantilla(long codTarPlantilla, ProcesoPlantilla proPlantilla,
			char estado, Set<Rol> rols, Set<Tarea> tarInstancias) {
		this.codTarPlantilla = codTarPlantilla;
		this.proPlantilla = proPlantilla;
		this.estado = estado;
		this.rols = rols;
		this.tarInstancias = tarInstancias;
	}

	@Id
	@Column(name = "cod_tar_plantilla", unique = true, nullable = false)
	public long getCodTarPlantilla() {
		return this.codTarPlantilla;
	}

	public void setCodTarPlantilla(long codTarPlantilla) {
		this.codTarPlantilla = codTarPlantilla;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cod_pro_plantilla", nullable = false)
	public ProcesoPlantilla getProPlantilla() {
		return this.proPlantilla;
	}

	public void setProPlantilla(ProcesoPlantilla proPlantilla) {
		this.proPlantilla = proPlantilla;
	}

	@Column(name = "estado", nullable = false, length = 1)
	public char getEstado() {
		return this.estado;
	}

	public void setEstado(char estado) {
		this.estado = estado;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "tar_pla_rol", schema = "proceso", joinColumns = { @JoinColumn(name = "cod_tar_plantilla", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "cod_rol", nullable = false, updatable = false) })
	public Set<Rol> getRols() {
		return this.rols;
	}

	public void setRols(Set<Rol> rols) {
		this.rols = rols;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tarPlantilla")
	public Set<Tarea> getTarInstancias() {
		return this.tarInstancias;
	}

	public void setTarInstancias(Set<Tarea> tarInstancias) {
		this.tarInstancias = tarInstancias;
	}

}
