package pe.com.soul.core.bean;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name = "usuario", schema = "seguridad")
public class Usuario extends User implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;


	public Usuario() {
	}

	public Usuario(long codUsuario, char estado, String usuario, String clave,
			String nomCompleto, String correo) {
		this.codUsuario = codUsuario;
		this.estado = estado;
		this.usuario = usuario;
		this.clave = clave;
		this.nomCompleto = nomCompleto;
		this.correo = correo;
	}

	@Id
	@Column(name = "cod_usuario", unique = true, nullable = false)
	public long getCodUsuario() {
		return this.codUsuario;
	}

	public void setCodUsuario(long codUsuario) {
		this.codUsuario = codUsuario;
	}

	@Column(name = "estado", nullable = false, length = 1)
	public char getEstado() {
		return this.estado;
	}

	public void setEstado(char estado) {
		this.estado = estado;
	}

	@Column(name = "usuario", nullable = false, length = 40)
	public String getUsuario() {
		return this.usuario;
	}

	public void setUsuario(String usuario) {
		this.usuario = usuario;
	}

	@Column(name = "clave", nullable = false, length = 20)
	public String getClave() {
		return this.clave;
	}

	public void setClave(String clave) {
		this.clave = clave;
	}

	@Column(name = "nom_completo", nullable = false, length = 120)
	public String getNomCompleto() {
		return this.nomCompleto;
	}

	public void setNomCompleto(String nomCompleto) {
		this.nomCompleto = nomCompleto;
	}

	@Column(name = "correo", nullable = false, length = 120)
	public String getCorreo() {
		return this.correo;
	}

	public void setCorreo(String correo) {
		this.correo = correo;
	}

}
