package pe.com.soul.core.bean;
// default package
// Generated 23/09/2015 09:32:07 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name = "usuario", schema = "seguridad")
public class Usuario implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long codUsuario;
	private char estado;
	private String usuario;
	private String clave;
	private String nomCompleto;
	private String correo;
	private Set<Rol> rols = new HashSet<Rol>(0);

	public Usuario() {
	}

	public Usuario(long codUsuario, char estado, String usuario, String clave,
			String nomCompleto, String correo) {
		this.codUsuario = codUsuario;
		this.estado = estado;
		this.usuario = usuario;
		this.clave = clave;
		this.nomCompleto = nomCompleto;
		this.correo = correo;
	}

	public Usuario(long codUsuario, char estado, String usuario, String clave,
			String nomCompleto, String correo, Set<Rol> rols) {
		this.codUsuario = codUsuario;
		this.estado = estado;
		this.usuario = usuario;
		this.clave = clave;
		this.nomCompleto = nomCompleto;
		this.correo = correo;
		this.rols = rols;
	}

	@Id
	@Column(name = "cod_usuario", unique = true, nullable = false)
	public long getCodUsuario() {
		return this.codUsuario;
	}

	public void setCodUsuario(long codUsuario) {
		this.codUsuario = codUsuario;
	}

	@Column(name = "estado", nullable = false, length = 1)
	public char getEstado() {
		return this.estado;
	}

	public void setEstado(char estado) {
		this.estado = estado;
	}

	@Column(name = "usuario", nullable = false, length = 40)
	public String getUsuario() {
		return this.usuario;
	}

	public void setUsuario(String usuario) {
		this.usuario = usuario;
	}

	@Column(name = "clave", nullable = false, length = 20)
	public String getClave() {
		return this.clave;
	}

	public void setClave(String clave) {
		this.clave = clave;
	}

	@Column(name = "nom_completo", nullable = false, length = 120)
	public String getNomCompleto() {
		return this.nomCompleto;
	}

	public void setNomCompleto(String nomCompleto) {
		this.nomCompleto = nomCompleto;
	}

	@Column(name = "correo", nullable = false, length = 120)
	public String getCorreo() {
		return this.correo;
	}

	public void setCorreo(String correo) {
		this.correo = correo;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "usu_rol", schema = "seguridad", joinColumns = { @JoinColumn(name = "cod_usuario", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "cod_rol", nullable = false, updatable = false) })
	public Set<Rol> getRols() {
		return this.rols;
	}

	public void setRols(Set<Rol> rols) {
		this.rols = rols;
	}

}
