package pe.com.soul.core.dao.entities;

// Generated 01/10/2015 10:53:53 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Modulo generated by hbm2java
 */
@Entity
@Table(name = "modulo", schema = "seguridad")
public class ModuloEntity implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private int codigoModulo;
	private String nombre;
	private int orden;
	private String descripcion;
	private String url;
	private Set<RolEntity> rols = new HashSet<RolEntity>(0);

	public ModuloEntity() {
	}

	public ModuloEntity(int codigoModulo, String nombre, int orden, String url) {
		this.codigoModulo = codigoModulo;
		this.nombre = nombre;
		this.orden = orden;
		this.url = url;
	}

	public ModuloEntity(int codigoModulo, String nombre, int orden,
			String descripcion, String url, Set<RolEntity> rols) {
		this.codigoModulo = codigoModulo;
		this.nombre = nombre;
		this.orden = orden;
		this.descripcion = descripcion;
		this.url = url;
		this.rols = rols;
	}

	@Id
	@Column(name = "codigo_modulo", unique = true, nullable = false)
	public int getCodigoModulo() {
		return this.codigoModulo;
	}

	public void setCodigoModulo(int codigoModulo) {
		this.codigoModulo = codigoModulo;
	}

	@Column(name = "nombre", nullable = false, length = 60)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "orden", nullable = false)
	public int getOrden() {
		return this.orden;
	}

	public void setOrden(int orden) {
		this.orden = orden;
	}

	@Column(name = "descripcion", length = 250)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "url", nullable = false, length = 120)
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "modulos")
	public Set<RolEntity> getRols() {
		return this.rols;
	}

	public void setRols(Set<RolEntity> rols) {
		this.rols = rols;
	}

}
