package pe.com.soul.core.dao.entities;

// Generated 02/10/2015 05:12:22 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Proceso generated by hbm2java
 */
@Entity
@Table(name = "proceso", schema = "proceso")
public class ProcesoEntity implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long codigoProceso;
	private ProcesoPlantillaEntity procesoPlantilla;
	private UsuarioEntity usuario;
	private int estadoProceso;
	private String nombreProceso;
	private String aleasProceso;
	private String versionProceso;
	private Date fechaCreacionProceso;
	private Date fechaTerminoProceso;
	private Set<TareaEntity> tareas = new HashSet<TareaEntity>(0);

	public ProcesoEntity() {
	}

	public ProcesoEntity(long codigoProceso, ProcesoPlantillaEntity procesoPlantilla,
			UsuarioEntity usuario, int estadoProceso, String nombreProceso,
			String aleasProceso, String versionProceso,
			Date fechaCreacionProceso) {
		this.codigoProceso = codigoProceso;
		this.procesoPlantilla = procesoPlantilla;
		this.usuario = usuario;
		this.estadoProceso = estadoProceso;
		this.nombreProceso = nombreProceso;
		this.aleasProceso = aleasProceso;
		this.versionProceso = versionProceso;
		this.fechaCreacionProceso = fechaCreacionProceso;
	}

	public ProcesoEntity(long codigoProceso, ProcesoPlantillaEntity procesoPlantilla,
			UsuarioEntity usuario, int estadoProceso, String nombreProceso,
			String aleasProceso, String versionProceso,
			Date fechaCreacionProceso, Date fechaTerminoProceso,
			Set<TareaEntity> tareas) {
		this.codigoProceso = codigoProceso;
		this.procesoPlantilla = procesoPlantilla;
		this.usuario = usuario;
		this.estadoProceso = estadoProceso;
		this.nombreProceso = nombreProceso;
		this.aleasProceso = aleasProceso;
		this.versionProceso = versionProceso;
		this.fechaCreacionProceso = fechaCreacionProceso;
		this.fechaTerminoProceso = fechaTerminoProceso;
		this.tareas = tareas;
	}

	@Id
	@GeneratedValue(generator="seq_codigo_proceso") 
    @SequenceGenerator(name="seq_codigo_proceso",sequenceName="proceso.seq_codigo_proceso", allocationSize=0) 
	@Column(name = "codigo_proceso", unique = true, nullable = false)
	public long getCodigoProceso() {
		return this.codigoProceso;
	}

	public void setCodigoProceso(long codigoProceso) {
		this.codigoProceso = codigoProceso;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codigo_proceso_plantilla", nullable = false)
	public ProcesoPlantillaEntity getProcesoPlantilla() {
		return this.procesoPlantilla;
	}

	public void setProcesoPlantilla(ProcesoPlantillaEntity procesoPlantilla) {
		this.procesoPlantilla = procesoPlantilla;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "usuario_creacion_proceso", nullable = false)
	public UsuarioEntity getUsuario() {
		return this.usuario;
	}

	public void setUsuario(UsuarioEntity usuario) {
		this.usuario = usuario;
	}

	@Column(name = "estado_proceso", nullable = false)
	public int getEstadoProceso() {
		return this.estadoProceso;
	}

	public void setEstadoProceso(int estadoProceso) {
		this.estadoProceso = estadoProceso;
	}

	@Column(name = "nombre_proceso", nullable = false, length = 120)
	public String getNombreProceso() {
		return this.nombreProceso;
	}

	public void setNombreProceso(String nombreProceso) {
		this.nombreProceso = nombreProceso;
	}

	@Column(name = "aleas_proceso", nullable = false, length = 100)
	public String getAleasProceso() {
		return this.aleasProceso;
	}

	public void setAleasProceso(String aleasProceso) {
		this.aleasProceso = aleasProceso;
	}

	@Column(name = "version_proceso", nullable = false, length = 12)
	public String getVersionProceso() {
		return this.versionProceso;
	}

	public void setVersionProceso(String versionProceso) {
		this.versionProceso = versionProceso;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_creacion_proceso", nullable = false, length = 29)
	public Date getFechaCreacionProceso() {
		return this.fechaCreacionProceso;
	}

	public void setFechaCreacionProceso(Date fechaCreacionProceso) {
		this.fechaCreacionProceso = fechaCreacionProceso;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_termino_proceso", length = 29)
	public Date getFechaTerminoProceso() {
		return this.fechaTerminoProceso;
	}

	public void setFechaTerminoProceso(Date fechaTerminoProceso) {
		this.fechaTerminoProceso = fechaTerminoProceso;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "proceso")
	public Set<TareaEntity> getTareas() {
		return this.tareas;
	}

	public void setTareas(Set<TareaEntity> tareas) {
		this.tareas = tareas;
	}

}
