package pe.com.soul.core.dao.entities;

// Generated 01/10/2015 10:53:53 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ProcesoPlantilla generated by hbm2java
 */
@Entity
@Table(name = "proceso_plantilla", schema = "proceso")
public class ProcesoPlantillaEntity implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long codigoProcesoPlantilla;
	private String version;
	private char estado;
	private String nombre;
	private String aleas;
	private Date fechaValidez;
	private boolean flagTodosInician;
	private Set<RolEntity> rols = new HashSet<RolEntity>(0);
	private Set<ProcesoEntity> procesos = new HashSet<ProcesoEntity>(0);
	private Set<TareaPlantillaEntity> tareaPlantillas = new HashSet<TareaPlantillaEntity>(0);
	private Set<RolEntity> rols_1 = new HashSet<RolEntity>(0);

	public ProcesoPlantillaEntity() {
	}

	public ProcesoPlantillaEntity(long codigoProcesoPlantilla, char estado,
			String nombre, String aleas, Date fechaValidez,
			boolean flagTodosInician) {
		this.codigoProcesoPlantilla = codigoProcesoPlantilla;
		this.estado = estado;
		this.nombre = nombre;
		this.aleas = aleas;
		this.fechaValidez = fechaValidez;
		this.flagTodosInician = flagTodosInician;
	}

	public ProcesoPlantillaEntity(long codigoProcesoPlantilla, char estado,
			String nombre, String aleas, Date fechaValidez,
			boolean flagTodosInician, Set<RolEntity> rols, Set<ProcesoEntity> procesos,
			Set<TareaPlantillaEntity> tareaPlantillas, Set<RolEntity> rols_1) {
		this.codigoProcesoPlantilla = codigoProcesoPlantilla;
		this.estado = estado;
		this.nombre = nombre;
		this.aleas = aleas;
		this.fechaValidez = fechaValidez;
		this.flagTodosInician = flagTodosInician;
		this.rols = rols;
		this.procesos = procesos;
		this.tareaPlantillas = tareaPlantillas;
		this.rols_1 = rols_1;
	}

	@Id
	@Column(name = "codigo_proceso_plantilla", unique = true, nullable = false)
	public long getCodigoProcesoPlantilla() {
		return this.codigoProcesoPlantilla;
	}

	public void setCodigoProcesoPlantilla(long codigoProcesoPlantilla) {
		this.codigoProcesoPlantilla = codigoProcesoPlantilla;
	}

	@Column(name = "version", nullable = false, length = 12)
	public String getVersion() {
		return this.version;
	}

	public void setVersion(String version) {
		this.version = version;
	}

	@Column(name = "estado", nullable = false, length = 1)
	public char getEstado() {
		return this.estado;
	}

	public void setEstado(char estado) {
		this.estado = estado;
	}

	@Column(name = "nombre", nullable = false, length = 120)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "aleas", nullable = false, length = 100)
	public String getAleas() {
		return this.aleas;
	}

	public void setAleas(String aleas) {
		this.aleas = aleas;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_validez", nullable = false, length = 29)
	public Date getFechaValidez() {
		return this.fechaValidez;
	}

	public void setFechaValidez(Date fechaValidez) {
		this.fechaValidez = fechaValidez;
	}

	@Column(name = "flag_todos_inician", nullable = false)
	public boolean isFlagTodosInician() {
		return this.flagTodosInician;
	}

	public void setFlagTodosInician(boolean flagTodosInician) {
		this.flagTodosInician = flagTodosInician;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "potencial_iniciador", schema = "proceso", joinColumns = { @JoinColumn(name = "codigo_proceso_plantilla", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "rol_codigo_rol", nullable = false, updatable = false) })
	public Set<RolEntity> getRols() {
		return this.rols;
	}

	public void setRols(Set<RolEntity> rols) {
		this.rols = rols;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "procesoPlantilla")
	public Set<ProcesoEntity> getProcesos() {
		return this.procesos;
	}

	public void setProcesos(Set<ProcesoEntity> procesos) {
		this.procesos = procesos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "procesoPlantilla")
	public Set<TareaPlantillaEntity> getTareaPlantillas() {
		return this.tareaPlantillas;
	}

	public void setTareaPlantillas(Set<TareaPlantillaEntity> tareaPlantillas) {
		this.tareaPlantillas = tareaPlantillas;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "administrador_proceso", schema = "proceso", joinColumns = { @JoinColumn(name = "codigo_proceso_plantilla", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "codigo_rol", nullable = false, updatable = false) })
	public Set<RolEntity> getRols_1() {
		return this.rols_1;
	}

	public void setRols_1(Set<RolEntity> rols_1) {
		this.rols_1 = rols_1;
	}

}
