package pe.com.soul.core.dao.entities;

// Generated 01/10/2015 10:53:53 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Proceso generated by hbm2java
 */
@Entity
@Table(name = "proceso", schema = "proceso")
public class ProcesoEntity implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long codigoProceso;
	private String version;
	private ProcesoPlantillaEntity procesoPlantilla;
	private UsuarioEntity usuario;
	private char estado;
	private String nombre;
	private String aleas;
	private Date fechaCreacion;
	private Date fechaTermino;
	private Set<TareaEntity> tareas = new HashSet<TareaEntity>(0);

	public ProcesoEntity() {
	}

	public ProcesoEntity(long codigoProceso, ProcesoPlantillaEntity procesoPlantilla,
			UsuarioEntity usuario, char estado, String nombre, String aleas,
			Date fechaCreacion) {
		this.codigoProceso = codigoProceso;
		this.procesoPlantilla = procesoPlantilla;
		this.usuario = usuario;
		this.estado = estado;
		this.nombre = nombre;
		this.aleas = aleas;
		this.fechaCreacion = fechaCreacion;
	}

	public ProcesoEntity(long codigoProceso, ProcesoPlantillaEntity procesoPlantilla,
			UsuarioEntity usuario, char estado, String nombre, String aleas,
			Date fechaCreacion, Date fechaTermino, Set<TareaEntity> tareas) {
		this.codigoProceso = codigoProceso;
		this.procesoPlantilla = procesoPlantilla;
		this.usuario = usuario;
		this.estado = estado;
		this.nombre = nombre;
		this.aleas = aleas;
		this.fechaCreacion = fechaCreacion;
		this.fechaTermino = fechaTermino;
		this.tareas = tareas;
	}

	@Id
	@GeneratedValue(generator="id_seq_codigo_proceso") 
    @SequenceGenerator(name="id_seq_codigo_proceso",sequenceName="proceso.seq_codigo_proceso", allocationSize=0)
	@Column(name = "codigo_proceso", unique = true, nullable = false)
	public long getCodigoProceso() {
		return this.codigoProceso;
	}

	public void setCodigoProceso(long codigoProceso) {
		this.codigoProceso = codigoProceso;
	}

	@Column(name = "version", nullable = false, length = 12)
	public String getVersion() {
		return this.version;
	}

	public void setVersion(String version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codigo_proceso_plantilla", nullable = false)
	public ProcesoPlantillaEntity getProcesoPlantilla() {
		return this.procesoPlantilla;
	}

	public void setProcesoPlantilla(ProcesoPlantillaEntity procesoPlantilla) {
		this.procesoPlantilla = procesoPlantilla;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codigo_usuario_creacion", nullable = false)
	public UsuarioEntity getUsuario() {
		return this.usuario;
	}

	public void setUsuario(UsuarioEntity usuario) {
		this.usuario = usuario;
	}

	@Column(name = "estado", nullable = false, length = 1)
	public char getEstado() {
		return this.estado;
	}

	public void setEstado(char estado) {
		this.estado = estado;
	}

	@Column(name = "nombre", nullable = false, length = 120)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "aleas", nullable = false, length = 100)
	public String getAleas() {
		return this.aleas;
	}

	public void setAleas(String aleas) {
		this.aleas = aleas;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_creacion", nullable = false, length = 29)
	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_termino", length = 29)
	public Date getFechaTermino() {
		return this.fechaTermino;
	}

	public void setFechaTermino(Date fechaTermino) {
		this.fechaTermino = fechaTermino;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "proceso")
	public Set<TareaEntity> getTareas() {
		return this.tareas;
	}

	public void setTareas(Set<TareaEntity> tareas) {
		this.tareas = tareas;
	}

}
