package pe.com.soul.core.dao.entities;

// Generated 07/10/2015 10:05:11 AM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ProcesoPlantilla generated by hbm2java
 */
@Entity
@Table(name = "proceso_plantilla", schema = "proceso")
public class ProcesoPlantillaEntity implements java.io.Serializable {

	private long codigoProcesoPlantilla;
	private char estadoProceso;
	private String nombreProceso;
	private String aleasProceso;
	private String versionProceso;
	private Date fechaValidezProceso;
	private boolean flagTodosInician;
	private Set<RolEntity> rols = new HashSet<RolEntity>(0);
	private Set<TareaPlantillaEntity> tareaPlantillas = new HashSet<TareaPlantillaEntity>(0);
	private Set<RolEntity> rols_1 = new HashSet<RolEntity>(0);

	public ProcesoPlantillaEntity() {
	}

	public ProcesoPlantillaEntity(long codigoProcesoPlantilla, char estadoProceso,
			String nombreProceso, String aleasProceso, String versionProceso,
			Date fechaValidezProceso, boolean flagTodosInician) {
		this.codigoProcesoPlantilla = codigoProcesoPlantilla;
		this.estadoProceso = estadoProceso;
		this.nombreProceso = nombreProceso;
		this.aleasProceso = aleasProceso;
		this.versionProceso = versionProceso;
		this.fechaValidezProceso = fechaValidezProceso;
		this.flagTodosInician = flagTodosInician;
	}

	public ProcesoPlantillaEntity(long codigoProcesoPlantilla, char estadoProceso,
			String nombreProceso, String aleasProceso, String versionProceso,
			Date fechaValidezProceso, boolean flagTodosInician, Set<RolEntity> rols,
			Set<TareaPlantillaEntity> tareaPlantillas, Set<RolEntity> rols_1) {
		this.codigoProcesoPlantilla = codigoProcesoPlantilla;
		this.estadoProceso = estadoProceso;
		this.nombreProceso = nombreProceso;
		this.aleasProceso = aleasProceso;
		this.versionProceso = versionProceso;
		this.fechaValidezProceso = fechaValidezProceso;
		this.flagTodosInician = flagTodosInician;
		this.rols = rols;
		this.tareaPlantillas = tareaPlantillas;
		this.rols_1 = rols_1;
	}

	@Id
	@Column(name = "codigo_proceso_plantilla", unique = true, nullable = false)
	public long getCodigoProcesoPlantilla() {
		return this.codigoProcesoPlantilla;
	}

	public void setCodigoProcesoPlantilla(long codigoProcesoPlantilla) {
		this.codigoProcesoPlantilla = codigoProcesoPlantilla;
	}

	@Column(name = "estado_proceso", nullable = false, length = 1)
	public char getEstadoProceso() {
		return this.estadoProceso;
	}

	public void setEstadoProceso(char estadoProceso) {
		this.estadoProceso = estadoProceso;
	}

	@Column(name = "nombre_proceso", nullable = false, length = 120)
	public String getNombreProceso() {
		return this.nombreProceso;
	}

	public void setNombreProceso(String nombreProceso) {
		this.nombreProceso = nombreProceso;
	}

	@Column(name = "aleas_proceso", nullable = false, length = 100)
	public String getAleasProceso() {
		return this.aleasProceso;
	}

	public void setAleasProceso(String aleasProceso) {
		this.aleasProceso = aleasProceso;
	}

	@Column(name = "version_proceso", nullable = false, length = 12)
	public String getVersionProceso() {
		return this.versionProceso;
	}

	public void setVersionProceso(String versionProceso) {
		this.versionProceso = versionProceso;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_validez_proceso", nullable = false, length = 29)
	public Date getFechaValidezProceso() {
		return this.fechaValidezProceso;
	}

	public void setFechaValidezProceso(Date fechaValidezProceso) {
		this.fechaValidezProceso = fechaValidezProceso;
	}

	@Column(name = "flag_todos_inician", nullable = false)
	public boolean isFlagTodosInician() {
		return this.flagTodosInician;
	}

	public void setFlagTodosInician(boolean flagTodosInician) {
		this.flagTodosInician = flagTodosInician;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "potencial_iniciador", schema = "proceso", joinColumns = { @JoinColumn(name = "codigo_proceso_plantilla", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "rol_codigo_rol", nullable = false, updatable = false) })
	public Set<RolEntity> getRols() {
		return this.rols;
	}

	public void setRols(Set<RolEntity> rols) {
		this.rols = rols;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "procesoPlantilla")
	public Set<TareaPlantillaEntity> getTareaPlantillas() {
		return this.tareaPlantillas;
	}

	public void setTareaPlantillas(Set<TareaPlantillaEntity> tareaPlantillas) {
		this.tareaPlantillas = tareaPlantillas;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "administrador_proceso", schema = "proceso", joinColumns = { @JoinColumn(name = "codigo_proceso_plantilla", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "codigo_rol", nullable = false, updatable = false) })
	public Set<RolEntity> getRols_1() {
		return this.rols_1;
	}

	public void setRols_1(Set<RolEntity> rols_1) {
		this.rols_1 = rols_1;
	}

}
