package pe.com.soul.core.dao.entities;

// Generated 07/10/2015 10:05:11 AM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TareaPlantilla generated by hbm2java
 */
@Entity
@Table(name = "tarea_plantilla", schema = "proceso")
public class TareaPlantillaEntity implements java.io.Serializable {

	private long codigoTareaPlantilla;
	private ProcesoPlantillaEntity procesoPlantilla;
	private int estadoTarea;
	private String nombreTarea;
	private String aleasTarea;
	private String versionTarea;
	private int prioridadTarea;
	private int ordenTarea;
	private Set<RolEntity> rols = new HashSet<RolEntity>(0);
	private Set<RolEntity> rols_1 = new HashSet<RolEntity>(0);
	private Set<RolEntity> rols_2 = new HashSet<RolEntity>(0);

	public TareaPlantillaEntity() {
	}

	public TareaPlantillaEntity(long codigoTareaPlantilla,
			ProcesoPlantillaEntity procesoPlantilla, int estadoTarea,
			String nombreTarea, String aleasTarea, String versionTarea,
			int prioridadTarea, int ordenTarea) {
		this.codigoTareaPlantilla = codigoTareaPlantilla;
		this.procesoPlantilla = procesoPlantilla;
		this.estadoTarea = estadoTarea;
		this.nombreTarea = nombreTarea;
		this.aleasTarea = aleasTarea;
		this.versionTarea = versionTarea;
		this.prioridadTarea = prioridadTarea;
		this.ordenTarea = ordenTarea;
	}

	public TareaPlantillaEntity(long codigoTareaPlantilla,
			ProcesoPlantillaEntity procesoPlantilla, int estadoTarea,
			String nombreTarea, String aleasTarea, String versionTarea,
			int prioridadTarea, int ordenTarea, Set<RolEntity> rols, Set<RolEntity> rols_1,
			Set<RolEntity> rols_2) {
		this.codigoTareaPlantilla = codigoTareaPlantilla;
		this.procesoPlantilla = procesoPlantilla;
		this.estadoTarea = estadoTarea;
		this.nombreTarea = nombreTarea;
		this.aleasTarea = aleasTarea;
		this.versionTarea = versionTarea;
		this.prioridadTarea = prioridadTarea;
		this.ordenTarea = ordenTarea;
		this.rols = rols;
		this.rols_1 = rols_1;
		this.rols_2 = rols_2;
	}

	@Id
	@Column(name = "codigo_tarea_plantilla", unique = true, nullable = false)
	public long getCodigoTareaPlantilla() {
		return this.codigoTareaPlantilla;
	}

	public void setCodigoTareaPlantilla(long codigoTareaPlantilla) {
		this.codigoTareaPlantilla = codigoTareaPlantilla;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codigo_proceso_plantilla", nullable = false)
	public ProcesoPlantillaEntity getProcesoPlantilla() {
		return this.procesoPlantilla;
	}

	public void setProcesoPlantilla(ProcesoPlantillaEntity procesoPlantilla) {
		this.procesoPlantilla = procesoPlantilla;
	}

	@Column(name = "estado_tarea", nullable = false)
	public int getEstadoTarea() {
		return this.estadoTarea;
	}

	public void setEstadoTarea(int estadoTarea) {
		this.estadoTarea = estadoTarea;
	}

	@Column(name = "nombre_tarea", nullable = false, length = 120)
	public String getNombreTarea() {
		return this.nombreTarea;
	}

	public void setNombreTarea(String nombreTarea) {
		this.nombreTarea = nombreTarea;
	}

	@Column(name = "aleas_tarea", nullable = false, length = 100)
	public String getAleasTarea() {
		return this.aleasTarea;
	}

	public void setAleasTarea(String aleasTarea) {
		this.aleasTarea = aleasTarea;
	}

	@Column(name = "version_tarea", nullable = false, length = 12)
	public String getVersionTarea() {
		return this.versionTarea;
	}

	public void setVersionTarea(String versionTarea) {
		this.versionTarea = versionTarea;
	}

	@Column(name = "prioridad_tarea", nullable = false)
	public int getPrioridadTarea() {
		return this.prioridadTarea;
	}

	public void setPrioridadTarea(int prioridadTarea) {
		this.prioridadTarea = prioridadTarea;
	}

	@Column(name = "orden_tarea", nullable = false)
	public int getOrdenTarea() {
		return this.ordenTarea;
	}

	public void setOrdenTarea(int ordenTarea) {
		this.ordenTarea = ordenTarea;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "potencial_dueno", schema = "proceso", joinColumns = { @JoinColumn(name = "codigo_tarea_plantilla", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "codigo_rol", nullable = false, updatable = false) })
	public Set<RolEntity> getRols() {
		return this.rols;
	}

	public void setRols(Set<RolEntity> rols) {
		this.rols = rols;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "editor_tarea", schema = "proceso", joinColumns = { @JoinColumn(name = "codigo_tarea_plantilla", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "codigo_rol", nullable = false, updatable = false) })
	public Set<RolEntity> getRols_1() {
		return this.rols_1;
	}

	public void setRols_1(Set<RolEntity> rols_1) {
		this.rols_1 = rols_1;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "administrador_tarea", schema = "proceso", joinColumns = { @JoinColumn(name = "codigo_tarea_plantilla", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "codigo_rol", nullable = false, updatable = false) })
	public Set<RolEntity> getRols_2() {
		return this.rols_2;
	}

	public void setRols_2(Set<RolEntity> rols_2) {
		this.rols_2 = rols_2;
	}

}
