package pe.com.soul.core.dao.entities;

// Generated 01/10/2015 10:53:53 PM by Hibernate Tools 4.3.1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Tarea generated by hbm2java
 */
@Entity
@Table(name = "tarea", schema = "proceso")
public class TareaEntity implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long codigoTarea;
	private String version;
	private ProcesoEntity proceso;
	private TareaPlantillaEntity tareaPlantilla;
	private char estado;
	private String nombre;
	private String aleas;
	private int prioridad;
	private Date fechaCreacion;
	private Date fechaReclamo;
	private Date fechaTermino;
	private Date fechaUltimaModificacion;
	private String dueno;

	public TareaEntity() {
	}

	public TareaEntity(long codigoTarea, ProcesoEntity proceso,
			TareaPlantillaEntity tareaPlantilla, char estado, String nombre,
			String aleas, int prioridad, Date fechaCreacion,
			Date fechaUltimaModificacion) {
		this.codigoTarea = codigoTarea;
		this.proceso = proceso;
		this.tareaPlantilla = tareaPlantilla;
		this.estado = estado;
		this.nombre = nombre;
		this.aleas = aleas;
		this.prioridad = prioridad;
		this.fechaCreacion = fechaCreacion;
		this.fechaUltimaModificacion = fechaUltimaModificacion;
	}

	public TareaEntity(long codigoTarea, ProcesoEntity proceso,
			TareaPlantillaEntity tareaPlantilla, char estado, String nombre,
			String aleas, int prioridad, Date fechaCreacion, Date fechaReclamo,
			Date fechaTermino, Date fechaUltimaModificacion, String dueno) {
		this.codigoTarea = codigoTarea;
		this.proceso = proceso;
		this.tareaPlantilla = tareaPlantilla;
		this.estado = estado;
		this.nombre = nombre;
		this.aleas = aleas;
		this.prioridad = prioridad;
		this.fechaCreacion = fechaCreacion;
		this.fechaReclamo = fechaReclamo;
		this.fechaTermino = fechaTermino;
		this.fechaUltimaModificacion = fechaUltimaModificacion;
		this.dueno = dueno;
	}

	@Id
	@GeneratedValue(generator="id_seq_codigo_tarea") 
    @SequenceGenerator(name="id_seq_codigo_tarea",sequenceName="proceso.seq_codigo_tarea", allocationSize=0)
	@Column(name = "codigo_tarea", unique = true, nullable = false)
	public long getCodigoTarea() {
		return this.codigoTarea;
	}

	public void setCodigoTarea(long codigoTarea) {
		this.codigoTarea = codigoTarea;
	}

	@Column(name = "version", nullable = false, length = 12)
	public String getVersion() {
		return this.version;
	}

	public void setVersion(String version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codigo_proceso", nullable = false)
	public ProcesoEntity getProceso() {
		return this.proceso;
	}

	public void setProceso(ProcesoEntity proceso) {
		this.proceso = proceso;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codigo_tarea_plantilla", nullable = false)
	public TareaPlantillaEntity getTareaPlantilla() {
		return this.tareaPlantilla;
	}

	public void setTareaPlantilla(TareaPlantillaEntity tareaPlantilla) {
		this.tareaPlantilla = tareaPlantilla;
	}

	@Column(name = "estado", nullable = false, length = 1)
	public char getEstado() {
		return this.estado;
	}

	public void setEstado(char estado) {
		this.estado = estado;
	}

	@Column(name = "nombre", nullable = false, length = 120)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "aleas", nullable = false, length = 100)
	public String getAleas() {
		return this.aleas;
	}

	public void setAleas(String aleas) {
		this.aleas = aleas;
	}

	@Column(name = "prioridad", nullable = false)
	public int getPrioridad() {
		return this.prioridad;
	}

	public void setPrioridad(int prioridad) {
		this.prioridad = prioridad;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_creacion", nullable = false, length = 29)
	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_reclamo", length = 29)
	public Date getFechaReclamo() {
		return this.fechaReclamo;
	}

	public void setFechaReclamo(Date fechaReclamo) {
		this.fechaReclamo = fechaReclamo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_termino", length = 29)
	public Date getFechaTermino() {
		return this.fechaTermino;
	}

	public void setFechaTermino(Date fechaTermino) {
		this.fechaTermino = fechaTermino;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_ultima_modificacion", nullable = false, length = 29)
	public Date getFechaUltimaModificacion() {
		return this.fechaUltimaModificacion;
	}

	public void setFechaUltimaModificacion(Date fechaUltimaModificacion) {
		this.fechaUltimaModificacion = fechaUltimaModificacion;
	}

	@Column(name = "dueno", length = 40)
	public String getDueno() {
		return this.dueno;
	}

	public void setDueno(String dueno) {
		this.dueno = dueno;
	}

}
