package pe.com.soul.core.dao.entities;

// Generated 01/10/2015 10:53:53 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TareaPlantilla generated by hbm2java
 */
@Entity
@Table(name = "tarea_plantilla", schema = "proceso")
public class TareaPlantillaEntity implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long codigoTareaPlantilla;
	private String version;
	private ProcesoPlantillaEntity procesoPlantilla;
	private char estado;
	private String nombre;
	private String aleas;
	private int prioridad;
	private int orden;
	private Set<RolEntity> rols = new HashSet<RolEntity>(0);
	private Set<RolEntity> rols_1 = new HashSet<RolEntity>(0);
	private Set<RolEntity> rols_2 = new HashSet<RolEntity>(0);
	private Set<TareaEntity> tareas = new HashSet<TareaEntity>(0);

	public TareaPlantillaEntity() {
	}

	public TareaPlantillaEntity(long codigoTareaPlantilla,
			ProcesoPlantillaEntity procesoPlantilla, char estado, String nombre,
			String aleas, int prioridad, int orden) {
		this.codigoTareaPlantilla = codigoTareaPlantilla;
		this.procesoPlantilla = procesoPlantilla;
		this.estado = estado;
		this.nombre = nombre;
		this.aleas = aleas;
		this.prioridad = prioridad;
		this.orden = orden;
	}

	public TareaPlantillaEntity(long codigoTareaPlantilla,
			ProcesoPlantillaEntity procesoPlantilla, char estado, String nombre,
			String aleas, int prioridad, int orden, Set<RolEntity> rols,
			Set<RolEntity> rols_1, Set<RolEntity> rols_2, Set<TareaEntity> tareas) {
		this.codigoTareaPlantilla = codigoTareaPlantilla;
		this.procesoPlantilla = procesoPlantilla;
		this.estado = estado;
		this.nombre = nombre;
		this.aleas = aleas;
		this.prioridad = prioridad;
		this.orden = orden;
		this.rols = rols;
		this.rols_1 = rols_1;
		this.rols_2 = rols_2;
		this.tareas = tareas;
	}

	@Id
	@Column(name = "codigo_tarea_plantilla", unique = true, nullable = false)
	public long getCodigoTareaPlantilla() {
		return this.codigoTareaPlantilla;
	}

	public void setCodigoTareaPlantilla(long codigoTareaPlantilla) {
		this.codigoTareaPlantilla = codigoTareaPlantilla;
	}

	@Column(name = "version", nullable = false, length = 12)
	public String getVersion() {
		return this.version;
	}

	public void setVersion(String version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codigo_proceso_plantilla", nullable = false)
	public ProcesoPlantillaEntity getProcesoPlantilla() {
		return this.procesoPlantilla;
	}

	public void setProcesoPlantilla(ProcesoPlantillaEntity procesoPlantilla) {
		this.procesoPlantilla = procesoPlantilla;
	}

	@Column(name = "estado", nullable = false, length = 1)
	public char getEstado() {
		return this.estado;
	}

	public void setEstado(char estado) {
		this.estado = estado;
	}

	@Column(name = "nombre", nullable = false, length = 120)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "aleas", nullable = false, length = 100)
	public String getAleas() {
		return this.aleas;
	}

	public void setAleas(String aleas) {
		this.aleas = aleas;
	}

	@Column(name = "prioridad", nullable = false)
	public int getPrioridad() {
		return this.prioridad;
	}

	public void setPrioridad(int prioridad) {
		this.prioridad = prioridad;
	}

	@Column(name = "orden", nullable = false)
	public int getOrden() {
		return this.orden;
	}

	public void setOrden(int orden) {
		this.orden = orden;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "potencial_dueno", schema = "proceso", joinColumns = { @JoinColumn(name = "codigo_tarea_plantilla", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "codigo_rol", nullable = false, updatable = false) })
	public Set<RolEntity> getRols() {
		return this.rols;
	}

	public void setRols(Set<RolEntity> rols) {
		this.rols = rols;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "editor_tarea", schema = "proceso", joinColumns = { @JoinColumn(name = "codigo_tarea_plantilla", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "codigo_rol", nullable = false, updatable = false) })
	public Set<RolEntity> getRols_1() {
		return this.rols_1;
	}

	public void setRols_1(Set<RolEntity> rols_1) {
		this.rols_1 = rols_1;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "administrador_tarea", schema = "proceso", joinColumns = { @JoinColumn(name = "codigo_tarea_plantilla", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "codigo_rol", nullable = false, updatable = false) })
	public Set<RolEntity> getRols_2() {
		return this.rols_2;
	}

	public void setRols_2(Set<RolEntity> rols_2) {
		this.rols_2 = rols_2;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tareaPlantilla")
	public Set<TareaEntity> getTareas() {
		return this.tareas;
	}

	public void setTareas(Set<TareaEntity> tareas) {
		this.tareas = tareas;
	}

}
