package pe.com.soul.core.dao.entities;

// Generated 01/10/2015 10:53:53 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TareaPotenciaDuenoId generated by hbm2java
 */
@Embeddable
public class TareaPotenciaDuenoIdEntity implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Long codigoTarea;
	private Long codigoProceso;
	private Long codigoTareaPlantilla;
	private Character estado;
	private String nombre;
	private String aleas;
	private String version;
	private Integer prioridad;
	private Date fechaCreacion;
	private Date fechaReclamo;
	private Date fechaTermino;
	private Date fechaUltimaModificacion;
	private String dueno;
	private Long codigoUsuario;

	public TareaPotenciaDuenoIdEntity() {
	}

	public TareaPotenciaDuenoIdEntity(Long codigoTarea, Long codigoProceso,
			Long codigoTareaPlantilla, Character estado, String nombre,
			String aleas, String version, Integer prioridad,
			Date fechaCreacion, Date fechaReclamo, Date fechaTermino,
			Date fechaUltimaModificacion, String dueno, Long codigoUsuario) {
		this.codigoTarea = codigoTarea;
		this.codigoProceso = codigoProceso;
		this.codigoTareaPlantilla = codigoTareaPlantilla;
		this.estado = estado;
		this.nombre = nombre;
		this.aleas = aleas;
		this.version = version;
		this.prioridad = prioridad;
		this.fechaCreacion = fechaCreacion;
		this.fechaReclamo = fechaReclamo;
		this.fechaTermino = fechaTermino;
		this.fechaUltimaModificacion = fechaUltimaModificacion;
		this.dueno = dueno;
		this.codigoUsuario = codigoUsuario;
	}

	@Column(name = "codigo_tarea")
	public Long getCodigoTarea() {
		return this.codigoTarea;
	}

	public void setCodigoTarea(Long codigoTarea) {
		this.codigoTarea = codigoTarea;
	}

	@Column(name = "codigo_proceso")
	public Long getCodigoProceso() {
		return this.codigoProceso;
	}

	public void setCodigoProceso(Long codigoProceso) {
		this.codigoProceso = codigoProceso;
	}

	@Column(name = "codigo_tarea_plantilla")
	public Long getCodigoTareaPlantilla() {
		return this.codigoTareaPlantilla;
	}

	public void setCodigoTareaPlantilla(Long codigoTareaPlantilla) {
		this.codigoTareaPlantilla = codigoTareaPlantilla;
	}

	@Column(name = "estado", length = 1)
	public Character getEstado() {
		return this.estado;
	}

	public void setEstado(Character estado) {
		this.estado = estado;
	}

	@Column(name = "nombre", length = 120)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "aleas", length = 100)
	public String getAleas() {
		return this.aleas;
	}

	public void setAleas(String aleas) {
		this.aleas = aleas;
	}

	@Column(name = "version", length = 12)
	public String getVersion() {
		return this.version;
	}

	public void setVersion(String version) {
		this.version = version;
	}

	@Column(name = "prioridad")
	public Integer getPrioridad() {
		return this.prioridad;
	}

	public void setPrioridad(Integer prioridad) {
		this.prioridad = prioridad;
	}

	@Column(name = "fecha_creacion", length = 29)
	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	@Column(name = "fecha_reclamo", length = 29)
	public Date getFechaReclamo() {
		return this.fechaReclamo;
	}

	public void setFechaReclamo(Date fechaReclamo) {
		this.fechaReclamo = fechaReclamo;
	}

	@Column(name = "fecha_termino", length = 29)
	public Date getFechaTermino() {
		return this.fechaTermino;
	}

	public void setFechaTermino(Date fechaTermino) {
		this.fechaTermino = fechaTermino;
	}

	@Column(name = "fecha_ultima_modificacion", length = 29)
	public Date getFechaUltimaModificacion() {
		return this.fechaUltimaModificacion;
	}

	public void setFechaUltimaModificacion(Date fechaUltimaModificacion) {
		this.fechaUltimaModificacion = fechaUltimaModificacion;
	}

	@Column(name = "dueno", length = 40)
	public String getDueno() {
		return this.dueno;
	}

	public void setDueno(String dueno) {
		this.dueno = dueno;
	}

	@Column(name = "codigo_usuario")
	public Long getCodigoUsuario() {
		return this.codigoUsuario;
	}

	public void setCodigoUsuario(Long codigoUsuario) {
		this.codigoUsuario = codigoUsuario;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TareaPotenciaDuenoIdEntity))
			return false;
		TareaPotenciaDuenoIdEntity castOther = (TareaPotenciaDuenoIdEntity) other;

		return ((this.getCodigoTarea() == castOther.getCodigoTarea()) || (this
				.getCodigoTarea() != null && castOther.getCodigoTarea() != null && this
				.getCodigoTarea().equals(castOther.getCodigoTarea())))
				&& ((this.getCodigoProceso() == castOther.getCodigoProceso()) || (this
						.getCodigoProceso() != null
						&& castOther.getCodigoProceso() != null && this
						.getCodigoProceso()
						.equals(castOther.getCodigoProceso())))
				&& ((this.getCodigoTareaPlantilla() == castOther
						.getCodigoTareaPlantilla()) || (this
						.getCodigoTareaPlantilla() != null
						&& castOther.getCodigoTareaPlantilla() != null && this
						.getCodigoTareaPlantilla().equals(
								castOther.getCodigoTareaPlantilla())))
				&& ((this.getEstado() == castOther.getEstado()) || (this
						.getEstado() != null && castOther.getEstado() != null && this
						.getEstado().equals(castOther.getEstado())))
				&& ((this.getNombre() == castOther.getNombre()) || (this
						.getNombre() != null && castOther.getNombre() != null && this
						.getNombre().equals(castOther.getNombre())))
				&& ((this.getAleas() == castOther.getAleas()) || (this
						.getAleas() != null && castOther.getAleas() != null && this
						.getAleas().equals(castOther.getAleas())))
				&& ((this.getVersion() == castOther.getVersion()) || (this
						.getVersion() != null && castOther.getVersion() != null && this
						.getVersion().equals(castOther.getVersion())))
				&& ((this.getPrioridad() == castOther.getPrioridad()) || (this
						.getPrioridad() != null
						&& castOther.getPrioridad() != null && this
						.getPrioridad().equals(castOther.getPrioridad())))
				&& ((this.getFechaCreacion() == castOther.getFechaCreacion()) || (this
						.getFechaCreacion() != null
						&& castOther.getFechaCreacion() != null && this
						.getFechaCreacion()
						.equals(castOther.getFechaCreacion())))
				&& ((this.getFechaReclamo() == castOther.getFechaReclamo()) || (this
						.getFechaReclamo() != null
						&& castOther.getFechaReclamo() != null && this
						.getFechaReclamo().equals(castOther.getFechaReclamo())))
				&& ((this.getFechaTermino() == castOther.getFechaTermino()) || (this
						.getFechaTermino() != null
						&& castOther.getFechaTermino() != null && this
						.getFechaTermino().equals(castOther.getFechaTermino())))
				&& ((this.getFechaUltimaModificacion() == castOther
						.getFechaUltimaModificacion()) || (this
						.getFechaUltimaModificacion() != null
						&& castOther.getFechaUltimaModificacion() != null && this
						.getFechaUltimaModificacion().equals(
								castOther.getFechaUltimaModificacion())))
				&& ((this.getDueno() == castOther.getDueno()) || (this
						.getDueno() != null && castOther.getDueno() != null && this
						.getDueno().equals(castOther.getDueno())))
				&& ((this.getCodigoUsuario() == castOther.getCodigoUsuario()) || (this
						.getCodigoUsuario() != null
						&& castOther.getCodigoUsuario() != null && this
						.getCodigoUsuario()
						.equals(castOther.getCodigoUsuario())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getCodigoTarea() == null ? 0 : this.getCodigoTarea()
						.hashCode());
		result = 37
				* result
				+ (getCodigoProceso() == null ? 0 : this.getCodigoProceso()
						.hashCode());
		result = 37
				* result
				+ (getCodigoTareaPlantilla() == null ? 0 : this
						.getCodigoTareaPlantilla().hashCode());
		result = 37 * result
				+ (getEstado() == null ? 0 : this.getEstado().hashCode());
		result = 37 * result
				+ (getNombre() == null ? 0 : this.getNombre().hashCode());
		result = 37 * result
				+ (getAleas() == null ? 0 : this.getAleas().hashCode());
		result = 37 * result
				+ (getVersion() == null ? 0 : this.getVersion().hashCode());
		result = 37 * result
				+ (getPrioridad() == null ? 0 : this.getPrioridad().hashCode());
		result = 37
				* result
				+ (getFechaCreacion() == null ? 0 : this.getFechaCreacion()
						.hashCode());
		result = 37
				* result
				+ (getFechaReclamo() == null ? 0 : this.getFechaReclamo()
						.hashCode());
		result = 37
				* result
				+ (getFechaTermino() == null ? 0 : this.getFechaTermino()
						.hashCode());
		result = 37
				* result
				+ (getFechaUltimaModificacion() == null ? 0 : this
						.getFechaUltimaModificacion().hashCode());
		result = 37 * result
				+ (getDueno() == null ? 0 : this.getDueno().hashCode());
		result = 37
				* result
				+ (getCodigoUsuario() == null ? 0 : this.getCodigoUsuario()
						.hashCode());
		return result;
	}

}
