package pe.com.soul.core.dao.entities;

// Generated 01/10/2015 10:53:53 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name = "usuario", schema = "seguridad")
public class UsuarioEntity implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long codigoUsuario;
	private char estado;
	private String usuario;
	private String clave;
	private String nombreCompleto;
	private String correo;
	private Set<ProcesoEntity> procesos = new HashSet<ProcesoEntity>(0);
	private Set<RolEntity> rols = new HashSet<RolEntity>(0);

	public UsuarioEntity() {
	}

	public UsuarioEntity(long codigoUsuario, char estado, String usuario,
			String clave, String nombreCompleto) {
		this.codigoUsuario = codigoUsuario;
		this.estado = estado;
		this.usuario = usuario;
		this.clave = clave;
		this.nombreCompleto = nombreCompleto;
	}

	public UsuarioEntity(long codigoUsuario, char estado, String usuario,
			String clave, String nombreCompleto, String correo,
			Set<ProcesoEntity> procesos, Set<RolEntity> rols) {
		this.codigoUsuario = codigoUsuario;
		this.estado = estado;
		this.usuario = usuario;
		this.clave = clave;
		this.nombreCompleto = nombreCompleto;
		this.correo = correo;
		this.procesos = procesos;
		this.rols = rols;
	}

	@Id
	@Column(name = "codigo_usuario", unique = true, nullable = false)
	public long getCodigoUsuario() {
		return this.codigoUsuario;
	}

	public void setCodigoUsuario(long codigoUsuario) {
		this.codigoUsuario = codigoUsuario;
	}

	@Column(name = "estado", nullable = false, length = 1)
	public char getEstado() {
		return this.estado;
	}

	public void setEstado(char estado) {
		this.estado = estado;
	}

	@Column(name = "usuario", nullable = false, length = 40)
	public String getUsuario() {
		return this.usuario;
	}

	public void setUsuario(String usuario) {
		this.usuario = usuario;
	}

	@Column(name = "clave", nullable = false, length = 20)
	public String getClave() {
		return this.clave;
	}

	public void setClave(String clave) {
		this.clave = clave;
	}

	@Column(name = "nombre_completo", nullable = false, length = 120)
	public String getNombreCompleto() {
		return this.nombreCompleto;
	}

	public void setNombreCompleto(String nombreCompleto) {
		this.nombreCompleto = nombreCompleto;
	}

	@Column(name = "correo", length = 120)
	public String getCorreo() {
		return this.correo;
	}

	public void setCorreo(String correo) {
		this.correo = correo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usuario")
	public Set<ProcesoEntity> getProcesos() {
		return this.procesos;
	}

	public void setProcesos(Set<ProcesoEntity> procesos) {
		this.procesos = procesos;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "usuario_rol", schema = "seguridad", joinColumns = { @JoinColumn(name = "codigo_usuario", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "codigo_rol", nullable = false, updatable = false) })
	public Set<RolEntity> getRols() {
		return this.rols;
	}

	public void setRols(Set<RolEntity> rols) {
		this.rols = rols;
	}

}
