package pe.com.soul.core.dao.jpa;

// Generated 25/09/2015 04:29:28 PM by Hibernate Tools 4.3.1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ModRol generated by hbm2java
 */
@Entity
@Table(name = "mod_rol", schema = "public")
public class ModRolJPA implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private ModRolIdJPA id;

	public ModRolJPA() {
	}

	public ModRolJPA(ModRolIdJPA id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "codRol", column = @Column(name = "cod_rol", nullable = false)),
			@AttributeOverride(name = "codModulo", column = @Column(name = "cod_modulo", nullable = false)) })
	public ModRolIdJPA getId() {
		return this.id;
	}

	public void setId(ModRolIdJPA id) {
		this.id = id;
	}

}
