package pe.com.soul.core.dao.jpa;

// Generated 25/09/2015 04:29:28 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ModRolId generated by hbm2java
 */
@Embeddable
public class ModRolIdJPA implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long codRol;
	private int codModulo;

	public ModRolIdJPA() {
	}

	public ModRolIdJPA(long codRol, int codModulo) {
		this.codRol = codRol;
		this.codModulo = codModulo;
	}

	@Column(name = "cod_rol", nullable = false)
	public long getCodRol() {
		return this.codRol;
	}

	public void setCodRol(long codRol) {
		this.codRol = codRol;
	}

	@Column(name = "cod_modulo", nullable = false)
	public int getCodModulo() {
		return this.codModulo;
	}

	public void setCodModulo(int codModulo) {
		this.codModulo = codModulo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ModRolIdJPA))
			return false;
		ModRolIdJPA castOther = (ModRolIdJPA) other;

		return (this.getCodRol() == castOther.getCodRol())
				&& (this.getCodModulo() == castOther.getCodModulo());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getCodRol();
		result = 37 * result + this.getCodModulo();
		return result;
	}

}
