package pe.com.soul.core.dao.jpa;

// Generated 24/09/2015 09:34:46 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Modulo generated by hbm2java
 */
@Entity
@Table(name = "modulo", schema = "seguridad")
public class ModuloJPA extends JpaBase {
	
	private static final long serialVersionUID = 1L;
	
	private int codModulo;
	private String nombre;
	private int orden;
	private Set<RolJPA> rols = new HashSet<RolJPA>(0);

	public ModuloJPA() {
	}

	public ModuloJPA(int codModulo, String nombre, int orden) {
		this.codModulo = codModulo;
		this.nombre = nombre;
		this.orden = orden;
	}

	public ModuloJPA(int codModulo, String nombre, int orden, Set<RolJPA> rols) {
		this.codModulo = codModulo;
		this.nombre = nombre;
		this.orden = orden;
		this.rols = rols;
	}

	@Id
	@Column(name = "cod_modulo", unique = true, nullable = false)
	public int getCodModulo() {
		return this.codModulo;
	}

	public void setCodModulo(int codModulo) {
		this.codModulo = codModulo;
	}

	@Column(name = "nombre", nullable = false, length = 60)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "orden", nullable = false)
	public int getOrden() {
		return this.orden;
	}

	public void setOrden(int orden) {
		this.orden = orden;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "modulos")
	public Set<RolJPA> getRols() {
		return this.rols;
	}

	public void setRols(Set<RolJPA> rols) {
		this.rols = rols;
	}

}
