package pe.com.soul.core.dao.jpa;

// Generated 24/09/2015 09:34:46 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ProInstancia generated by hbm2java
 */
@Entity
@Table(name = "pro_instancia", schema = "proceso")
public class ProcesoJPA extends JpaBase {
	
	private static final long serialVersionUID = 1L;
	
	private long codProceso;
	private ProcesoPlantillaJPA proPlantilla;
	private char estado;
	private Set<TareaJPA> tarInstancias = new HashSet<TareaJPA>(0);

	public ProcesoJPA() {
	}

	public ProcesoJPA(long codProceso, ProcesoPlantillaJPA proPlantilla, char estado) {
		this.codProceso = codProceso;
		this.proPlantilla = proPlantilla;
		this.estado = estado;
	}

	public ProcesoJPA(long codProceso, ProcesoPlantillaJPA proPlantilla,
			char estado, Set<TareaJPA> tarInstancias) {
		this.codProceso = codProceso;
		this.proPlantilla = proPlantilla;
		this.estado = estado;
		this.tarInstancias = tarInstancias;
	}

	@Id
	@Column(name = "cod_proceso", unique = true, nullable = false)
	public long getCodProceso() {
		return this.codProceso;
	}

	public void setCodProceso(long codProceso) {
		this.codProceso = codProceso;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cod_pro_plantilla", nullable = false)
	public ProcesoPlantillaJPA getProPlantilla() {
		return this.proPlantilla;
	}

	public void setProPlantilla(ProcesoPlantillaJPA proPlantilla) {
		this.proPlantilla = proPlantilla;
	}

	@Column(name = "estado", nullable = false, length = 1)
	public char getEstado() {
		return this.estado;
	}

	public void setEstado(char estado) {
		this.estado = estado;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "proInstancia")
	public Set<TareaJPA> getTarInstancias() {
		return this.tarInstancias;
	}

	public void setTarInstancias(Set<TareaJPA> tarInstancias) {
		this.tarInstancias = tarInstancias;
	}

}
