package pe.com.soul.core.dao.jpa;

// Generated 24/09/2015 09:34:46 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

import pe.com.soul.core.modelo.Rol;

/**
 * Rol generated by hbm2java
 */
@Entity
@Table(name = "rol", schema = "seguridad")
public class RolJPA extends Rol {

	private static final long serialVersionUID = 1L;

	private Set<ModuloJPA> modulos = new HashSet<ModuloJPA>(0);
	private Set<ProcesoPlantillaJPA> proPlantillas = new HashSet<ProcesoPlantillaJPA>(0);
	private Set<TareaPlantillaJPA> tarPlantillas = new HashSet<TareaPlantillaJPA>(0);
	private Set<UsuarioJPA> usuarios = new HashSet<UsuarioJPA>(0);

	public RolJPA() {
	}

	public RolJPA(long codRol, String nombre) {
		this.codRol = codRol;
		this.nombre = nombre;
	}

	public RolJPA(long codRol, String nombre, Set<ModuloJPA> modulos,
			Set<ProcesoPlantillaJPA> proPlantillas, Set<TareaPlantillaJPA> tarPlantillas,
			Set<UsuarioJPA> usuarios) {
		this.codRol = codRol;
		this.nombre = nombre;
		this.modulos = modulos;
		this.proPlantillas = proPlantillas;
		this.tarPlantillas = tarPlantillas;
		this.usuarios = usuarios;
	}

	@Id
	@Column(name = "cod_rol", unique = true, nullable = false)
	public long getCodRol() {
		return this.codRol;
	}

	public void setCodRol(long codRol) {
		this.codRol = codRol;
	}

	@Column(name = "nombre", nullable = false, length = 120)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "mod_rol", schema = "public", joinColumns = { @JoinColumn(name = "cod_rol", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "cod_modulo", nullable = false, updatable = false) })
	public Set<ModuloJPA> getModulos() {
		return this.modulos;
	}

	public void setModulos(Set<ModuloJPA> modulos) {
		this.modulos = modulos;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "rols")
	public Set<ProcesoPlantillaJPA> getProPlantillas() {
		return this.proPlantillas;
	}

	public void setProPlantillas(Set<ProcesoPlantillaJPA> proPlantillas) {
		this.proPlantillas = proPlantillas;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "rols")
	public Set<TareaPlantillaJPA> getTarPlantillas() {
		return this.tarPlantillas;
	}

	public void setTarPlantillas(Set<TareaPlantillaJPA> tarPlantillas) {
		this.tarPlantillas = tarPlantillas;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "rols")
	public Set<UsuarioJPA> getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Set<UsuarioJPA> usuarios) {
		this.usuarios = usuarios;
	}

}
