package pe.com.soul.core.dao.jpa;

// Generated 25/09/2015 04:29:28 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Rol generated by hbm2java
 */
@Entity
@Table(name = "rol", schema = "seguridad")
public class RolJPA implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long codigoRol;
	private String nombre;
	private Set<TareaPlantillaJPA> tareaPlantillas = new HashSet<TareaPlantillaJPA>(0);
	private Set<ModuloJPA> modulos = new HashSet<ModuloJPA>(0);
	private Set<ProcesoPlantillaJPA> procesoPlantillas = new HashSet<ProcesoPlantillaJPA>(
			0);
	private Set<TareaPlantillaJPA> tareaPlantillas_1 = new HashSet<TareaPlantillaJPA>(
			0);
	private Set<TareaPlantillaJPA> tareaPlantillas_2 = new HashSet<TareaPlantillaJPA>(
			0);
	private Set<ProcesoPlantillaJPA> procesoPlantillas_1 = new HashSet<ProcesoPlantillaJPA>(
			0);
	private Set<UsuarioJPA> usuarios = new HashSet<UsuarioJPA>(0);

	public RolJPA() {
	}

	public RolJPA(long codigoRol, String nombre) {
		this.codigoRol = codigoRol;
		this.nombre = nombre;
	}

	public RolJPA(long codigoRol, String nombre,
			Set<TareaPlantillaJPA> tareaPlantillas, Set<ModuloJPA> modulos,
			Set<ProcesoPlantillaJPA> procesoPlantillas,
			Set<TareaPlantillaJPA> tareaPlantillas_1,
			Set<TareaPlantillaJPA> tareaPlantillas_2,
			Set<ProcesoPlantillaJPA> procesoPlantillas_1, Set<UsuarioJPA> usuarios) {
		this.codigoRol = codigoRol;
		this.nombre = nombre;
		this.tareaPlantillas = tareaPlantillas;
		this.modulos = modulos;
		this.procesoPlantillas = procesoPlantillas;
		this.tareaPlantillas_1 = tareaPlantillas_1;
		this.tareaPlantillas_2 = tareaPlantillas_2;
		this.procesoPlantillas_1 = procesoPlantillas_1;
		this.usuarios = usuarios;
	}

	@Id
	@Column(name = "codigo_rol", unique = true, nullable = false)
	public long getCodigoRol() {
		return this.codigoRol;
	}

	public void setCodigoRol(long codigoRol) {
		this.codigoRol = codigoRol;
	}

	@Column(name = "nombre", nullable = false, length = 120)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "rols")
	public Set<TareaPlantillaJPA> getTareaPlantillas() {
		return this.tareaPlantillas;
	}

	public void setTareaPlantillas(Set<TareaPlantillaJPA> tareaPlantillas) {
		this.tareaPlantillas = tareaPlantillas;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "modulo_rol", schema = "seguridad", joinColumns = { @JoinColumn(name = "codigo_rol", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "codigo_modulo", nullable = false, updatable = false) })
	public Set<ModuloJPA> getModulos() {
		return this.modulos;
	}

	public void setModulos(Set<ModuloJPA> modulos) {
		this.modulos = modulos;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "rols_1")
	public Set<ProcesoPlantillaJPA> getProcesoPlantillas() {
		return this.procesoPlantillas;
	}

	public void setProcesoPlantillas(Set<ProcesoPlantillaJPA> procesoPlantillas) {
		this.procesoPlantillas = procesoPlantillas;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "rols")
	public Set<TareaPlantillaJPA> getTareaPlantillas_1() {
		return this.tareaPlantillas_1;
	}

	public void setTareaPlantillas_1(Set<TareaPlantillaJPA> tareaPlantillas_1) {
		this.tareaPlantillas_1 = tareaPlantillas_1;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "rols")
	public Set<TareaPlantillaJPA> getTareaPlantillas_2() {
		return this.tareaPlantillas_2;
	}

	public void setTareaPlantillas_2(Set<TareaPlantillaJPA> tareaPlantillas_2) {
		this.tareaPlantillas_2 = tareaPlantillas_2;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "rols")
	public Set<ProcesoPlantillaJPA> getProcesoPlantillas_1() {
		return this.procesoPlantillas_1;
	}

	public void setProcesoPlantillas_1(Set<ProcesoPlantillaJPA> procesoPlantillas_1) {
		this.procesoPlantillas_1 = procesoPlantillas_1;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "rols")
	public Set<UsuarioJPA> getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Set<UsuarioJPA> usuarios) {
		this.usuarios = usuarios;
	}

}
