package pe.com.soul.core.dao.jpa;

// Generated 25/09/2015 04:29:28 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TareaPlantilla generated by hbm2java
 */
@Entity
@Table(name = "tarea_plantilla", schema = "proceso")
public class TareaPlantillaJPA implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long codigoTareaPlantilla;
	private String version;
	private ProcesoPlantillaJPA procesoPlantilla;
	private char estado;
	private String nombre;
	private String aleas;
	private int prioridad;
	private Set<RolJPA> rols = new HashSet<RolJPA>(0);
	private Set<RolJPA> rols_1 = new HashSet<RolJPA>(0);
	private Set<RolJPA> rols_2 = new HashSet<RolJPA>(0);
	private Set<TareaJPA> tareas = new HashSet<TareaJPA>(0);

	public TareaPlantillaJPA() {
	}

	public TareaPlantillaJPA(long codigoTareaPlantilla,
			ProcesoPlantillaJPA procesoPlantilla, char estado, String nombre,
			String aleas, int prioridad) {
		this.codigoTareaPlantilla = codigoTareaPlantilla;
		this.procesoPlantilla = procesoPlantilla;
		this.estado = estado;
		this.nombre = nombre;
		this.aleas = aleas;
		this.prioridad = prioridad;
	}

	public TareaPlantillaJPA(long codigoTareaPlantilla,
			ProcesoPlantillaJPA procesoPlantilla, char estado, String nombre,
			String aleas, int prioridad, Set<RolJPA> rols, Set<RolJPA> rols_1,
			Set<RolJPA> rols_2, Set<TareaJPA> tareas) {
		this.codigoTareaPlantilla = codigoTareaPlantilla;
		this.procesoPlantilla = procesoPlantilla;
		this.estado = estado;
		this.nombre = nombre;
		this.aleas = aleas;
		this.prioridad = prioridad;
		this.rols = rols;
		this.rols_1 = rols_1;
		this.rols_2 = rols_2;
		this.tareas = tareas;
	}

	@Id
	@Column(name = "codigo_tarea_plantilla", unique = true, nullable = false)
	public long getCodigoTareaPlantilla() {
		return this.codigoTareaPlantilla;
	}

	public void setCodigoTareaPlantilla(long codigoTareaPlantilla) {
		this.codigoTareaPlantilla = codigoTareaPlantilla;
	}

	@Column(name = "version", nullable = false, length = 12)
	public String getVersion() {
		return this.version;
	}

	public void setVersion(String version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codigo_proceso_plantilla", nullable = false)
	public ProcesoPlantillaJPA getProcesoPlantilla() {
		return this.procesoPlantilla;
	}

	public void setProcesoPlantilla(ProcesoPlantillaJPA procesoPlantilla) {
		this.procesoPlantilla = procesoPlantilla;
	}

	@Column(name = "estado", nullable = false, length = 1)
	public char getEstado() {
		return this.estado;
	}

	public void setEstado(char estado) {
		this.estado = estado;
	}

	@Column(name = "nombre", nullable = false, length = 120)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "aleas", nullable = false, length = 100)
	public String getAleas() {
		return this.aleas;
	}

	public void setAleas(String aleas) {
		this.aleas = aleas;
	}

	@Column(name = "prioridad", nullable = false)
	public int getPrioridad() {
		return this.prioridad;
	}

	public void setPrioridad(int prioridad) {
		this.prioridad = prioridad;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "potencial_dueno", schema = "proceso", joinColumns = { @JoinColumn(name = "codigo_tarea_plantilla", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "codigo_rol", nullable = false, updatable = false) })
	public Set<RolJPA> getRols() {
		return this.rols;
	}

	public void setRols(Set<RolJPA> rols) {
		this.rols = rols;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "editor_tarea", schema = "proceso", joinColumns = { @JoinColumn(name = "codigo_tarea_plantilla", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "codigo_rol", nullable = false, updatable = false) })
	public Set<RolJPA> getRols_1() {
		return this.rols_1;
	}

	public void setRols_1(Set<RolJPA> rols_1) {
		this.rols_1 = rols_1;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "administrador_tarea", schema = "proceso", joinColumns = { @JoinColumn(name = "codigo_tarea_plantilla", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "codigo_rol", nullable = false, updatable = false) })
	public Set<RolJPA> getRols_2() {
		return this.rols_2;
	}

	public void setRols_2(Set<RolJPA> rols_2) {
		this.rols_2 = rols_2;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tareaPlantilla")
	public Set<TareaJPA> getTareas() {
		return this.tareas;
	}

	public void setTareas(Set<TareaJPA> tareas) {
		this.tareas = tareas;
	}

}
