package pe.com.soul.core.dao.jpa;

// Generated 24/09/2015 09:34:46 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TarInstancia generated by hbm2java
 */
@Entity
@Table(name = "tar_instancia", schema = "proceso")
public class TareaJPA extends JpaBase {
	
	private static final long serialVersionUID = 1L;
	
	private long codTarea;
	private ProcesoJPA proInstancia;
	private TareaPlantillaJPA tarPlantilla;
	private char estado;

	public TareaJPA() {
	}

	public TareaJPA(long codTarea, ProcesoJPA proInstancia,
			TareaPlantillaJPA tarPlantilla, char estado) {
		this.codTarea = codTarea;
		this.proInstancia = proInstancia;
		this.tarPlantilla = tarPlantilla;
		this.estado = estado;
	}

	@Id
	@Column(name = "cod_tarea", unique = true, nullable = false)
	public long getCodTarea() {
		return this.codTarea;
	}

	public void setCodTarea(long codTarea) {
		this.codTarea = codTarea;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cod_proceso", nullable = false)
	public ProcesoJPA getProInstancia() {
		return this.proInstancia;
	}

	public void setProInstancia(ProcesoJPA proInstancia) {
		this.proInstancia = proInstancia;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cod_tar_plantilla", nullable = false)
	public TareaPlantillaJPA getTarPlantilla() {
		return this.tarPlantilla;
	}

	public void setTarPlantilla(TareaPlantillaJPA tarPlantilla) {
		this.tarPlantilla = tarPlantilla;
	}

	@Column(name = "estado", nullable = false, length = 1)
	public char getEstado() {
		return this.estado;
	}

	public void setEstado(char estado) {
		this.estado = estado;
	}

}
