
-- Created by Vertabelo (http://vertabelo.com)
-- Last modification date: 2015-09-23 16:35:43.973
CREATE SCHEMA SEGURIDAD AUTHORIZATION postgres;
CREATE SCHEMA PROCESO AUTHORIZATION postgres;


-- Created by Vertabelo (http://vertabelo.com)
-- Last modification date: 2015-09-23 17:42:56.983




-- tables
-- Table: MODULO
CREATE TABLE SEGURIDAD.MODULO (
    COD_MODULO int  NOT NULL,
    NOMBRE varchar(60)  NOT NULL,
    ORDEN int  NOT NULL,
    CONSTRAINT MODULO_pk PRIMARY KEY (COD_MODULO)
);



-- Table: MOD_ROL
CREATE TABLE MOD_ROL (
    COD_ROL bigint  NOT NULL,
    COD_MODULO int  NOT NULL,
    CONSTRAINT MOD_ROL_pk PRIMARY KEY (COD_ROL,COD_MODULO)
);



-- Table: PRO_INSTANCIA
CREATE TABLE PROCESO.PRO_INSTANCIA (
    COD_PROCESO bigint  NOT NULL,
    COD_PRO_PLANTILLA bigint  NOT NULL,
    ESTADO char(1)  NOT NULL,
    CONSTRAINT PRO_INSTANCIA_pk PRIMARY KEY (COD_PROCESO)
);



-- Table: PRO_PLANTILLA
CREATE TABLE PROCESO.PRO_PLANTILLA (
    COD_PRO_PLANTILLA bigint  NOT NULL,
    ESTADO char(1)  NOT NULL,
    NOMBRE varchar(120)  NOT NULL,
    CONSTRAINT PRO_PLANTILLA_pk PRIMARY KEY (COD_PRO_PLANTILLA)
);



-- Table: PRO_PLA_ROL
CREATE TABLE PROCESO.PRO_PLA_ROL (
    COD_PRO_PLANTILLA bigint  NOT NULL,
    COD_ROL bigint  NOT NULL,
    CONSTRAINT PRO_PLA_ROL_pk PRIMARY KEY (COD_PRO_PLANTILLA,COD_ROL)
);



-- Table: ROL
CREATE TABLE SEGURIDAD.ROL (
    COD_ROL bigint  NOT NULL,
    NOMBRE varchar(120)  NOT NULL,
    CONSTRAINT ROL_pk PRIMARY KEY (COD_ROL)
);



-- Table: TAR_INSTANCIA
CREATE TABLE PROCESO.TAR_INSTANCIA (
    COD_TAREA bigint  NOT NULL,
    COD_PROCESO bigint  NOT NULL,
    COD_TAR_PLANTILLA bigint  NOT NULL,
    ESTADO char(1)  NOT NULL,
    CONSTRAINT TAR_INSTANCIA_pk PRIMARY KEY (COD_TAREA)
);



-- Table: TAR_PLANTILLA
CREATE TABLE PROCESO.TAR_PLANTILLA (
    COD_TAR_PLANTILLA bigint  NOT NULL,
    COD_PRO_PLANTILLA bigint  NOT NULL,
    ESTADO char(1)  NOT NULL,
    CONSTRAINT TAR_PLANTILLA_pk PRIMARY KEY (COD_TAR_PLANTILLA)
);



-- Table: TAR_PLA_ROL
CREATE TABLE PROCESO.TAR_PLA_ROL (
    COD_TAR_PLANTILLA bigint  NOT NULL,
    COD_ROL bigint  NOT NULL,
    CONSTRAINT TAR_PLA_ROL_pk PRIMARY KEY (COD_TAR_PLANTILLA,COD_ROL)
);



-- Table: USUARIO
CREATE TABLE SEGURIDAD.USUARIO (
    COD_USUARIO bigint  NOT NULL,
    ESTADO char(1)  NOT NULL,
    USUARIO varchar(40)  NOT NULL,
    CLAVE varchar(20)  NOT NULL,
    NOM_COMPLETO varchar(120)  NOT NULL,
    CORREO varchar(120)  NOT NULL,
    CONSTRAINT USUARIO_pk PRIMARY KEY (COD_USUARIO)
);



-- Table: USU_ROL
CREATE TABLE SEGURIDAD.USU_ROL (
    COD_USUARIO bigint  NOT NULL,
    COD_ROL bigint  NOT NULL,
    CONSTRAINT USU_ROL_pk PRIMARY KEY (COD_USUARIO,COD_ROL)
);







-- foreign keys
-- Reference:  MOD_ROL_MODULO (table: MOD_ROL)


ALTER TABLE MOD_ROL ADD CONSTRAINT MOD_ROL_MODULO 
    FOREIGN KEY (COD_MODULO)
    REFERENCES SEGURIDAD.MODULO (COD_MODULO)
    NOT DEFERRABLE 
    INITIALLY IMMEDIATE 
;

-- Reference:  MOD_ROL_ROL (table: MOD_ROL)


ALTER TABLE MOD_ROL ADD CONSTRAINT MOD_ROL_ROL 
    FOREIGN KEY (COD_ROL)
    REFERENCES SEGURIDAD.ROL (COD_ROL)
    NOT DEFERRABLE 
    INITIALLY IMMEDIATE 
;

-- Reference:  PRO_INSTANCIA_PRO_PLANTILLA (table: PROCESO.PRO_INSTANCIA)


ALTER TABLE PROCESO.PRO_INSTANCIA ADD CONSTRAINT PRO_INSTANCIA_PRO_PLANTILLA 
    FOREIGN KEY (COD_PRO_PLANTILLA)
    REFERENCES PROCESO.PRO_PLANTILLA (COD_PRO_PLANTILLA)
    NOT DEFERRABLE 
    INITIALLY IMMEDIATE 
;

-- Reference:  PRO_PLA_ROL_PRO_PLANTILLA (table: PROCESO.PRO_PLA_ROL)


ALTER TABLE PROCESO.PRO_PLA_ROL ADD CONSTRAINT PRO_PLA_ROL_PRO_PLANTILLA 
    FOREIGN KEY (COD_PRO_PLANTILLA)
    REFERENCES PROCESO.PRO_PLANTILLA (COD_PRO_PLANTILLA)
    NOT DEFERRABLE 
    INITIALLY IMMEDIATE 
;

-- Reference:  PRO_PLA_ROL_ROL (table: PROCESO.PRO_PLA_ROL)


ALTER TABLE PROCESO.PRO_PLA_ROL ADD CONSTRAINT PRO_PLA_ROL_ROL 
    FOREIGN KEY (COD_ROL)
    REFERENCES SEGURIDAD.ROL (COD_ROL)
    NOT DEFERRABLE 
    INITIALLY IMMEDIATE 
;

-- Reference:  TAR_INSTANCIA_PRO_INSTANCIA (table: PROCESO.TAR_INSTANCIA)


ALTER TABLE PROCESO.TAR_INSTANCIA ADD CONSTRAINT TAR_INSTANCIA_PRO_INSTANCIA 
    FOREIGN KEY (COD_PROCESO)
    REFERENCES PROCESO.PRO_INSTANCIA (COD_PROCESO)
    NOT DEFERRABLE 
    INITIALLY IMMEDIATE 
;

-- Reference:  TAR_INSTANCIA_TAR_PLANTILLA (table: PROCESO.TAR_INSTANCIA)


ALTER TABLE PROCESO.TAR_INSTANCIA ADD CONSTRAINT TAR_INSTANCIA_TAR_PLANTILLA 
    FOREIGN KEY (COD_TAR_PLANTILLA)
    REFERENCES PROCESO.TAR_PLANTILLA (COD_TAR_PLANTILLA)
    NOT DEFERRABLE 
    INITIALLY IMMEDIATE 
;

-- Reference:  TAR_PLANTILLA_PRO_PLANTILLA (table: PROCESO.TAR_PLANTILLA)


ALTER TABLE PROCESO.TAR_PLANTILLA ADD CONSTRAINT TAR_PLANTILLA_PRO_PLANTILLA 
    FOREIGN KEY (COD_PRO_PLANTILLA)
    REFERENCES PROCESO.PRO_PLANTILLA (COD_PRO_PLANTILLA)
    NOT DEFERRABLE 
    INITIALLY IMMEDIATE 
;

-- Reference:  TAR_PLA_ROL_ROL (table: PROCESO.TAR_PLA_ROL)


ALTER TABLE PROCESO.TAR_PLA_ROL ADD CONSTRAINT TAR_PLA_ROL_ROL 
    FOREIGN KEY (COD_ROL)
    REFERENCES SEGURIDAD.ROL (COD_ROL)
    NOT DEFERRABLE 
    INITIALLY IMMEDIATE 
;

-- Reference:  TAR_PLA_ROL_TAR_PLANTILLA (table: PROCESO.TAR_PLA_ROL)


ALTER TABLE PROCESO.TAR_PLA_ROL ADD CONSTRAINT TAR_PLA_ROL_TAR_PLANTILLA 
    FOREIGN KEY (COD_TAR_PLANTILLA)
    REFERENCES PROCESO.TAR_PLANTILLA (COD_TAR_PLANTILLA)
    NOT DEFERRABLE 
    INITIALLY IMMEDIATE 
;

-- Reference:  USU_ROL_ROL (table: SEGURIDAD.USU_ROL)


ALTER TABLE SEGURIDAD.USU_ROL ADD CONSTRAINT USU_ROL_ROL 
    FOREIGN KEY (COD_ROL)
    REFERENCES SEGURIDAD.ROL (COD_ROL)
    NOT DEFERRABLE 
    INITIALLY IMMEDIATE 
;

-- Reference:  USU_ROL_USUARIO (table: SEGURIDAD.USU_ROL)


ALTER TABLE SEGURIDAD.USU_ROL ADD CONSTRAINT USU_ROL_USUARIO 
    FOREIGN KEY (COD_USUARIO)
    REFERENCES SEGURIDAD.USUARIO (COD_USUARIO)
    NOT DEFERRABLE 
    INITIALLY IMMEDIATE 
;






-- End of file.
