
CREATE SCHEMA soul;

CREATE TABLE soul.ATRIBUTO (

		COD_ATRIBUTO INTEGER NOT NULL,

		COD_CLASE INTEGER NOT NULL,

		NOMBRE VARCHAR(120) NOT NULL,

		TIPO VARCHAR(255) NOT NULL,

		FLG_LISTA CHAR(1) NOT NULL DEFAULT '0',

		WEB_NOMBRE VARCHAR(120),

		WEB_FORMATO VARCHAR(120),

		INF_NOMBRE VARCHAR(120),

		INF_DESCRIPCION VARCHAR(255),

		INF_AUTOR VARCHAR(120),

		WEB_MEN_VALIDACION VARCHAR(250),

		WEB_FOR_VALIDACION VARCHAR(250)

	)

	;

CREATE TABLE soul.ATRIBUTO_SQL (

		COD_TABLA INTEGER NOT NULL,

		COD_ATRIBUTO INTEGER NOT NULL,

		CAMPO VARCHAR(50) NOT NULL,

		TIPO VARCHAR(50) NOT NULL,

		LONGITUD INTEGER,

		PRECISION INTEGER,

		PK CHAR(1) NOT NULL DEFAULT '0',

		OBLIGATORIO CHAR(1) NOT NULL DEFAULT '0',

		FK_TABLA INTEGER,

		FK_UNO_MUCHO CHAR(1),

		FN_BUS_NOMBRE VARCHAR(120),

		FN_BUS_CATALOGO VARCHAR(50),

		VAL_DEFECTO VARCHAR(120),

		FK_CAMPO INTEGER

	)

	;

CREATE TABLE soul.CATALOGO (

		COD_CATALOGO VARCHAR(50) NOT NULL,

		COD_ATRIBUTO VARCHAR(50) NOT NULL,

		VALOR_1 VARCHAR(100),

		VALOR_2 VARCHAR(100),

		DESCRIPCION VARCHAR(100),

		LIM_COD_ATRIBUTO INTEGER,

		LIM_VALOR_1 INTEGER,

		LIM_VALOR_2 INTEGER,

		CABECERA CHAR(1) NOT NULL,

		COD_PROYECTO INTEGER NOT NULL DEFAULT 0

	)

	;

CREATE TABLE soul.CLASE (

		COD_CLASE INTEGER NOT NULL,

		NOMBRE VARCHAR(120) NOT NULL,

		PAQUETE VARCHAR(250) NOT NULL,

		COD_PROYECTO INTEGER NOT NULL,

		INF_AUTOR VARCHAR(120),

		INF_DESCRIPCION VARCHAR(255),

		NIVEL INTEGER

	)

	;

CREATE TABLE soul.CONFIGURACION (

		COD_PROYECTO INTEGER NOT NULL,

		USUARIO VARCHAR(20) NOT NULL,

		RUTA_WORKSPACE VARCHAR(255) NOT NULL,

		RUTA_SCRIPT_SQL VARCHAR(255) NOT NULL

	)

	;

CREATE TABLE soul.CONSULTA (

		COD_CONSULTA INTEGER NOT NULL,

		SQL_ALE_STO_PROCEDURE VARCHAR(120) NOT NULL,

		JAV_PAQUETE VARCHAR(255) NOT NULL,

		JAV_INTERFACE VARCHAR(255) NOT NULL,

		COD_PROYECTO INTEGER NOT NULL,

		NOMBRE VARCHAR(120) NOT NULL DEFAULT ''

	)

	;

CREATE TABLE soul.CONSULTA_ATRIBUTO (

		COD_CONSULTA INTEGER NOT NULL,

		COD_ATRIBUTO INTEGER NOT NULL,

		FLG_CONDICION CHAR(1) NOT NULL DEFAULT '0',

		FLG_VISIBLE CHAR(1) NOT NULL DEFAULT '1',

		COD_TABLA INTEGER NOT NULL DEFAULT 0

	)

	;

CREATE TABLE soul.CONSULTA_TABLA (

		COD_CONSULTA INTEGER NOT NULL,

		COD_TABLA INTEGER NOT NULL,

		FK CHAR(1) NOT NULL DEFAULT '0',

		FLG_UNO_MUCHOS CHAR(1) NOT NULL DEFAULT '0',

		COD_TAB_PADRE INTEGER

	)

	;

CREATE TABLE soul.DATASOURCE (

		COD_PROYECTO INTEGER NOT NULL,

		COD_DATASOURCE VARCHAR(100) NOT NULL,

		DESCRIPCION VARCHAR(255) NOT NULL,

		ESTADO CHAR(1)

	)

	;

CREATE TABLE soul.EQUIPO (

		COD_PROYECTO INTEGER NOT NULL,

		COD_USUARIO VARCHAR(50) NOT NULL,

		ES_RESPONSABLE CHAR(1) NOT NULL,

		CARPETA_DESTINO_WORKSPACE VARCHAR(255) NOT NULL DEFAULT '',

		CARPETA_DESTINO_PARCIAL VARCHAR(250) NOT NULL DEFAULT ''

	)

	;

CREATE TABLE soul.ESQUEMA (

		COD_PROYECTO INTEGER NOT NULL,

		COD_ESQUEMA VARCHAR(100) NOT NULL,

		DESCRIPCION VARCHAR(255) NOT NULL,

		ESTADO CHAR(1)

	)

	;

CREATE TABLE soul.MANTENIMIENTO (

		COD_PROYECTO INTEGER NOT NULL,

		COD_MANTENIMIENTO VARCHAR(80) NOT NULL,

		NOMBRE VARCHAR(100) NOT NULL,

		DESCRIPCION VARCHAR(255),

		COD_ESQUEMA VARCHAR(100) NOT NULL,

		COD_DATASOURCE VARCHAR(100) NOT NULL

	)

	;

CREATE TABLE soul.MANTENIMIENTO_ATRIBUTO (

		COD_PROYECTO INTEGER NOT NULL,

		COD_MANTENIMIENTO VARCHAR(80) NOT NULL,

		COD_ATRIBUTO INTEGER NOT NULL,

		NOMBRE VARCHAR(50) NOT NULL,

		TIPO_DATO VARCHAR(50) NOT NULL,

		LONGITUD INTEGER,

		PRECISION INTEGER,

		ES_LLAVE_PRIMARIA CHAR(1),

		ES_LISTADO CHAR(1),

		ES_BUSQUEDA CHAR(1),

		ES_OBLIGATORIO CHAR(1),

		DESCRIPCION VARCHAR(255)

	)

	;

CREATE TABLE soul.MANTENIMIENTO_ROL (

		COD_PROYECTO INTEGER NOT NULL,

		COD_MANTENIMIENTO VARCHAR(80) NOT NULL,

		COD_ROL VARCHAR(100) NOT NULL

	)

	;

CREATE TABLE soul.PROCESO (

		COD_PROCESO INTEGER NOT NULL,

		COD_PROYECTO INTEGER NOT NULL,

		INF_NOMBRE VARCHAR(120) NOT NULL,

		COD_UNI_NEGOCIO VARCHAR(12) NOT NULL,

		COD_PRODUCTO VARCHAR(12) NOT NULL,

		INF_SUFIJO VARCHAR(6),

		BPM_PLANTILLA VARCHAR(120) NOT NULL,

		BPM_ACT_INICIO INTEGER NOT NULL,

		JAV_PAQUETE VARCHAR(255) NOT NULL,

		JAV_CLASE VARCHAR(120) NOT NULL,

		JAV_ALE_PROCESO VARCHAR(120),

		JAV_DATASOURCE VARCHAR(120) NOT NULL,

		COD_CON_RESUMEN INTEGER NOT NULL,

		COD_CON_DETALLE INTEGER NOT NULL,

		JAV_DOC_SEQUENCE VARCHAR(120)

	)

	;

CREATE TABLE soul.PROCESO_INICIO (

		COD_PROCESO INTEGER NOT NULL,

		COD_ATRIBUTO INTEGER NOT NULL,

		BPM_FLG_ENTRADA CHAR(1) NOT NULL DEFAULT '0',

		BPM_OBJ_REFERENCIA VARCHAR(60),

		BPM_FLG_PIID CHAR(1) NOT NULL DEFAULT '0',

		WEB_FLG_REFERENCIA CHAR(1) NOT NULL DEFAULT '0',

		WEB_FLG_VALIDACION CHAR(1) NOT NULL DEFAULT '0',

		WEB_MEN_VALIDACION VARCHAR(255),

		WEB_VAL_OMISION VARCHAR(255),

		WEB_REQUERIDO CHAR(1) NOT NULL DEFAULT '0',

		WEB_NOM_CAT_COMBO VARCHAR(255),

		SQL_FLG_AUTOGENERADO CHAR(1) NOT NULL DEFAULT '0',

		SQL_NOM_SECUENCIAL VARCHAR(255),

		COD_PROYECTO INTEGER NOT NULL

	)

	;

CREATE TABLE soul.PROYECTO (

		COD_PROYECTO INTEGER NOT NULL,

		NOMBRE VARCHAR(120) NOT NULL,

		JAV_PRO_LIBRERIA VARCHAR(255) NOT NULL,

		JAV_PRO_EJB VARCHAR(255) NOT NULL,

		JAV_PRO_CLI_EJB VARCHAR(255) NOT NULL,

		JAV_PRO_WEB VARCHAR(255) NOT NULL,

		JAV_PAQUETE VARCHAR(255) NOT NULL,

		JAV_PAQ_CONTROLADOR VARCHAR(255) NOT NULL,

		JAV_PRE_CONTROLADOR VARCHAR(50) NOT NULL,

		JAV_PRO_EJB_EXT VARCHAR(255)

	)

	;

CREATE TABLE soul.ROL (

		COD_PROYECTO INTEGER NOT NULL,

		COD_ROL VARCHAR(100) NOT NULL,

		DESCRIPCION VARCHAR(255) NOT NULL,

		ESTADO CHAR(1)

	)

	;

CREATE TABLE soul.TABLA (

		COD_TABLA INTEGER NOT NULL,

		ESQUEMA VARCHAR(50) NOT NULL,

		NOMBRE VARCHAR(50) NOT NULL,

		COD_PROYECTO INTEGER NOT NULL,

		ORDEN INTEGER

	)

	;

CREATE TABLE soul.TAREA (

		COD_TAREA INTEGER NOT NULL,

		COD_PROCESO INTEGER NOT NULL,

		COD_PROYECTO INTEGER NOT NULL,

		NOMBRE VARCHAR(120) NOT NULL,

		VERSION VARCHAR(10) NOT NULL,

		COD_CON_TRABAJAR INTEGER NOT NULL,

		COD_CON_COMPLETAR INTEGER NOT NULL,

		SQL_ALEAS VARCHAR(20) NOT NULL,

		SQL_DATASOURCE VARCHAR(120) NOT NULL,

		BPM_NOMBRE VARCHAR(255) NOT NULL,

		JAV_PAQUETE VARCHAR(255) NOT NULL,

		JAV_CLASE VARCHAR(255) NOT NULL,

		WEB_ACC_COMPLETAR CHAR(1) NOT NULL DEFAULT '1',

		WEB_ACC_GRABAR CHAR(1) NOT NULL DEFAULT '1',

		WEB_ACC_CANCELAR CHAR(1) NOT NULL DEFAULT '0',

		WEB_ACC_RECHAZAR CHAR(1) NOT NULL DEFAULT '0',

		WEB_ACC_OBSERVAR CHAR(1) NOT NULL DEFAULT '0',

		WEB_ACC_SALIR CHAR(1) NOT NULL DEFAULT '1',

		WEB_ACC_SUBSANAR CHAR(1) NOT NULL DEFAULT '0',

		WEB_PAR_HIS_COMENTARIO VARCHAR(120) NOT NULL,

		WEB_PAR_HIS_ACCION VARCHAR(120) NOT NULL,

		WEB_TIE_ROJO INTEGER NOT NULL,

		WEB_TIE_AMARILLO INTEGER NOT NULL,

		WEB_FLG_ARC_ADJUNTOS CHAR(1) NOT NULL DEFAULT '0',

		WEB_FLG_ARC_ADICIONALES CHAR(1) NOT NULL DEFAULT '0',

		WEB_NOM_CONFIGURACION VARCHAR(120),

		TIPO_VISTA CHAR(1)

	)

	;

CREATE TABLE soul.TAREA_ATRIBUTO (

		TAREA_SECCION_ID VARCHAR(20) NOT NULL,

		TAREA_SUB_SECCION_ID INTEGER NOT NULL,

		TAREA_ATRIBUTO_ID INTEGER NOT NULL,

		COD_CLASE INTEGER NOT NULL,

		COD_ATRIBUTO INTEGER NOT NULL,

		NOMBRE VARCHAR(120) NOT NULL,

		ACTIVO CHAR(1) NOT NULL,

		EDITOR_TIPO_CAMPO CHAR(1),

		EDITOR_OBLIGATORIO CHAR(1)

	)

	;

CREATE TABLE soul.TAREA_ATR_CANCELAR (

		COD_PROCESO INTEGER NOT NULL,

		COD_PROYECTO INTEGER NOT NULL,

		COD_TAREA INTEGER NOT NULL,

		COD_ATRIBUTO INTEGER NOT NULL,

		JAV_VAL_OMISION VARCHAR(250),

		WEB_FLG_VALIDACION CHAR(1)

	)

	;

CREATE TABLE soul.TAREA_ATR_COMPLETAR (

		COD_PROCESO INTEGER NOT NULL,

		COD_PROYECTO INTEGER NOT NULL,

		COD_TAREA INTEGER NOT NULL,

		COD_ATRIBUTO INTEGER NOT NULL,

		JAV_VAL_OMISION VARCHAR(250),

		WEB_FLG_VALIDACION CHAR(1) NOT NULL DEFAULT '0',

		WEB_TAB_CAMPO INTEGER,

		WEB_ORD_VALIDACION INTEGER

	)

	;

CREATE TABLE soul.TAREA_ATR_OBSERVAR (

		COD_PROCESO INTEGER NOT NULL,

		COD_PROYECTO INTEGER NOT NULL,

		COD_TAREA INTEGER NOT NULL,

		COD_ATRIBUTO INTEGER NOT NULL,

		JAV_VAL_OMISION VARCHAR(250),

		WEB_FLG_VALIDACION CHAR(1)

	)

	;

CREATE TABLE soul.TAREA_ATR_RECHAZAR (

		COD_PROCESO INTEGER NOT NULL,

		COD_PROYECTO INTEGER NOT NULL,

		COD_TAREA INTEGER NOT NULL,

		COD_ATRIBUTO INTEGER NOT NULL,

		JAV_VAL_OMISION VARCHAR(250),

		WEB_FLG_VALIDACION CHAR(1)

	)

	;

CREATE TABLE soul.USUARIO (

		COD_USUARIO VARCHAR(50) NOT NULL,

		CLAVE VARCHAR(100) NOT NULL,

		NOMBRE VARCHAR(100) NOT NULL,

		PERFIL VARCHAR(50) NOT NULL,

		DESCRIPCION VARCHAR(250)

	)

	;

ALTER TABLE soul.ATRIBUTO ADD CONSTRAINT OBJETO_PK PRIMARY KEY

	(COD_ATRIBUTO);

ALTER TABLE soul.ATRIBUTO_SQL ADD CONSTRAINT OBJ_SQL_PK PRIMARY KEY

	(COD_TABLA,

	 COD_ATRIBUTO);

ALTER TABLE soul.CATALOGO ADD CONSTRAINT CATALOGO_PK PRIMARY KEY

	(COD_CATALOGO,

	 COD_ATRIBUTO,

	 COD_PROYECTO);

ALTER TABLE soul.CLASE ADD CONSTRAINT CLASE_PK PRIMARY KEY

	(COD_CLASE);

ALTER TABLE soul.CONFIGURACION ADD CONSTRAINT CONFIGURACION_PK PRIMARY KEY

	(COD_PROYECTO,

	 USUARIO);

ALTER TABLE soul.CONSULTA ADD CONSTRAINT CONSULTA_PK PRIMARY KEY

	(COD_CONSULTA);

ALTER TABLE soul.CONSULTA_ATRIBUTO ADD CONSTRAINT CON_ATRIBUTO_PK PRIMARY KEY

	(COD_CONSULTA,

	 COD_ATRIBUTO);

ALTER TABLE soul.CONSULTA_TABLA ADD CONSTRAINT CON_TABLA_PK PRIMARY KEY

	(COD_CONSULTA,

	 COD_TABLA);

ALTER TABLE soul.DATASOURCE ADD CONSTRAINT SQL150708145914480 PRIMARY KEY

	(COD_PROYECTO,

	 COD_DATASOURCE);

ALTER TABLE soul.EQUIPO ADD CONSTRAINT SQL150708144027730 PRIMARY KEY

	(COD_PROYECTO,

	 COD_USUARIO);

ALTER TABLE soul.ESQUEMA ADD CONSTRAINT SQL150708145914380 PRIMARY KEY

	(COD_PROYECTO,

	 COD_ESQUEMA);

ALTER TABLE soul.MANTENIMIENTO ADD CONSTRAINT SQL150717091917330 PRIMARY KEY

	(COD_PROYECTO,

	 COD_MANTENIMIENTO);

ALTER TABLE soul.MANTENIMIENTO_ATRIBUTO ADD CONSTRAINT SQL150721084249850 PRIMARY KEY

	(COD_PROYECTO,

	 COD_MANTENIMIENTO,

	 COD_ATRIBUTO);

ALTER TABLE soul.MANTENIMIENTO_ROL ADD CONSTRAINT SQL150721084032400 PRIMARY KEY

	(COD_PROYECTO,

	 COD_MANTENIMIENTO,

	 COD_ROL);


ALTER TABLE soul.PROCESO ADD CONSTRAINT PROCESO_PK PRIMARY KEY

	(COD_PROCESO,

	 COD_PROYECTO);

ALTER TABLE soul.PROCESO_INICIO ADD CONSTRAINT PRO_INI_ATRIBUTO_PK PRIMARY KEY

	(COD_PROCESO,

	 COD_ATRIBUTO,

	 COD_PROYECTO);

ALTER TABLE soul.PROYECTO ADD CONSTRAINT PROYECTO_PK PRIMARY KEY

	(COD_PROYECTO);

ALTER TABLE soul.ROL ADD CONSTRAINT SQL150708145914240 PRIMARY KEY

	(COD_PROYECTO,

	 COD_ROL);

ALTER TABLE soul.TABLA ADD CONSTRAINT TABLA_PK PRIMARY KEY

	(COD_TABLA);

ALTER TABLE soul.TAREA ADD CONSTRAINT TAREA_PK PRIMARY KEY

	(COD_PROCESO,

	 COD_PROYECTO,

	 COD_TAREA);

ALTER TABLE soul.TAREA_ATR_CANCELAR ADD CONSTRAINT TAREA_ATR_CANCELAR_PK PRIMARY KEY

	(COD_PROCESO,

	 COD_PROYECTO,

	 COD_TAREA,

	 COD_ATRIBUTO);

ALTER TABLE soul.TAREA_ATR_COMPLETAR ADD CONSTRAINT TAR_ATR_COMPLETAR_PK PRIMARY KEY

	(COD_PROCESO,

	 COD_PROYECTO,

	 COD_TAREA,

	 COD_ATRIBUTO);

ALTER TABLE soul.TAREA_ATR_OBSERVAR ADD CONSTRAINT TAREA_ATR_OBSERVAR_PK PRIMARY KEY

	(COD_PROCESO,

	 COD_PROYECTO,

	 COD_TAREA,

	 COD_ATRIBUTO);

ALTER TABLE soul.TAREA_ATR_RECHAZAR ADD CONSTRAINT TAREA_ATR_RECHAZAR_PK PRIMARY KEY

	(COD_PROCESO,

	 COD_PROYECTO,

	 COD_TAREA,

	 COD_ATRIBUTO);



ALTER TABLE soul.USUARIO ADD CONSTRAINT PK_COD_USUARIO PRIMARY KEY

	(COD_USUARIO);

	
ALTER TABLE soul.ATRIBUTO ADD CONSTRAINT OBJETO_CLASE_FK FOREIGN KEY

	(COD_CLASE)

	REFERENCES soul.CLASE

	(COD_CLASE)

	ON DELETE RESTRICT;


ALTER TABLE soul.ATRIBUTO_SQL ADD CONSTRAINT OBJ_ATR_SQL_TABLA_FK FOREIGN KEY

	(COD_TABLA)

	REFERENCES soul.TABLA

	(COD_TABLA)

	ON DELETE RESTRICT;

ALTER TABLE soul.ATRIBUTO_SQL ADD CONSTRAINT OBJ_SQL_OBJETO_FK FOREIGN KEY

	(COD_ATRIBUTO)

	REFERENCES soul.ATRIBUTO

	(COD_ATRIBUTO)

	ON DELETE RESTRICT;

ALTER TABLE soul.CLASE ADD CONSTRAINT CLASE_PROYECTO_FK FOREIGN KEY

	(COD_PROYECTO)

	REFERENCES soul.PROYECTO

	(COD_PROYECTO)

	ON DELETE RESTRICT;

ALTER TABLE soul.CONFIGURACION ADD CONSTRAINT CONFIGURACION_PROYECTO_FK FOREIGN KEY

	(COD_PROYECTO)

	REFERENCES soul.PROYECTO

	(COD_PROYECTO)

	ON DELETE CASCADE;

ALTER TABLE soul.CONSULTA ADD CONSTRAINT CONSULTA_PROYECTO_FK FOREIGN KEY

	(COD_PROYECTO)

	REFERENCES soul.PROYECTO

	(COD_PROYECTO)

	ON DELETE RESTRICT;

ALTER TABLE soul.CONSULTA_ATRIBUTO ADD CONSTRAINT CON_ATRIBUTO_ATRIBUTO_FK FOREIGN KEY

	(COD_ATRIBUTO)

	REFERENCES soul.ATRIBUTO

	(COD_ATRIBUTO)

	ON DELETE CASCADE;

ALTER TABLE soul.CONSULTA_ATRIBUTO ADD CONSTRAINT CON_ATRIBUTO_CONSULTA_FK FOREIGN KEY

	(COD_CONSULTA)

	REFERENCES soul.CONSULTA

	(COD_CONSULTA)

	ON DELETE CASCADE;

ALTER TABLE soul.CONSULTA_TABLA ADD CONSTRAINT CON_TABLA_CONSULTA_FK FOREIGN KEY

	(COD_CONSULTA)

	REFERENCES soul.CONSULTA

	(COD_CONSULTA)

	ON DELETE CASCADE;

ALTER TABLE soul.CONSULTA_TABLA ADD CONSTRAINT CON_TABLA_TABLA_FK FOREIGN KEY

	(COD_TABLA)

	REFERENCES soul.TABLA

	(COD_TABLA)

	ON DELETE CASCADE;

ALTER TABLE soul.CONSULTA_TABLA ADD CONSTRAINT CON_TABLA_TABLA_FK1 FOREIGN KEY

	(COD_TAB_PADRE)

	REFERENCES soul.TABLA

	(COD_TABLA)

	ON DELETE RESTRICT;

ALTER TABLE soul.PROCESO ADD CONSTRAINT PROCESO_CONSULTA_FK FOREIGN KEY

	(COD_CON_RESUMEN)

	REFERENCES soul.CONSULTA

	(COD_CONSULTA)

	ON DELETE RESTRICT;

ALTER TABLE soul.PROCESO ADD CONSTRAINT PROCESO_CONSULTA_FK1 FOREIGN KEY

	(COD_CON_DETALLE)

	REFERENCES soul.CONSULTA

	(COD_CONSULTA)

	ON DELETE RESTRICT;


ALTER TABLE soul.PROCESO ADD CONSTRAINT PROCESO_PROYECTO_FK FOREIGN KEY

	(COD_PROYECTO)

	REFERENCES soul.PROYECTO

	(COD_PROYECTO)

	ON DELETE RESTRICT;

ALTER TABLE soul.PROCESO_INICIO ADD CONSTRAINT PRO_INI_ATRIBUTO_ATRIBUTO_FK FOREIGN KEY

	(COD_ATRIBUTO)

	REFERENCES soul.ATRIBUTO

	(COD_ATRIBUTO)

	ON DELETE CASCADE;

ALTER TABLE soul.PROCESO_INICIO ADD CONSTRAINT PRO_INI_ATRIBUTO_PROCESO_FK FOREIGN KEY

	(COD_PROCESO,

	 COD_PROYECTO)

	REFERENCES soul.PROCESO

	(COD_PROCESO,

	 COD_PROYECTO)

	ON DELETE CASCADE;

ALTER TABLE soul.TABLA ADD CONSTRAINT TABLA_PROYECTO_FK FOREIGN KEY

	(COD_PROYECTO)

	REFERENCES soul.PROYECTO

	(COD_PROYECTO)

	ON DELETE RESTRICT;

ALTER TABLE soul.TAREA ADD CONSTRAINT TAREA_CONSULTA_FK FOREIGN KEY

	(COD_CON_TRABAJAR)

	REFERENCES soul.CONSULTA

	(COD_CONSULTA)

	ON DELETE RESTRICT;

ALTER TABLE soul.TAREA ADD CONSTRAINT TAREA_CONSULTA_FK1 FOREIGN KEY

	(COD_CON_COMPLETAR)

	REFERENCES soul.CONSULTA

	(COD_CONSULTA)

	ON DELETE RESTRICT;

ALTER TABLE soul.TAREA ADD CONSTRAINT TAREA_PROCESO_FK FOREIGN KEY

	(COD_PROCESO,

	 COD_PROYECTO)

	REFERENCES soul.PROCESO

	(COD_PROCESO,

	 COD_PROYECTO)

	ON DELETE CASCADE;

ALTER TABLE soul.TAREA_ATR_CANCELAR ADD CONSTRAINT TAR_ATR_CANCELAR_ATRIBUTO_FK FOREIGN KEY

	(COD_ATRIBUTO)

	REFERENCES soul.ATRIBUTO

	(COD_ATRIBUTO)

	ON DELETE CASCADE;

ALTER TABLE soul.TAREA_ATR_CANCELAR ADD CONSTRAINT TAR_ATR_CANCELAR_TAREA_FK FOREIGN KEY

	(COD_PROCESO,

	 COD_PROYECTO,

	 COD_TAREA)

	REFERENCES soul.TAREA

	(COD_PROCESO,

	 COD_PROYECTO,

	 COD_TAREA)

	ON DELETE CASCADE;

ALTER TABLE soul.TAREA_ATR_COMPLETAR ADD CONSTRAINT TAR_ATR_COMPLETAR_ATRIBUTO_FK FOREIGN KEY

	(COD_ATRIBUTO)

	REFERENCES soul.ATRIBUTO

	(COD_ATRIBUTO)

	ON DELETE CASCADE;

ALTER TABLE soul.TAREA_ATR_COMPLETAR ADD CONSTRAINT TAR_ATR_COMPLETAR_TAREA_FK FOREIGN KEY

	(COD_PROCESO,

	 COD_PROYECTO,

	 COD_TAREA)

	REFERENCES soul.TAREA

	(COD_PROCESO,

	 COD_PROYECTO,

	 COD_TAREA)

	ON DELETE CASCADE;

ALTER TABLE soul.TAREA_ATR_OBSERVAR ADD CONSTRAINT TAREA_ATR_OBSERVAR_ATRIBUTO_FK FOREIGN KEY

	(COD_ATRIBUTO)

	REFERENCES soul.ATRIBUTO

	(COD_ATRIBUTO)

	ON DELETE CASCADE;

ALTER TABLE soul.TAREA_ATR_OBSERVAR ADD CONSTRAINT TAREA_ATR_OBSERVAR_TAREA_FK FOREIGN KEY

	(COD_PROCESO,

	 COD_PROYECTO,

	 COD_TAREA)

	REFERENCES soul.TAREA

	(COD_PROCESO,

	 COD_PROYECTO,

	 COD_TAREA)

	ON DELETE CASCADE;

ALTER TABLE soul.TAREA_ATR_RECHAZAR ADD CONSTRAINT TAR_ATR_RECHAZAR_ATRIBUTO_FK FOREIGN KEY

	(COD_ATRIBUTO)

	REFERENCES soul.ATRIBUTO

	(COD_ATRIBUTO)

	ON DELETE CASCADE;

ALTER TABLE soul.TAREA_ATR_RECHAZAR ADD CONSTRAINT TAR_ATR_RECHAZAR_TAREA_FK FOREIGN KEY

	(COD_PROCESO,

	 COD_PROYECTO,

	 COD_TAREA)

	REFERENCES soul.TAREA

	(COD_PROCESO,

	 COD_PROYECTO,

	 COD_TAREA)

	ON DELETE CASCADE;

CREATE VIEW soul.PROCESO_INICIO_ATRIBUTO_CLASE (COD_PROYECTO, COD_PROCESO, COD_ATRIBUTO, NOM_ATRIBUTO, COD_CLASE, NOM_CLASE, BPM_FLG_ENTRADA, BPM_OBJ_REFERENCIA, BPM_FLG_PIID, WEB_FLG_REFERENCIA, WEB_FLG_VALIDACION, WEB_MEN_VALIDACION, WEB_VAL_OMISION, WEB_REQUERIDO, WEB_NOM_CAT_COMBO, SQL_FLG_AUTOGENERADO, SQL_NOM_SECUENCIAL) AS

SELECT VISTA.COD_PROYECTO AS COD_PROYECTO,

	       VISTA.COD_PROCESO AS COD_PROCESO,

		   VISTA.COD_ATRIBUTO AS COD_ATRIBUTO,

		   VISTA.NOM_ATRIBUTO AS NOM_ATRIBUTO,

		   VISTA.COD_CLASE AS COD_CLASE,

		   VISTA.NOM_CLASE AS NOM_CLASE,

		   VISTA.BPM_FLG_ENTRADA AS BPM_FLG_ENTRADA,

		   VISTA.BPM_OBJ_REFERENCIA AS BPM_OBJ_REFERENCIA,

		   VISTA.BPM_FLG_PIID AS BPM_FLG_PIID,

		   VISTA.WEB_FLG_REFERENCIA AS WEB_FLG_REFERENCIA,

		   VISTA.WEB_FLG_VALIDACION AS WEB_FLG_VALIDACION,

		   VISTA.WEB_MEN_VALIDACION AS WEB_MEN_VALIDACION,

		   VISTA.WEB_VAL_OMISION AS WEB_VAL_OMISION,

		   VISTA.WEB_REQUERIDO AS WEB_REQUERIDO,

		   VISTA.WEB_NOM_CAT_COMBO AS WEB_NOM_CAT_COMBO,

		   VISTA.SQL_FLG_AUTOGENERADO AS SQL_FLG_AUTOGENERADO,

		   VISTA.SQL_NOM_SECUENCIAL AS SQL_NOM_SECUENCIAL	

  FROM (SELECT PI.COD_PROYECTO AS COD_PROYECTO,

       PI.COD_PROCESO AS COD_PROCESO,

	   ATR.COD_ATRIBUTO AS COD_ATRIBUTO,

	   ATR.NOMBRE AS NOM_ATRIBUTO,

	   ATR.COD_CLASE AS COD_CLASE,

	   CLA.NOMBRE AS NOM_CLASE,

	   PI.BPM_FLG_ENTRADA AS BPM_FLG_ENTRADA,

	   PI.BPM_OBJ_REFERENCIA AS BPM_OBJ_REFERENCIA,

	   PI.BPM_FLG_PIID AS BPM_FLG_PIID,

	   PI.WEB_FLG_REFERENCIA AS WEB_FLG_REFERENCIA,

	   PI.WEB_FLG_VALIDACION AS WEB_FLG_VALIDACION,

	   PI.WEB_MEN_VALIDACION AS WEB_MEN_VALIDACION,

	   PI.WEB_VAL_OMISION AS WEB_VAL_OMISION,

	   PI.WEB_REQUERIDO AS WEB_REQUERIDO,

	   PI.WEB_NOM_CAT_COMBO AS WEB_NOM_CAT_COMBO,

	   PI.SQL_FLG_AUTOGENERADO AS SQL_FLG_AUTOGENERADO,

	   PI.SQL_NOM_SECUENCIAL AS SQL_NOM_SECUENCIAL	

  FROM soul.PROCESO_INICIO PI, 

       soul.ATRIBUTO ATR,

       soul.CLASE CLA

 WHERE PI.COD_ATRIBUTO = ATR.COD_ATRIBUTO

   AND ATR.COD_CLASE = CLA.COD_CLASE

   ORDER BY ATR.COD_CLASE, ATR.COD_ATRIBUTO ASC) AS VISTA;

