
INSERT INTO SEGURIDAD.USUARIO VALUES (1, '1', 'daniel', 'clave1', 'daniel bravo', 'daniel@correo.com');
INSERT INTO SEGURIDAD.USUARIO VALUES (2, '1', 'edwin', 'clave1', 'edwin rebaza', 'edwin@correo.com');
INSERT INTO SEGURIDAD.USUARIO VALUES (3, '1', 'david', 'clave1', 'david huertas', 'david@correo.com');
INSERT INTO SEGURIDAD.USUARIO VALUES (4, '1', 'manuel', 'clave1', 'manuel flores', 'manuel@correo.com');

INSERT INTO SEGURIDAD.ROL VALUES (1, 'Administrador');
INSERT INTO SEGURIDAD.ROL VALUES (2, 'Analista');
INSERT INTO SEGURIDAD.ROL VALUES (3, 'Operador');
INSERT INTO SEGURIDAD.ROL VALUES (4, 'Asistente');

INSERT INTO SEGURIDAD.USU_ROL VALUES (1, 1);
INSERT INTO SEGURIDAD.USU_ROL VALUES (2, 2);
INSERT INTO SEGURIDAD.USU_ROL VALUES (3, 3);
INSERT INTO SEGURIDAD.USU_ROL VALUES (4, 4);

SELECT * FROM SEGURIDAD.USUARIO;
SELECT * FROM SEGURIDAD.ROL;
SELECT * FROM SEGURIDAD.USU_ROL;