package pe.com.captiva.dao.entity;

// Generated 21/10/2015 10:31:13 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AtributoSqlId generated by hbm2java
 */
@Embeddable
public class AtributoSqlId implements java.io.Serializable {

	private int codTabla;
	private int codAtributo;

	public AtributoSqlId() {
	}

	public AtributoSqlId(int codTabla, int codAtributo) {
		this.codTabla = codTabla;
		this.codAtributo = codAtributo;
	}

	@Column(name = "cod_tabla", nullable = false)
	public int getCodTabla() {
		return this.codTabla;
	}

	public void setCodTabla(int codTabla) {
		this.codTabla = codTabla;
	}

	@Column(name = "cod_atributo", nullable = false)
	public int getCodAtributo() {
		return this.codAtributo;
	}

	public void setCodAtributo(int codAtributo) {
		this.codAtributo = codAtributo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AtributoSqlId))
			return false;
		AtributoSqlId castOther = (AtributoSqlId) other;

		return (this.getCodTabla() == castOther.getCodTabla())
				&& (this.getCodAtributo() == castOther.getCodAtributo());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCodTabla();
		result = 37 * result + this.getCodAtributo();
		return result;
	}

}
