package pe.com.captiva.dao.entity;

// Generated 12/11/2015 12:28:21 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;

/**
 * AtributoSql generated by hbm2java
 */
@Entity
@Table(name = "atributo_sql", schema = "soul")
public class AtributoSql implements java.io.Serializable {

	private int codAtributo;
	private Atributo atributo;
	private Tabla tabla;
	private String campo;
	private String tipo;
	private Integer longitud;
	private Integer precision;
	private char pk;
	private char obligatorio;
	private Integer fkTabla;
	private Character fkUnoMucho;
	private String fnBusNombre;
	private String fnBusCatalogo;
	private String valDefecto;
	private Integer fkCampo;
	private String sequencial;

	public AtributoSql() {
	}

	public AtributoSql(Atributo atributo, Tabla tabla, String campo,
			String tipo, char pk, char obligatorio) {
		this.atributo = atributo;
		this.tabla = tabla;
		this.campo = campo;
		this.tipo = tipo;
		this.pk = pk;
		this.obligatorio = obligatorio;
	}

	public AtributoSql(Atributo atributo, Tabla tabla, String campo,
			String tipo, Integer longitud, Integer precision, char pk,
			char obligatorio, Integer fkTabla, Character fkUnoMucho,
			String fnBusNombre, String fnBusCatalogo, String valDefecto,
			Integer fkCampo, String sequencial) {
		this.atributo = atributo;
		this.tabla = tabla;
		this.campo = campo;
		this.tipo = tipo;
		this.longitud = longitud;
		this.precision = precision;
		this.pk = pk;
		this.obligatorio = obligatorio;
		this.fkTabla = fkTabla;
		this.fkUnoMucho = fkUnoMucho;
		this.fnBusNombre = fnBusNombre;
		this.fnBusCatalogo = fnBusCatalogo;
		this.valDefecto = valDefecto;
		this.fkCampo = fkCampo;
		this.sequencial = sequencial;
	}

	@Id
	@Column(name = "cod_atributo", unique = true, nullable = false)
	public int getCodAtributo() {
		return this.codAtributo;
	}

	public void setCodAtributo(int codAtributo) {
		this.codAtributo = codAtributo;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public Atributo getAtributo() {
		return this.atributo;
	}

	public void setAtributo(Atributo atributo) {
		this.atributo = atributo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cod_tabla", nullable = false)
	public Tabla getTabla() {
		return this.tabla;
	}

	public void setTabla(Tabla tabla) {
		this.tabla = tabla;
	}

	@Column(name = "campo", nullable = false, length = 50)
	public String getCampo() {
		return this.campo;
	}

	public void setCampo(String campo) {
		this.campo = campo;
	}

	@Column(name = "tipo", nullable = false, length = 50)
	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	@Column(name = "longitud")
	public Integer getLongitud() {
		return this.longitud;
	}

	public void setLongitud(Integer longitud) {
		this.longitud = longitud;
	}

	@Column(name = "precision")
	public Integer getPrecision() {
		return this.precision;
	}

	public void setPrecision(Integer precision) {
		this.precision = precision;
	}

	@Column(name = "pk", nullable = false, length = 1)
	public char getPk() {
		return this.pk;
	}

	public void setPk(char pk) {
		this.pk = pk;
	}

	@Column(name = "obligatorio", nullable = false, length = 1)
	public char getObligatorio() {
		return this.obligatorio;
	}

	public void setObligatorio(char obligatorio) {
		this.obligatorio = obligatorio;
	}

	@Column(name = "fk_tabla")
	public Integer getFkTabla() {
		return this.fkTabla;
	}

	public void setFkTabla(Integer fkTabla) {
		this.fkTabla = fkTabla;
	}

	@Column(name = "fk_uno_mucho", length = 1)
	public Character getFkUnoMucho() {
		return this.fkUnoMucho;
	}

	public void setFkUnoMucho(Character fkUnoMucho) {
		this.fkUnoMucho = fkUnoMucho;
	}

	@Column(name = "fn_bus_nombre", length = 120)
	public String getFnBusNombre() {
		return this.fnBusNombre;
	}

	public void setFnBusNombre(String fnBusNombre) {
		this.fnBusNombre = fnBusNombre;
	}

	@Column(name = "fn_bus_catalogo", length = 50)
	public String getFnBusCatalogo() {
		return this.fnBusCatalogo;
	}

	public void setFnBusCatalogo(String fnBusCatalogo) {
		this.fnBusCatalogo = fnBusCatalogo;
	}

	@Column(name = "val_defecto", length = 120)
	public String getValDefecto() {
		return this.valDefecto;
	}

	public void setValDefecto(String valDefecto) {
		this.valDefecto = valDefecto;
	}

	@Column(name = "fk_campo")
	public Integer getFkCampo() {
		return this.fkCampo;
	}

	public void setFkCampo(Integer fkCampo) {
		this.fkCampo = fkCampo;
	}

	@Column(name = "sequencial", length = 120)
	public String getSequencial() {
		return this.sequencial;
	}

	public void setSequencial(String sequencial) {
		this.sequencial = sequencial;
	}

}
