package pe.com.captiva.dao.entity;

// Generated 30/10/2015 11:10:41 AM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Clase generated by hbm2java
 */
@Entity
@Table(name = "clase", schema = "soul")
public class Clase implements java.io.Serializable {

	private int codClase;
	private Proyecto proyecto;
	private Tabla tabla;
	private String nombre;
	private String paquete;
	private String infAutor;
	private String infDescripcion;
	private Integer nivel;
	private Set<Atributo> atributos = new HashSet<Atributo>(0);

	public Clase() {
	}

	public Clase(int codClase, Proyecto proyecto, String nombre, String paquete) {
		this.codClase = codClase;
		this.proyecto = proyecto;
		this.nombre = nombre;
		this.paquete = paquete;
	}

	public Clase(int codClase, Proyecto proyecto, Tabla tabla, String nombre,
			String paquete, String infAutor, String infDescripcion,
			Integer nivel, Set<Atributo> atributos) {
		this.codClase = codClase;
		this.proyecto = proyecto;
		this.tabla = tabla;
		this.nombre = nombre;
		this.paquete = paquete;
		this.infAutor = infAutor;
		this.infDescripcion = infDescripcion;
		this.nivel = nivel;
		this.atributos = atributos;
	}

	@Id
	@Column(name = "cod_clase", unique = true, nullable = false)
	public int getCodClase() {
		return this.codClase;
	}

	public void setCodClase(int codClase) {
		this.codClase = codClase;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cod_proyecto", nullable = false)
	public Proyecto getProyecto() {
		return this.proyecto;
	}

	public void setProyecto(Proyecto proyecto) {
		this.proyecto = proyecto;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cod_tabla")
	public Tabla getTabla() {
		return this.tabla;
	}

	public void setTabla(Tabla tabla) {
		this.tabla = tabla;
	}

	@Column(name = "nombre", nullable = false, length = 120)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "paquete", nullable = false, length = 250)
	public String getPaquete() {
		return this.paquete;
	}

	public void setPaquete(String paquete) {
		this.paquete = paquete;
	}

	@Column(name = "inf_autor", length = 120)
	public String getInfAutor() {
		return this.infAutor;
	}

	public void setInfAutor(String infAutor) {
		this.infAutor = infAutor;
	}

	@Column(name = "inf_descripcion")
	public String getInfDescripcion() {
		return this.infDescripcion;
	}

	public void setInfDescripcion(String infDescripcion) {
		this.infDescripcion = infDescripcion;
	}

	@Column(name = "nivel")
	public Integer getNivel() {
		return this.nivel;
	}

	public void setNivel(Integer nivel) {
		this.nivel = nivel;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "clase")
	public Set<Atributo> getAtributos() {
		return this.atributos;
	}

	public void setAtributos(Set<Atributo> atributos) {
		this.atributos = atributos;
	}

}
