package pe.com.captiva.dao.entity;

// Generated 22/10/2015 09:43:27 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ConfiguracionId generated by hbm2java
 */
@Embeddable
public class ConfiguracionId implements java.io.Serializable {

	private int codProyecto;
	private String usuario;

	public ConfiguracionId() {
	}

	public ConfiguracionId(int codProyecto, String usuario) {
		this.codProyecto = codProyecto;
		this.usuario = usuario;
	}

	@Column(name = "cod_proyecto", nullable = false)
	public int getCodProyecto() {
		return this.codProyecto;
	}

	public void setCodProyecto(int codProyecto) {
		this.codProyecto = codProyecto;
	}

	@Column(name = "usuario", nullable = false, length = 20)
	public String getUsuario() {
		return this.usuario;
	}

	public void setUsuario(String usuario) {
		this.usuario = usuario;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ConfiguracionId))
			return false;
		ConfiguracionId castOther = (ConfiguracionId) other;

		return (this.getCodProyecto() == castOther.getCodProyecto())
				&& ((this.getUsuario() == castOther.getUsuario()) || (this
						.getUsuario() != null && castOther.getUsuario() != null && this
						.getUsuario().equals(castOther.getUsuario())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCodProyecto();
		result = 37 * result
				+ (getUsuario() == null ? 0 : this.getUsuario().hashCode());
		return result;
	}

}
