package pe.com.captiva.dao.entity;

// Generated 21/10/2015 10:31:13 PM by Hibernate Tools 4.3.1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Configuracion generated by hbm2java
 */
@Entity
@Table(name = "configuracion", schema = "soul")
public class Configuracion implements java.io.Serializable {

	private ConfiguracionId id;
	private Proyecto proyecto;
	private String rutaWorkspace;
	private String rutaScriptSql;

	public Configuracion() {
	}

	public Configuracion(ConfiguracionId id, Proyecto proyecto,
			String rutaWorkspace, String rutaScriptSql) {
		this.id = id;
		this.proyecto = proyecto;
		this.rutaWorkspace = rutaWorkspace;
		this.rutaScriptSql = rutaScriptSql;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "codProyecto", column = @Column(name = "cod_proyecto", nullable = false)),
			@AttributeOverride(name = "usuario", column = @Column(name = "usuario", nullable = false, length = 20)) })
	public ConfiguracionId getId() {
		return this.id;
	}

	public void setId(ConfiguracionId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cod_proyecto", nullable = false, insertable = false, updatable = false)
	public Proyecto getProyecto() {
		return this.proyecto;
	}

	public void setProyecto(Proyecto proyecto) {
		this.proyecto = proyecto;
	}

	@Column(name = "ruta_workspace", nullable = false)
	public String getRutaWorkspace() {
		return this.rutaWorkspace;
	}

	public void setRutaWorkspace(String rutaWorkspace) {
		this.rutaWorkspace = rutaWorkspace;
	}

	@Column(name = "ruta_script_sql", nullable = false)
	public String getRutaScriptSql() {
		return this.rutaScriptSql;
	}

	public void setRutaScriptSql(String rutaScriptSql) {
		this.rutaScriptSql = rutaScriptSql;
	}

}
