package pe.com.captiva.dao.entity;

// Generated 25/10/2015 10:35:30 PM by Hibernate Tools 4.3.1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ConsultaTabla generated by hbm2java
 */
@Entity
@Table(name = "consulta_tabla", schema = "soul")
public class ConsultaTabla implements java.io.Serializable {

	private ConsultaTablaId id;
	private Consulta consulta;
	private Tabla tablaByCodTabPadre;
	private Tabla tablaByCodTabla;
	private char fk;
	private char flgUnoMuchos;

	public ConsultaTabla() {
	}

	public ConsultaTabla(ConsultaTablaId id, Consulta consulta,
			Tabla tablaByCodTabla, char fk, char flgUnoMuchos) {
		this.id = id;
		this.consulta = consulta;
		this.tablaByCodTabla = tablaByCodTabla;
		this.fk = fk;
		this.flgUnoMuchos = flgUnoMuchos;
	}

	public ConsultaTabla(ConsultaTablaId id, Consulta consulta,
			Tabla tablaByCodTabPadre, Tabla tablaByCodTabla, char fk,
			char flgUnoMuchos) {
		this.id = id;
		this.consulta = consulta;
		this.tablaByCodTabPadre = tablaByCodTabPadre;
		this.tablaByCodTabla = tablaByCodTabla;
		this.fk = fk;
		this.flgUnoMuchos = flgUnoMuchos;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "codConsulta", column = @Column(name = "cod_consulta", nullable = false)),
			@AttributeOverride(name = "codTabla", column = @Column(name = "cod_tabla", nullable = false)) })
	public ConsultaTablaId getId() {
		return this.id;
	}

	public void setId(ConsultaTablaId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cod_consulta", nullable = false, insertable = false, updatable = false)
	public Consulta getConsulta() {
		return this.consulta;
	}

	public void setConsulta(Consulta consulta) {
		this.consulta = consulta;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cod_tab_padre")
	public Tabla getTablaByCodTabPadre() {
		return this.tablaByCodTabPadre;
	}

	public void setTablaByCodTabPadre(Tabla tablaByCodTabPadre) {
		this.tablaByCodTabPadre = tablaByCodTabPadre;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cod_tabla", nullable = false, insertable = false, updatable = false)
	public Tabla getTablaByCodTabla() {
		return this.tablaByCodTabla;
	}

	public void setTablaByCodTabla(Tabla tablaByCodTabla) {
		this.tablaByCodTabla = tablaByCodTabla;
	}

	@Column(name = "fk", nullable = false, length = 1)
	public char getFk() {
		return this.fk;
	}

	public void setFk(char fk) {
		this.fk = fk;
	}

	@Column(name = "flg_uno_muchos", nullable = false, length = 1)
	public char getFlgUnoMuchos() {
		return this.flgUnoMuchos;
	}

	public void setFlgUnoMuchos(char flgUnoMuchos) {
		this.flgUnoMuchos = flgUnoMuchos;
	}

}
