package pe.com.captiva.dao.entity;
// Generated 26/11/2015 04:49:30 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ConsultaReporteRolId generated by hbm2java
 */
@Embeddable
public class ConsultaReporteRolId implements java.io.Serializable {

	private int codConsulta;
	private String codRol;

	public ConsultaReporteRolId() {
	}

	public ConsultaReporteRolId(int codConsulta, String codRol) {
		this.codConsulta = codConsulta;
		this.codRol = codRol;
	}

	@Column(name = "cod_consulta", nullable = false)
	public int getCodConsulta() {
		return this.codConsulta;
	}

	public void setCodConsulta(int codConsulta) {
		this.codConsulta = codConsulta;
	}

	@Column(name = "cod_rol", nullable = false, length = 120)
	public String getCodRol() {
		return this.codRol;
	}

	public void setCodRol(String codRol) {
		this.codRol = codRol;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ConsultaReporteRolId))
			return false;
		ConsultaReporteRolId castOther = (ConsultaReporteRolId) other;

		return (this.getCodConsulta() == castOther.getCodConsulta())
				&& ((this.getCodRol() == castOther.getCodRol()) || (this.getCodRol() != null
						&& castOther.getCodRol() != null && this.getCodRol().equals(castOther.getCodRol())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCodConsulta();
		result = 37 * result + (getCodRol() == null ? 0 : this.getCodRol().hashCode());
		return result;
	}

}
