package pe.com.captiva.dao.entity;
// Generated 26/11/2015 04:49:30 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ConsultaAtributo generated by hbm2java
 */
@Entity
@Table(name = "consulta_atributo", schema = "soul")
public class ConsultaAtributo implements java.io.Serializable {

	private ConsultaAtributoId id;
	private Atributo atributo;
	private Consulta consulta;
	private char flgCondicion;
	private int codTabla;
	private char flgReporteRastrear;
	private char flgReporteBusqueda;

	public ConsultaAtributo() {
	}

	public ConsultaAtributo(ConsultaAtributoId id, Atributo atributo, Consulta consulta, char flgCondicion,
			int codTabla, char flgReporteRastrear, char flgReporteBusqueda) {
		this.id = id;
		this.atributo = atributo;
		this.consulta = consulta;
		this.flgCondicion = flgCondicion;
		this.codTabla = codTabla;
		this.flgReporteRastrear = flgReporteRastrear;
		this.flgReporteBusqueda = flgReporteBusqueda;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "codConsulta", column = @Column(name = "cod_consulta", nullable = false) ),
			@AttributeOverride(name = "codAtributo", column = @Column(name = "cod_atributo", nullable = false) ) })
	public ConsultaAtributoId getId() {
		return this.id;
	}

	public void setId(ConsultaAtributoId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cod_atributo", nullable = false, insertable = false, updatable = false)
	public Atributo getAtributo() {
		return this.atributo;
	}

	public void setAtributo(Atributo atributo) {
		this.atributo = atributo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cod_consulta", nullable = false, insertable = false, updatable = false)
	public Consulta getConsulta() {
		return this.consulta;
	}

	public void setConsulta(Consulta consulta) {
		this.consulta = consulta;
	}

	@Column(name = "flg_condicion", nullable = false, length = 1)
	public char getFlgCondicion() {
		return this.flgCondicion;
	}

	public void setFlgCondicion(char flgCondicion) {
		this.flgCondicion = flgCondicion;
	}

	@Column(name = "cod_tabla", nullable = false)
	public int getCodTabla() {
		return this.codTabla;
	}

	public void setCodTabla(int codTabla) {
		this.codTabla = codTabla;
	}

	@Column(name = "flg_reporte_rastrear", nullable = false, length = 1)
	public char getFlgReporteRastrear() {
		return this.flgReporteRastrear;
	}

	public void setFlgReporteRastrear(char flgReporteRastrear) {
		this.flgReporteRastrear = flgReporteRastrear;
	}

	@Column(name = "flg_reporte_busqueda", nullable = false, length = 1)
	public char getFlgReporteBusqueda() {
		return this.flgReporteBusqueda;
	}

	public void setFlgReporteBusqueda(char flgReporteBusqueda) {
		this.flgReporteBusqueda = flgReporteBusqueda;
	}

}
