package pe.com.captiva.dao.entity;
// Generated 26/11/2015 04:49:30 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ConsultaReporteRol generated by hbm2java
 */
@Entity
@Table(name = "consulta_reporte_rol", schema = "soul")
public class ConsultaReporteRol implements java.io.Serializable {

	private ConsultaReporteRolId id;

	public ConsultaReporteRol() {
	}

	public ConsultaReporteRol(ConsultaReporteRolId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "codConsulta", column = @Column(name = "cod_consulta", nullable = false) ),
			@AttributeOverride(name = "codRol", column = @Column(name = "cod_rol", nullable = false, length = 120) ) })
	public ConsultaReporteRolId getId() {
		return this.id;
	}

	public void setId(ConsultaReporteRolId id) {
		this.id = id;
	}

}
