package pe.com.captiva.dao.entity;

// Generated 12/11/2015 12:28:21 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ConsultaTablaId generated by hbm2java
 */
@Embeddable
public class ConsultaTablaId implements java.io.Serializable {

	private int codConsulta;
	private int codTabla;

	public ConsultaTablaId() {
	}

	public ConsultaTablaId(int codConsulta, int codTabla) {
		this.codConsulta = codConsulta;
		this.codTabla = codTabla;
	}

	@Column(name = "cod_consulta", nullable = false)
	public int getCodConsulta() {
		return this.codConsulta;
	}

	public void setCodConsulta(int codConsulta) {
		this.codConsulta = codConsulta;
	}

	@Column(name = "cod_tabla", nullable = false)
	public int getCodTabla() {
		return this.codTabla;
	}

	public void setCodTabla(int codTabla) {
		this.codTabla = codTabla;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ConsultaTablaId))
			return false;
		ConsultaTablaId castOther = (ConsultaTablaId) other;

		return (this.getCodConsulta() == castOther.getCodConsulta())
				&& (this.getCodTabla() == castOther.getCodTabla());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCodConsulta();
		result = 37 * result + this.getCodTabla();
		return result;
	}

}
