package pe.com.captiva.dao.entity;

// Generated 22/10/2015 09:43:27 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Esquema generated by hbm2java
 */
@Entity
@Table(name = "esquema", schema = "soul")
public class Esquema implements java.io.Serializable {

	private String codEsquema;
	private Proyecto proyecto;
	private Character estado;
	private String descripcion;

	public Esquema() {
	}

	public Esquema(String codEsquema, String descripcion) {
		this.codEsquema = codEsquema;
		this.descripcion = descripcion;
	}

	public Esquema(String codEsquema, Proyecto proyecto, Character estado,
			String descripcion) {
		this.codEsquema = codEsquema;
		this.proyecto = proyecto;
		this.estado = estado;
		this.descripcion = descripcion;
	}

	@Id
	@Column(name = "cod_esquema", unique = true, nullable = false, length = 100)
	public String getCodEsquema() {
		return this.codEsquema;
	}

	public void setCodEsquema(String codEsquema) {
		this.codEsquema = codEsquema;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cod_proyecto")
	public Proyecto getProyecto() {
		return this.proyecto;
	}

	public void setProyecto(Proyecto proyecto) {
		this.proyecto = proyecto;
	}

	@Column(name = "estado", length = 1)
	public Character getEstado() {
		return this.estado;
	}

	public void setEstado(Character estado) {
		this.estado = estado;
	}

	@Column(name = "descripcion", nullable = false)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

}
