package pe.com.captiva.dao.entity;
// Generated 26/11/2015 04:49:30 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * MaeDocumento generated by hbm2java
 */
@Entity
@Table(name = "mae_documento", schema = "soul")
public class MaeDocumento implements java.io.Serializable {

	private MaeDocumentoId id;
	private String nombre;
	private String descripcion;
	private String formatos;
	private char estado;

	public MaeDocumento() {
	}

	public MaeDocumento(MaeDocumentoId id, String nombre, String formatos, char estado) {
		this.id = id;
		this.nombre = nombre;
		this.formatos = formatos;
		this.estado = estado;
	}

	public MaeDocumento(MaeDocumentoId id, String nombre, String descripcion, String formatos, char estado) {
		this.id = id;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.formatos = formatos;
		this.estado = estado;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "codProyecto", column = @Column(name = "cod_proyecto", nullable = false) ),
			@AttributeOverride(name = "codMaeDocumento", column = @Column(name = "cod_mae_documento", nullable = false) ) })
	public MaeDocumentoId getId() {
		return this.id;
	}

	public void setId(MaeDocumentoId id) {
		this.id = id;
	}

	@Column(name = "nombre", nullable = false, length = 100)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "descripcion", length = 250)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "formatos", nullable = false, length = 50)
	public String getFormatos() {
		return this.formatos;
	}

	public void setFormatos(String formatos) {
		this.formatos = formatos;
	}

	@Column(name = "estado", nullable = false, length = 1)
	public char getEstado() {
		return this.estado;
	}

	public void setEstado(char estado) {
		this.estado = estado;
	}

}
