package pe.com.captiva.dao.entity;

// Generated 23/11/2015 04:50:15 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * MaeDocumentoTareaId generated by hbm2java
 */
@Embeddable
public class MaeDocumentoTareaId implements java.io.Serializable {

	private int codProyecto;
	private int codTarea;
	private int codMaeDocumentoTarea;

	public MaeDocumentoTareaId() {
	}

	public MaeDocumentoTareaId(int codProyecto, int codTarea,
			int codMaeDocumentoTarea) {
		this.codProyecto = codProyecto;
		this.codTarea = codTarea;
		this.codMaeDocumentoTarea = codMaeDocumentoTarea;
	}

	@Column(name = "cod_proyecto", nullable = false)
	public int getCodProyecto() {
		return this.codProyecto;
	}

	public void setCodProyecto(int codProyecto) {
		this.codProyecto = codProyecto;
	}

	@Column(name = "cod_tarea", nullable = false)
	public int getCodTarea() {
		return this.codTarea;
	}

	public void setCodTarea(int codTarea) {
		this.codTarea = codTarea;
	}

	@Column(name = "cod_mae_documento_tarea", nullable = false)
	public int getCodMaeDocumentoTarea() {
		return this.codMaeDocumentoTarea;
	}

	public void setCodMaeDocumentoTarea(int codMaeDocumentoTarea) {
		this.codMaeDocumentoTarea = codMaeDocumentoTarea;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof MaeDocumentoTareaId))
			return false;
		MaeDocumentoTareaId castOther = (MaeDocumentoTareaId) other;

		return (this.getCodProyecto() == castOther.getCodProyecto())
				&& (this.getCodTarea() == castOther.getCodTarea())
				&& (this.getCodMaeDocumentoTarea() == castOther
						.getCodMaeDocumentoTarea());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCodProyecto();
		result = 37 * result + this.getCodTarea();
		result = 37 * result + this.getCodMaeDocumentoTarea();
		return result;
	}

}
