package pe.com.captiva.dao.entity;
// Generated 26/11/2015 04:49:30 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * MaeMotivoRechazarId generated by hbm2java
 */
@Embeddable
public class MaeMotivoRechazarId implements java.io.Serializable {

	private int codProyecto;
	private int codTarea;
	private int codMaeMotivoRechazar;

	public MaeMotivoRechazarId() {
	}

	public MaeMotivoRechazarId(int codProyecto, int codTarea, int codMaeMotivoRechazar) {
		this.codProyecto = codProyecto;
		this.codTarea = codTarea;
		this.codMaeMotivoRechazar = codMaeMotivoRechazar;
	}

	@Column(name = "cod_proyecto", nullable = false)
	public int getCodProyecto() {
		return this.codProyecto;
	}

	public void setCodProyecto(int codProyecto) {
		this.codProyecto = codProyecto;
	}

	@Column(name = "cod_tarea", nullable = false)
	public int getCodTarea() {
		return this.codTarea;
	}

	public void setCodTarea(int codTarea) {
		this.codTarea = codTarea;
	}

	@Column(name = "cod_mae_motivo_rechazar", nullable = false)
	public int getCodMaeMotivoRechazar() {
		return this.codMaeMotivoRechazar;
	}

	public void setCodMaeMotivoRechazar(int codMaeMotivoRechazar) {
		this.codMaeMotivoRechazar = codMaeMotivoRechazar;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof MaeMotivoRechazarId))
			return false;
		MaeMotivoRechazarId castOther = (MaeMotivoRechazarId) other;

		return (this.getCodProyecto() == castOther.getCodProyecto()) && (this.getCodTarea() == castOther.getCodTarea())
				&& (this.getCodMaeMotivoRechazar() == castOther.getCodMaeMotivoRechazar());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCodProyecto();
		result = 37 * result + this.getCodTarea();
		result = 37 * result + this.getCodMaeMotivoRechazar();
		return result;
	}

}
