package pe.com.captiva.dao.entity;
// Generated 26/11/2015 04:49:30 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * MaeObservacion generated by hbm2java
 */
@Entity
@Table(name = "mae_observacion", schema = "soul")
public class MaeObservacion implements java.io.Serializable {

	private MaeObservacionId id;
	private String nombre;
	private String descripcion;
	private char estado;

	public MaeObservacion() {
	}

	public MaeObservacion(MaeObservacionId id, String nombre, char estado) {
		this.id = id;
		this.nombre = nombre;
		this.estado = estado;
	}

	public MaeObservacion(MaeObservacionId id, String nombre, String descripcion, char estado) {
		this.id = id;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.estado = estado;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "codProyecto", column = @Column(name = "cod_proyecto", nullable = false) ),
			@AttributeOverride(name = "codTarea", column = @Column(name = "cod_tarea", nullable = false) ),
			@AttributeOverride(name = "codMaeObservacion", column = @Column(name = "cod_mae_observacion", nullable = false) ) })
	public MaeObservacionId getId() {
		return this.id;
	}

	public void setId(MaeObservacionId id) {
		this.id = id;
	}

	@Column(name = "nombre", nullable = false, length = 100)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "descripcion", length = 250)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "estado", nullable = false, length = 1)
	public char getEstado() {
		return this.estado;
	}

	public void setEstado(char estado) {
		this.estado = estado;
	}

}
