package pe.com.captiva.dao.entity;
// Generated 01/12/2015 04:35:12 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * MaeSubsanacionId generated by hbm2java
 */
@Embeddable
public class MaeSubsanacionId implements java.io.Serializable {

	private int codProyecto;
	private int codTarea;
	private int codMaeObservacion;
	private int codMaeSubsanacion;

	public MaeSubsanacionId() {
	}

	public MaeSubsanacionId(int codProyecto, int codTarea, int codMaeObservacion, int codMaeSubsanacion) {
		this.codProyecto = codProyecto;
		this.codTarea = codTarea;
		this.codMaeObservacion = codMaeObservacion;
		this.codMaeSubsanacion = codMaeSubsanacion;
	}

	@Column(name = "cod_proyecto", nullable = false)
	public int getCodProyecto() {
		return this.codProyecto;
	}

	public void setCodProyecto(int codProyecto) {
		this.codProyecto = codProyecto;
	}

	@Column(name = "cod_tarea", nullable = false)
	public int getCodTarea() {
		return this.codTarea;
	}

	public void setCodTarea(int codTarea) {
		this.codTarea = codTarea;
	}

	@Column(name = "cod_mae_observacion", nullable = false)
	public int getCodMaeObservacion() {
		return this.codMaeObservacion;
	}

	public void setCodMaeObservacion(int codMaeObservacion) {
		this.codMaeObservacion = codMaeObservacion;
	}

	@Column(name = "cod_mae_subsanacion", nullable = false)
	public int getCodMaeSubsanacion() {
		return this.codMaeSubsanacion;
	}

	public void setCodMaeSubsanacion(int codMaeSubsanacion) {
		this.codMaeSubsanacion = codMaeSubsanacion;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof MaeSubsanacionId))
			return false;
		MaeSubsanacionId castOther = (MaeSubsanacionId) other;

		return (this.getCodProyecto() == castOther.getCodProyecto()) && (this.getCodTarea() == castOther.getCodTarea())
				&& (this.getCodMaeObservacion() == castOther.getCodMaeObservacion())
				&& (this.getCodMaeSubsanacion() == castOther.getCodMaeSubsanacion());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCodProyecto();
		result = 37 * result + this.getCodTarea();
		result = 37 * result + this.getCodMaeObservacion();
		result = 37 * result + this.getCodMaeSubsanacion();
		return result;
	}

}
