package pe.com.captiva.dao.entity;
// Generated 26/11/2015 04:49:30 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ProcesoInicioSubSeccionId generated by hbm2java
 */
@Embeddable
public class ProcesoInicioSubSeccionId implements java.io.Serializable {

	private int codProceso;
	private int codSubSeccion;

	public ProcesoInicioSubSeccionId() {
	}

	public ProcesoInicioSubSeccionId(int codProceso, int codSubSeccion) {
		this.codProceso = codProceso;
		this.codSubSeccion = codSubSeccion;
	}

	@Column(name = "cod_proceso", nullable = false)
	public int getCodProceso() {
		return this.codProceso;
	}

	public void setCodProceso(int codProceso) {
		this.codProceso = codProceso;
	}

	@Column(name = "cod_sub_seccion", nullable = false)
	public int getCodSubSeccion() {
		return this.codSubSeccion;
	}

	public void setCodSubSeccion(int codSubSeccion) {
		this.codSubSeccion = codSubSeccion;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ProcesoInicioSubSeccionId))
			return false;
		ProcesoInicioSubSeccionId castOther = (ProcesoInicioSubSeccionId) other;

		return (this.getCodProceso() == castOther.getCodProceso())
				&& (this.getCodSubSeccion() == castOther.getCodSubSeccion());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCodProceso();
		result = 37 * result + this.getCodSubSeccion();
		return result;
	}

}
