package pe.com.captiva.dao.entity;
// Generated 01/12/2015 04:35:12 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ProcesoDetalleSubSeccion generated by hbm2java
 */
@Entity
@Table(name = "proceso_detalle_sub_seccion", schema = "soul")
public class ProcesoDetalleSubSeccion implements java.io.Serializable {

	private ProcesoDetalleSubSeccionId id;
	private Proceso proceso;

	public ProcesoDetalleSubSeccion() {
	}

	public ProcesoDetalleSubSeccion(ProcesoDetalleSubSeccionId id) {
		this.id = id;
	}

	public ProcesoDetalleSubSeccion(ProcesoDetalleSubSeccionId id, Proceso proceso) {
		this.id = id;
		this.proceso = proceso;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "codProceso", column = @Column(name = "cod_proceso") ),
			@AttributeOverride(name = "codSeccion", column = @Column(name = "cod_seccion", nullable = false, length = 20) ),
			@AttributeOverride(name = "codSubSeccion", column = @Column(name = "cod_sub_seccion", nullable = false) ),
			@AttributeOverride(name = "nombre", column = @Column(name = "nombre", nullable = false, length = 100) ) })
	public ProcesoDetalleSubSeccionId getId() {
		return this.id;
	}

	public void setId(ProcesoDetalleSubSeccionId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cod_proceso", insertable = false, updatable = false)
	public Proceso getProceso() {
		return this.proceso;
	}

	public void setProceso(Proceso proceso) {
		this.proceso = proceso;
	}

}
