package pe.com.captiva.dao.entity;

// Generated 12/11/2015 12:28:21 PM by Hibernate Tools 4.3.1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ProcesoDetalleSubSeccion generated by hbm2java
 */
@Entity
@Table(name = "proceso_detalle_sub_seccion", schema = "soul")
public class ProcesoDetalleSubSeccion implements java.io.Serializable {

	private ProcesoDetalleSubSeccionId id;

	public ProcesoDetalleSubSeccion() {
	}

	public ProcesoDetalleSubSeccion(ProcesoDetalleSubSeccionId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "codProceso", column = @Column(name = "cod_proceso")),
			@AttributeOverride(name = "codSeccion", column = @Column(name = "cod_seccion", nullable = false, length = 20)),
			@AttributeOverride(name = "codSubSeccion", column = @Column(name = "cod_sub_seccion", nullable = false)),
			@AttributeOverride(name = "nombre", column = @Column(name = "nombre", nullable = false, length = 100)) })
	public ProcesoDetalleSubSeccionId getId() {
		return this.id;
	}

	public void setId(ProcesoDetalleSubSeccionId id) {
		this.id = id;
	}

}
