package pe.com.captiva.dao.entity;

// Generated 19/11/2015 03:54:12 PM by Hibernate Tools 4.3.1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ProcesoInicio generated by hbm2java
 */
@Entity
@Table(name = "proceso_inicio", schema = "soul")
public class ProcesoInicio implements java.io.Serializable {

	private ProcesoInicioId id;
	private Atributo atributo;
	private Proceso proceso;
	private String webEtiqueta;
	private String webTipo;
	private char webTipoCampo;
	private Character webTipoLista;
	private String webCatalogo;
	private char webRequerido;
	private String webMensajeValidacion;
	private String valOmision;

	public ProcesoInicio() {
	}

	public ProcesoInicio(ProcesoInicioId id, Atributo atributo,
			Proceso proceso, String webEtiqueta, String webTipo,
			char webTipoCampo, char webRequerido) {
		this.id = id;
		this.atributo = atributo;
		this.proceso = proceso;
		this.webEtiqueta = webEtiqueta;
		this.webTipo = webTipo;
		this.webTipoCampo = webTipoCampo;
		this.webRequerido = webRequerido;
	}

	public ProcesoInicio(ProcesoInicioId id, Atributo atributo,
			Proceso proceso, String webEtiqueta, String webTipo,
			char webTipoCampo, Character webTipoLista, String webCatalogo,
			char webRequerido, String webMensajeValidacion, String valOmision) {
		this.id = id;
		this.atributo = atributo;
		this.proceso = proceso;
		this.webEtiqueta = webEtiqueta;
		this.webTipo = webTipo;
		this.webTipoCampo = webTipoCampo;
		this.webTipoLista = webTipoLista;
		this.webCatalogo = webCatalogo;
		this.webRequerido = webRequerido;
		this.webMensajeValidacion = webMensajeValidacion;
		this.valOmision = valOmision;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "codProceso", column = @Column(name = "cod_proceso", nullable = false)),
			@AttributeOverride(name = "codSubSeccion", column = @Column(name = "cod_sub_seccion", nullable = false)),
			@AttributeOverride(name = "codProcesoInicio", column = @Column(name = "cod_proceso_inicio", nullable = false)) })
	public ProcesoInicioId getId() {
		return this.id;
	}

	public void setId(ProcesoInicioId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cod_atributo", nullable = false)
	public Atributo getAtributo() {
		return this.atributo;
	}

	public void setAtributo(Atributo atributo) {
		this.atributo = atributo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cod_proceso", nullable = false, insertable = false, updatable = false)
	public Proceso getProceso() {
		return this.proceso;
	}

	public void setProceso(Proceso proceso) {
		this.proceso = proceso;
	}

	@Column(name = "web_etiqueta", nullable = false)
	public String getWebEtiqueta() {
		return this.webEtiqueta;
	}

	public void setWebEtiqueta(String webEtiqueta) {
		this.webEtiqueta = webEtiqueta;
	}

	@Column(name = "web_tipo", nullable = false, length = 60)
	public String getWebTipo() {
		return this.webTipo;
	}

	public void setWebTipo(String webTipo) {
		this.webTipo = webTipo;
	}

	@Column(name = "web_tipo_campo", nullable = false, length = 1)
	public char getWebTipoCampo() {
		return this.webTipoCampo;
	}

	public void setWebTipoCampo(char webTipoCampo) {
		this.webTipoCampo = webTipoCampo;
	}

	@Column(name = "web_tipo_lista", length = 1)
	public Character getWebTipoLista() {
		return this.webTipoLista;
	}

	public void setWebTipoLista(Character webTipoLista) {
		this.webTipoLista = webTipoLista;
	}

	@Column(name = "web_catalogo", length = 60)
	public String getWebCatalogo() {
		return this.webCatalogo;
	}

	public void setWebCatalogo(String webCatalogo) {
		this.webCatalogo = webCatalogo;
	}

	@Column(name = "web_requerido", nullable = false, length = 1)
	public char getWebRequerido() {
		return this.webRequerido;
	}

	public void setWebRequerido(char webRequerido) {
		this.webRequerido = webRequerido;
	}

	@Column(name = "web_mensaje_validacion")
	public String getWebMensajeValidacion() {
		return this.webMensajeValidacion;
	}

	public void setWebMensajeValidacion(String webMensajeValidacion) {
		this.webMensajeValidacion = webMensajeValidacion;
	}

	@Column(name = "val_omision")
	public String getValOmision() {
		return this.valOmision;
	}

	public void setValOmision(String valOmision) {
		this.valOmision = valOmision;
	}

}
