package pe.com.captiva.dao.entity;

// Generated 25/10/2015 10:35:30 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Proceso generated by hbm2java
 */
@Entity
@Table(name = "proceso", schema = "soul")
public class Proceso implements java.io.Serializable {

	private int codProceso;
	private Consulta consultaByCodConResumen;
	private Consulta consultaByCodConDetalle;
	private Proyecto proyecto;
	private String infNombre;
	private String codUniNegocio;
	private String codProducto;
	private String infSufijo;
	private String bpmPlantilla;
	private int bpmActInicio;
	private String javPaquete;
	private String javClase;
	private String javAleProceso;
	private String javDatasource;
	private String javDocSequence;
	private Set<ProcesoInicio> procesoInicios = new HashSet<ProcesoInicio>(0);
	private Set<Rol> rols = new HashSet<Rol>(0);
	private Set<Tarea> tareas = new HashSet<Tarea>(0);

	public Proceso() {
	}

	public Proceso(int codProceso, Consulta consultaByCodConResumen,
			Consulta consultaByCodConDetalle, Proyecto proyecto,
			String infNombre, String codUniNegocio, String codProducto,
			String bpmPlantilla, int bpmActInicio, String javPaquete,
			String javClase, String javDatasource) {
		this.codProceso = codProceso;
		this.consultaByCodConResumen = consultaByCodConResumen;
		this.consultaByCodConDetalle = consultaByCodConDetalle;
		this.proyecto = proyecto;
		this.infNombre = infNombre;
		this.codUniNegocio = codUniNegocio;
		this.codProducto = codProducto;
		this.bpmPlantilla = bpmPlantilla;
		this.bpmActInicio = bpmActInicio;
		this.javPaquete = javPaquete;
		this.javClase = javClase;
		this.javDatasource = javDatasource;
	}

	public Proceso(int codProceso, Consulta consultaByCodConResumen,
			Consulta consultaByCodConDetalle, Proyecto proyecto,
			String infNombre, String codUniNegocio, String codProducto,
			String infSufijo, String bpmPlantilla, int bpmActInicio,
			String javPaquete, String javClase, String javAleProceso,
			String javDatasource, String javDocSequence,
			Set<ProcesoInicio> procesoInicios, Set<Rol> rols, Set<Tarea> tareas) {
		this.codProceso = codProceso;
		this.consultaByCodConResumen = consultaByCodConResumen;
		this.consultaByCodConDetalle = consultaByCodConDetalle;
		this.proyecto = proyecto;
		this.infNombre = infNombre;
		this.codUniNegocio = codUniNegocio;
		this.codProducto = codProducto;
		this.infSufijo = infSufijo;
		this.bpmPlantilla = bpmPlantilla;
		this.bpmActInicio = bpmActInicio;
		this.javPaquete = javPaquete;
		this.javClase = javClase;
		this.javAleProceso = javAleProceso;
		this.javDatasource = javDatasource;
		this.javDocSequence = javDocSequence;
		this.procesoInicios = procesoInicios;
		this.rols = rols;
		this.tareas = tareas;
	}

	@Id
	@Column(name = "cod_proceso", unique = true, nullable = false)
	public int getCodProceso() {
		return this.codProceso;
	}

	public void setCodProceso(int codProceso) {
		this.codProceso = codProceso;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cod_con_resumen", nullable = false)
	public Consulta getConsultaByCodConResumen() {
		return this.consultaByCodConResumen;
	}

	public void setConsultaByCodConResumen(Consulta consultaByCodConResumen) {
		this.consultaByCodConResumen = consultaByCodConResumen;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cod_con_detalle", nullable = false)
	public Consulta getConsultaByCodConDetalle() {
		return this.consultaByCodConDetalle;
	}

	public void setConsultaByCodConDetalle(Consulta consultaByCodConDetalle) {
		this.consultaByCodConDetalle = consultaByCodConDetalle;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cod_proyecto", nullable = false)
	public Proyecto getProyecto() {
		return this.proyecto;
	}

	public void setProyecto(Proyecto proyecto) {
		this.proyecto = proyecto;
	}

	@Column(name = "inf_nombre", nullable = false, length = 120)
	public String getInfNombre() {
		return this.infNombre;
	}

	public void setInfNombre(String infNombre) {
		this.infNombre = infNombre;
	}

	@Column(name = "cod_uni_negocio", nullable = false, length = 12)
	public String getCodUniNegocio() {
		return this.codUniNegocio;
	}

	public void setCodUniNegocio(String codUniNegocio) {
		this.codUniNegocio = codUniNegocio;
	}

	@Column(name = "cod_producto", nullable = false, length = 12)
	public String getCodProducto() {
		return this.codProducto;
	}

	public void setCodProducto(String codProducto) {
		this.codProducto = codProducto;
	}

	@Column(name = "inf_sufijo", length = 6)
	public String getInfSufijo() {
		return this.infSufijo;
	}

	public void setInfSufijo(String infSufijo) {
		this.infSufijo = infSufijo;
	}

	@Column(name = "bpm_plantilla", nullable = false, length = 120)
	public String getBpmPlantilla() {
		return this.bpmPlantilla;
	}

	public void setBpmPlantilla(String bpmPlantilla) {
		this.bpmPlantilla = bpmPlantilla;
	}

	@Column(name = "bpm_act_inicio", nullable = false)
	public int getBpmActInicio() {
		return this.bpmActInicio;
	}

	public void setBpmActInicio(int bpmActInicio) {
		this.bpmActInicio = bpmActInicio;
	}

	@Column(name = "jav_paquete", nullable = false)
	public String getJavPaquete() {
		return this.javPaquete;
	}

	public void setJavPaquete(String javPaquete) {
		this.javPaquete = javPaquete;
	}

	@Column(name = "jav_clase", nullable = false, length = 120)
	public String getJavClase() {
		return this.javClase;
	}

	public void setJavClase(String javClase) {
		this.javClase = javClase;
	}

	@Column(name = "jav_ale_proceso", length = 120)
	public String getJavAleProceso() {
		return this.javAleProceso;
	}

	public void setJavAleProceso(String javAleProceso) {
		this.javAleProceso = javAleProceso;
	}

	@Column(name = "jav_datasource", nullable = false, length = 120)
	public String getJavDatasource() {
		return this.javDatasource;
	}

	public void setJavDatasource(String javDatasource) {
		this.javDatasource = javDatasource;
	}

	@Column(name = "jav_doc_sequence", length = 120)
	public String getJavDocSequence() {
		return this.javDocSequence;
	}

	public void setJavDocSequence(String javDocSequence) {
		this.javDocSequence = javDocSequence;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "proceso")
	public Set<ProcesoInicio> getProcesoInicios() {
		return this.procesoInicios;
	}

	public void setProcesoInicios(Set<ProcesoInicio> procesoInicios) {
		this.procesoInicios = procesoInicios;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "proceso_rol_potencial", schema = "soul", joinColumns = { @JoinColumn(name = "cod_proceso", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "cod_rol", nullable = false, updatable = false) })
	public Set<Rol> getRols() {
		return this.rols;
	}

	public void setRols(Set<Rol> rols) {
		this.rols = rols;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "proceso")
	public Set<Tarea> getTareas() {
		return this.tareas;
	}

	public void setTareas(Set<Tarea> tareas) {
		this.tareas = tareas;
	}

}
