package pe.com.captiva.dao.entity;

// Generated 19/11/2015 03:54:12 PM by Hibernate Tools 4.3.1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ProcesoInicioSubSeccion generated by hbm2java
 */
@Entity
@Table(name = "proceso_inicio_sub_seccion", schema = "soul")
public class ProcesoInicioSubSeccion implements java.io.Serializable {

	private ProcesoInicioSubSeccionId id;
	private String nombre;

	public ProcesoInicioSubSeccion() {
	}

	public ProcesoInicioSubSeccion(ProcesoInicioSubSeccionId id, String nombre) {
		this.id = id;
		this.nombre = nombre;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "codProceso", column = @Column(name = "cod_proceso", nullable = false)),
			@AttributeOverride(name = "codSubSeccion", column = @Column(name = "cod_sub_seccion", nullable = false)) })
	public ProcesoInicioSubSeccionId getId() {
		return this.id;
	}

	public void setId(ProcesoInicioSubSeccionId id) {
		this.id = id;
	}

	@Column(name = "nombre", nullable = false, length = 100)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

}
