package pe.com.captiva.dao.entity;

// Generated 19/11/2015 03:54:12 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ProcesoInicioId generated by hbm2java
 */
@Embeddable
public class ProcesoInicioId implements java.io.Serializable {

	private int codProceso;
	private int codSubSeccion;
	private int codProcesoInicio;

	public ProcesoInicioId() {
	}

	public ProcesoInicioId(int codProceso, int codSubSeccion,
			int codProcesoInicio) {
		this.codProceso = codProceso;
		this.codSubSeccion = codSubSeccion;
		this.codProcesoInicio = codProcesoInicio;
	}

	@Column(name = "cod_proceso", nullable = false)
	public int getCodProceso() {
		return this.codProceso;
	}

	public void setCodProceso(int codProceso) {
		this.codProceso = codProceso;
	}

	@Column(name = "cod_sub_seccion", nullable = false)
	public int getCodSubSeccion() {
		return this.codSubSeccion;
	}

	public void setCodSubSeccion(int codSubSeccion) {
		this.codSubSeccion = codSubSeccion;
	}

	@Column(name = "cod_proceso_inicio", nullable = false)
	public int getCodProcesoInicio() {
		return this.codProcesoInicio;
	}

	public void setCodProcesoInicio(int codProcesoInicio) {
		this.codProcesoInicio = codProcesoInicio;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ProcesoInicioId))
			return false;
		ProcesoInicioId castOther = (ProcesoInicioId) other;

		return (this.getCodProceso() == castOther.getCodProceso())
				&& (this.getCodSubSeccion() == castOther.getCodSubSeccion())
				&& (this.getCodProcesoInicio() == castOther
						.getCodProcesoInicio());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCodProceso();
		result = 37 * result + this.getCodSubSeccion();
		result = 37 * result + this.getCodProcesoInicio();
		return result;
	}

}
