package pe.com.captiva.dao.entity;

// Generated 23/11/2015 04:50:15 PM by Hibernate Tools 4.3.1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ProcesoDetalle generated by hbm2java
 */
@Entity
@Table(name = "proceso_detalle", schema = "soul")
public class ProcesoDetalle implements java.io.Serializable {

	private ProcesoDetalleId id;

	public ProcesoDetalle() {
	}

	public ProcesoDetalle(ProcesoDetalleId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "codProceso", column = @Column(name = "cod_proceso")),
			@AttributeOverride(name = "codSeccion", column = @Column(name = "cod_seccion", nullable = false, length = 20)),
			@AttributeOverride(name = "codSubSeccion", column = @Column(name = "cod_sub_seccion", nullable = false)),
			@AttributeOverride(name = "codProcesoDetalle", column = @Column(name = "cod_proceso_detalle", nullable = false)),
			@AttributeOverride(name = "codAtributo", column = @Column(name = "cod_atributo", nullable = false)),
			@AttributeOverride(name = "webEtiqueta", column = @Column(name = "web_etiqueta", nullable = false)) })
	public ProcesoDetalleId getId() {
		return this.id;
	}

	public void setId(ProcesoDetalleId id) {
		this.id = id;
	}

}
