package pe.com.captiva.dao.entity;

// Generated 25/10/2015 06:37:17 AM by Hibernate Tools 4.3.1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ProcesoInicio generated by hbm2java
 */
@Entity
@Table(name = "proceso_inicio", schema = "soul")
public class ProcesoInicio implements java.io.Serializable {

	private ProcesoInicioId id;
	private Atributo atributo;
	private Proceso proceso;
	private char bpmFlgEntrada;
	private String bpmObjReferencia;
	private char bpmFlgPiid;
	private char webFlgReferencia;
	private char webFlgValidacion;
	private String webMenValidacion;
	private String webValOmision;
	private char webRequerido;
	private String webNomCatCombo;
	private char sqlFlgAutogenerado;
	private String sqlNomSecuencial;

	public ProcesoInicio() {
	}

	public ProcesoInicio(ProcesoInicioId id, Atributo atributo,
			Proceso proceso, char bpmFlgEntrada, char bpmFlgPiid,
			char webFlgReferencia, char webFlgValidacion, char webRequerido,
			char sqlFlgAutogenerado) {
		this.id = id;
		this.atributo = atributo;
		this.proceso = proceso;
		this.bpmFlgEntrada = bpmFlgEntrada;
		this.bpmFlgPiid = bpmFlgPiid;
		this.webFlgReferencia = webFlgReferencia;
		this.webFlgValidacion = webFlgValidacion;
		this.webRequerido = webRequerido;
		this.sqlFlgAutogenerado = sqlFlgAutogenerado;
	}

	public ProcesoInicio(ProcesoInicioId id, Atributo atributo,
			Proceso proceso, char bpmFlgEntrada, String bpmObjReferencia,
			char bpmFlgPiid, char webFlgReferencia, char webFlgValidacion,
			String webMenValidacion, String webValOmision, char webRequerido,
			String webNomCatCombo, char sqlFlgAutogenerado,
			String sqlNomSecuencial) {
		this.id = id;
		this.atributo = atributo;
		this.proceso = proceso;
		this.bpmFlgEntrada = bpmFlgEntrada;
		this.bpmObjReferencia = bpmObjReferencia;
		this.bpmFlgPiid = bpmFlgPiid;
		this.webFlgReferencia = webFlgReferencia;
		this.webFlgValidacion = webFlgValidacion;
		this.webMenValidacion = webMenValidacion;
		this.webValOmision = webValOmision;
		this.webRequerido = webRequerido;
		this.webNomCatCombo = webNomCatCombo;
		this.sqlFlgAutogenerado = sqlFlgAutogenerado;
		this.sqlNomSecuencial = sqlNomSecuencial;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "codProceso", column = @Column(name = "cod_proceso", nullable = false)),
			@AttributeOverride(name = "codAtributo", column = @Column(name = "cod_atributo", nullable = false)) })
	public ProcesoInicioId getId() {
		return this.id;
	}

	public void setId(ProcesoInicioId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cod_atributo", nullable = false, insertable = false, updatable = false)
	public Atributo getAtributo() {
		return this.atributo;
	}

	public void setAtributo(Atributo atributo) {
		this.atributo = atributo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cod_proceso", nullable = false, insertable = false, updatable = false)
	public Proceso getProceso() {
		return this.proceso;
	}

	public void setProceso(Proceso proceso) {
		this.proceso = proceso;
	}

	@Column(name = "bpm_flg_entrada", nullable = false, length = 1)
	public char getBpmFlgEntrada() {
		return this.bpmFlgEntrada;
	}

	public void setBpmFlgEntrada(char bpmFlgEntrada) {
		this.bpmFlgEntrada = bpmFlgEntrada;
	}

	@Column(name = "bpm_obj_referencia", length = 60)
	public String getBpmObjReferencia() {
		return this.bpmObjReferencia;
	}

	public void setBpmObjReferencia(String bpmObjReferencia) {
		this.bpmObjReferencia = bpmObjReferencia;
	}

	@Column(name = "bpm_flg_piid", nullable = false, length = 1)
	public char getBpmFlgPiid() {
		return this.bpmFlgPiid;
	}

	public void setBpmFlgPiid(char bpmFlgPiid) {
		this.bpmFlgPiid = bpmFlgPiid;
	}

	@Column(name = "web_flg_referencia", nullable = false, length = 1)
	public char getWebFlgReferencia() {
		return this.webFlgReferencia;
	}

	public void setWebFlgReferencia(char webFlgReferencia) {
		this.webFlgReferencia = webFlgReferencia;
	}

	@Column(name = "web_flg_validacion", nullable = false, length = 1)
	public char getWebFlgValidacion() {
		return this.webFlgValidacion;
	}

	public void setWebFlgValidacion(char webFlgValidacion) {
		this.webFlgValidacion = webFlgValidacion;
	}

	@Column(name = "web_men_validacion")
	public String getWebMenValidacion() {
		return this.webMenValidacion;
	}

	public void setWebMenValidacion(String webMenValidacion) {
		this.webMenValidacion = webMenValidacion;
	}

	@Column(name = "web_val_omision")
	public String getWebValOmision() {
		return this.webValOmision;
	}

	public void setWebValOmision(String webValOmision) {
		this.webValOmision = webValOmision;
	}

	@Column(name = "web_requerido", nullable = false, length = 1)
	public char getWebRequerido() {
		return this.webRequerido;
	}

	public void setWebRequerido(char webRequerido) {
		this.webRequerido = webRequerido;
	}

	@Column(name = "web_nom_cat_combo")
	public String getWebNomCatCombo() {
		return this.webNomCatCombo;
	}

	public void setWebNomCatCombo(String webNomCatCombo) {
		this.webNomCatCombo = webNomCatCombo;
	}

	@Column(name = "sql_flg_autogenerado", nullable = false, length = 1)
	public char getSqlFlgAutogenerado() {
		return this.sqlFlgAutogenerado;
	}

	public void setSqlFlgAutogenerado(char sqlFlgAutogenerado) {
		this.sqlFlgAutogenerado = sqlFlgAutogenerado;
	}

	@Column(name = "sql_nom_secuencial")
	public String getSqlNomSecuencial() {
		return this.sqlNomSecuencial;
	}

	public void setSqlNomSecuencial(String sqlNomSecuencial) {
		this.sqlNomSecuencial = sqlNomSecuencial;
	}

}
