package pe.com.captiva.dao.entity;
// Generated 01/12/2015 04:35:12 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ProcesoDetalle generated by hbm2java
 */
@Entity
@Table(name = "proceso_detalle", schema = "soul")
public class ProcesoDetalle implements java.io.Serializable {

	private ProcesoDetalleId id;
	private Atributo atributo;
	private Proceso proceso;

	public ProcesoDetalle() {
	}

	public ProcesoDetalle(ProcesoDetalleId id, Atributo atributo) {
		this.id = id;
		this.atributo = atributo;
	}

	public ProcesoDetalle(ProcesoDetalleId id, Atributo atributo, Proceso proceso) {
		this.id = id;
		this.atributo = atributo;
		this.proceso = proceso;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "codProceso", column = @Column(name = "cod_proceso") ),
			@AttributeOverride(name = "codSeccion", column = @Column(name = "cod_seccion", nullable = false, length = 20) ),
			@AttributeOverride(name = "codSubSeccion", column = @Column(name = "cod_sub_seccion", nullable = false) ),
			@AttributeOverride(name = "codProcesoDetalle", column = @Column(name = "cod_proceso_detalle", nullable = false) ),
			@AttributeOverride(name = "codAtributo", column = @Column(name = "cod_atributo", nullable = false) ),
			@AttributeOverride(name = "webEtiqueta", column = @Column(name = "web_etiqueta", nullable = false) ) })
	public ProcesoDetalleId getId() {
		return this.id;
	}

	public void setId(ProcesoDetalleId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cod_atributo", nullable = false, insertable = false, updatable = false)
	public Atributo getAtributo() {
		return this.atributo;
	}

	public void setAtributo(Atributo atributo) {
		this.atributo = atributo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cod_proceso", insertable = false, updatable = false)
	public Proceso getProceso() {
		return this.proceso;
	}

	public void setProceso(Proceso proceso) {
		this.proceso = proceso;
	}

}
