package pe.com.captiva.dao.entity;
// Generated 26/11/2015 04:49:30 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TablaMantenimientoRolId generated by hbm2java
 */
@Embeddable
public class TablaMantenimientoRolId implements java.io.Serializable {

	private int codTabla;
	private String codRol;

	public TablaMantenimientoRolId() {
	}

	public TablaMantenimientoRolId(int codTabla, String codRol) {
		this.codTabla = codTabla;
		this.codRol = codRol;
	}

	@Column(name = "cod_tabla", nullable = false)
	public int getCodTabla() {
		return this.codTabla;
	}

	public void setCodTabla(int codTabla) {
		this.codTabla = codTabla;
	}

	@Column(name = "cod_rol", nullable = false, length = 120)
	public String getCodRol() {
		return this.codRol;
	}

	public void setCodRol(String codRol) {
		this.codRol = codRol;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TablaMantenimientoRolId))
			return false;
		TablaMantenimientoRolId castOther = (TablaMantenimientoRolId) other;

		return (this.getCodTabla() == castOther.getCodTabla())
				&& ((this.getCodRol() == castOther.getCodRol()) || (this.getCodRol() != null
						&& castOther.getCodRol() != null && this.getCodRol().equals(castOther.getCodRol())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCodTabla();
		result = 37 * result + (getCodRol() == null ? 0 : this.getCodRol().hashCode());
		return result;
	}

}
