package pe.com.captiva.dao.entity;
// Generated 01/12/2015 04:35:12 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * TablaMantenimientoRol generated by hbm2java
 */
@Entity
@Table(name = "tabla_mantenimiento_rol", schema = "soul")
public class TablaMantenimientoRol implements java.io.Serializable {

	private TablaMantenimientoRolId id;

	public TablaMantenimientoRol() {
	}

	public TablaMantenimientoRol(TablaMantenimientoRolId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "codTabla", column = @Column(name = "cod_tabla", nullable = false) ),
			@AttributeOverride(name = "codRol", column = @Column(name = "cod_rol", nullable = false, length = 120) ) })
	public TablaMantenimientoRolId getId() {
		return this.id;
	}

	public void setId(TablaMantenimientoRolId id) {
		this.id = id;
	}

}
