package pe.com.captiva.dao.entity;
// Generated 01/12/2015 04:35:12 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * TareaAccion generated by hbm2java
 */
@Entity
@Table(name = "tarea_accion", schema = "soul")
public class TareaAccion implements java.io.Serializable {

	private TareaAccionId id;

	public TareaAccion() {
	}

	public TareaAccion(TareaAccionId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "codTarea", column = @Column(name = "cod_tarea") ),
			@AttributeOverride(name = "codSeccion", column = @Column(name = "cod_seccion", nullable = false, length = 20) ),
			@AttributeOverride(name = "codSubSeccion", column = @Column(name = "cod_sub_seccion") ),
			@AttributeOverride(name = "codTareaAccion", column = @Column(name = "cod_tarea_accion", nullable = false) ),
			@AttributeOverride(name = "codTipoAccion", column = @Column(name = "cod_tipo_accion", nullable = false, length = 1) ),
			@AttributeOverride(name = "codAtributo", column = @Column(name = "cod_atributo", nullable = false) ),
			@AttributeOverride(name = "webEtiqueta", column = @Column(name = "web_etiqueta") ),
			@AttributeOverride(name = "webTipo", column = @Column(name = "web_tipo", length = 60) ),
			@AttributeOverride(name = "webTipoCampo", column = @Column(name = "web_tipo_campo", length = 1) ),
			@AttributeOverride(name = "webTipoLista", column = @Column(name = "web_tipo_lista", length = 1) ),
			@AttributeOverride(name = "webCatalogo", column = @Column(name = "web_catalogo", length = 60) ),
			@AttributeOverride(name = "webRequerido", column = @Column(name = "web_requerido", nullable = false, length = 1) ),
			@AttributeOverride(name = "webMensajeValidacion", column = @Column(name = "web_mensaje_validacion") ),
			@AttributeOverride(name = "valOmision", column = @Column(name = "val_omision") ) })
	public TareaAccionId getId() {
		return this.id;
	}

	public void setId(TareaAccionId id) {
		this.id = id;
	}

}
