package pe.com.captiva.dao.entity;

// Generated 25/10/2015 06:37:17 AM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Tarea generated by hbm2java
 */
@Entity
@Table(name = "tarea", schema = "soul")
public class Tarea implements java.io.Serializable {

	private int codTarea;
	private Consulta consultaByCodConTrabajar;
	private Consulta consultaByCodConCompletar;
	private Proceso proceso;
	private String nombre;
	private String versionTarea;
	private String sqlAleas;
	private String sqlDatasource;
	private String bpmNombre;
	private String javPaquete;
	private String javClase;
	private char webAccCompletar;
	private char webAccGrabar;
	private char webAccCancelar;
	private char webAccRechazar;
	private char webAccObservar;
	private char webAccSalir;
	private char webAccSubsanar;
	private String webParHisComentario;
	private String webParHisAccion;
	private int webTieRojo;
	private int webTieAmarillo;
	private char webFlgArcAdjuntos;
	private char webFlgArcAdicionales;
	private String webNomConfiguracion;
	private Character tipoVista;
	private Set<TareaAtrCompletar> tareaAtrCompletars = new HashSet<TareaAtrCompletar>(
			0);
	private Set<TareaAtrCancelar> tareaAtrCancelars = new HashSet<TareaAtrCancelar>(
			0);
	private Set<Rol> rols = new HashSet<Rol>(0);
	private Set<TareaAtrRechazar> tareaAtrRechazars = new HashSet<TareaAtrRechazar>(
			0);
	private Set<TareaAtrObservar> tareaAtrObservars = new HashSet<TareaAtrObservar>(
			0);
	private Set<Rol> rols_1 = new HashSet<Rol>(0);

	public Tarea() {
	}

	public Tarea(int codTarea, Consulta consultaByCodConTrabajar,
			Consulta consultaByCodConCompletar, String nombre,
			String versionTarea, String sqlAleas, String sqlDatasource,
			String bpmNombre, String javPaquete, String javClase,
			char webAccCompletar, char webAccGrabar, char webAccCancelar,
			char webAccRechazar, char webAccObservar, char webAccSalir,
			char webAccSubsanar, String webParHisComentario,
			String webParHisAccion, int webTieRojo, int webTieAmarillo,
			char webFlgArcAdjuntos, char webFlgArcAdicionales) {
		this.codTarea = codTarea;
		this.consultaByCodConTrabajar = consultaByCodConTrabajar;
		this.consultaByCodConCompletar = consultaByCodConCompletar;
		this.nombre = nombre;
		this.versionTarea = versionTarea;
		this.sqlAleas = sqlAleas;
		this.sqlDatasource = sqlDatasource;
		this.bpmNombre = bpmNombre;
		this.javPaquete = javPaquete;
		this.javClase = javClase;
		this.webAccCompletar = webAccCompletar;
		this.webAccGrabar = webAccGrabar;
		this.webAccCancelar = webAccCancelar;
		this.webAccRechazar = webAccRechazar;
		this.webAccObservar = webAccObservar;
		this.webAccSalir = webAccSalir;
		this.webAccSubsanar = webAccSubsanar;
		this.webParHisComentario = webParHisComentario;
		this.webParHisAccion = webParHisAccion;
		this.webTieRojo = webTieRojo;
		this.webTieAmarillo = webTieAmarillo;
		this.webFlgArcAdjuntos = webFlgArcAdjuntos;
		this.webFlgArcAdicionales = webFlgArcAdicionales;
	}

	public Tarea(int codTarea, Consulta consultaByCodConTrabajar,
			Consulta consultaByCodConCompletar, Proceso proceso, String nombre,
			String versionTarea, String sqlAleas, String sqlDatasource,
			String bpmNombre, String javPaquete, String javClase,
			char webAccCompletar, char webAccGrabar, char webAccCancelar,
			char webAccRechazar, char webAccObservar, char webAccSalir,
			char webAccSubsanar, String webParHisComentario,
			String webParHisAccion, int webTieRojo, int webTieAmarillo,
			char webFlgArcAdjuntos, char webFlgArcAdicionales,
			String webNomConfiguracion, Character tipoVista,
			Set<TareaAtrCompletar> tareaAtrCompletars,
			Set<TareaAtrCancelar> tareaAtrCancelars, Set<Rol> rols,
			Set<TareaAtrRechazar> tareaAtrRechazars,
			Set<TareaAtrObservar> tareaAtrObservars, Set<Rol> rols_1) {
		this.codTarea = codTarea;
		this.consultaByCodConTrabajar = consultaByCodConTrabajar;
		this.consultaByCodConCompletar = consultaByCodConCompletar;
		this.proceso = proceso;
		this.nombre = nombre;
		this.versionTarea = versionTarea;
		this.sqlAleas = sqlAleas;
		this.sqlDatasource = sqlDatasource;
		this.bpmNombre = bpmNombre;
		this.javPaquete = javPaquete;
		this.javClase = javClase;
		this.webAccCompletar = webAccCompletar;
		this.webAccGrabar = webAccGrabar;
		this.webAccCancelar = webAccCancelar;
		this.webAccRechazar = webAccRechazar;
		this.webAccObservar = webAccObservar;
		this.webAccSalir = webAccSalir;
		this.webAccSubsanar = webAccSubsanar;
		this.webParHisComentario = webParHisComentario;
		this.webParHisAccion = webParHisAccion;
		this.webTieRojo = webTieRojo;
		this.webTieAmarillo = webTieAmarillo;
		this.webFlgArcAdjuntos = webFlgArcAdjuntos;
		this.webFlgArcAdicionales = webFlgArcAdicionales;
		this.webNomConfiguracion = webNomConfiguracion;
		this.tipoVista = tipoVista;
		this.tareaAtrCompletars = tareaAtrCompletars;
		this.tareaAtrCancelars = tareaAtrCancelars;
		this.rols = rols;
		this.tareaAtrRechazars = tareaAtrRechazars;
		this.tareaAtrObservars = tareaAtrObservars;
		this.rols_1 = rols_1;
	}

	@Id
	@Column(name = "cod_tarea", unique = true, nullable = false)
	public int getCodTarea() {
		return this.codTarea;
	}

	public void setCodTarea(int codTarea) {
		this.codTarea = codTarea;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cod_con_trabajar", nullable = false)
	public Consulta getConsultaByCodConTrabajar() {
		return this.consultaByCodConTrabajar;
	}

	public void setConsultaByCodConTrabajar(Consulta consultaByCodConTrabajar) {
		this.consultaByCodConTrabajar = consultaByCodConTrabajar;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cod_con_completar", nullable = false)
	public Consulta getConsultaByCodConCompletar() {
		return this.consultaByCodConCompletar;
	}

	public void setConsultaByCodConCompletar(Consulta consultaByCodConCompletar) {
		this.consultaByCodConCompletar = consultaByCodConCompletar;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cod_proceso")
	public Proceso getProceso() {
		return this.proceso;
	}

	public void setProceso(Proceso proceso) {
		this.proceso = proceso;
	}

	@Column(name = "nombre", nullable = false, length = 120)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "version_tarea", nullable = false, length = 10)
	public String getVersionTarea() {
		return this.versionTarea;
	}

	public void setVersionTarea(String versionTarea) {
		this.versionTarea = versionTarea;
	}

	@Column(name = "sql_aleas", nullable = false, length = 20)
	public String getSqlAleas() {
		return this.sqlAleas;
	}

	public void setSqlAleas(String sqlAleas) {
		this.sqlAleas = sqlAleas;
	}

	@Column(name = "sql_datasource", nullable = false, length = 120)
	public String getSqlDatasource() {
		return this.sqlDatasource;
	}

	public void setSqlDatasource(String sqlDatasource) {
		this.sqlDatasource = sqlDatasource;
	}

	@Column(name = "bpm_nombre", nullable = false)
	public String getBpmNombre() {
		return this.bpmNombre;
	}

	public void setBpmNombre(String bpmNombre) {
		this.bpmNombre = bpmNombre;
	}

	@Column(name = "jav_paquete", nullable = false)
	public String getJavPaquete() {
		return this.javPaquete;
	}

	public void setJavPaquete(String javPaquete) {
		this.javPaquete = javPaquete;
	}

	@Column(name = "jav_clase", nullable = false)
	public String getJavClase() {
		return this.javClase;
	}

	public void setJavClase(String javClase) {
		this.javClase = javClase;
	}

	@Column(name = "web_acc_completar", nullable = false, length = 1)
	public char getWebAccCompletar() {
		return this.webAccCompletar;
	}

	public void setWebAccCompletar(char webAccCompletar) {
		this.webAccCompletar = webAccCompletar;
	}

	@Column(name = "web_acc_grabar", nullable = false, length = 1)
	public char getWebAccGrabar() {
		return this.webAccGrabar;
	}

	public void setWebAccGrabar(char webAccGrabar) {
		this.webAccGrabar = webAccGrabar;
	}

	@Column(name = "web_acc_cancelar", nullable = false, length = 1)
	public char getWebAccCancelar() {
		return this.webAccCancelar;
	}

	public void setWebAccCancelar(char webAccCancelar) {
		this.webAccCancelar = webAccCancelar;
	}

	@Column(name = "web_acc_rechazar", nullable = false, length = 1)
	public char getWebAccRechazar() {
		return this.webAccRechazar;
	}

	public void setWebAccRechazar(char webAccRechazar) {
		this.webAccRechazar = webAccRechazar;
	}

	@Column(name = "web_acc_observar", nullable = false, length = 1)
	public char getWebAccObservar() {
		return this.webAccObservar;
	}

	public void setWebAccObservar(char webAccObservar) {
		this.webAccObservar = webAccObservar;
	}

	@Column(name = "web_acc_salir", nullable = false, length = 1)
	public char getWebAccSalir() {
		return this.webAccSalir;
	}

	public void setWebAccSalir(char webAccSalir) {
		this.webAccSalir = webAccSalir;
	}

	@Column(name = "web_acc_subsanar", nullable = false, length = 1)
	public char getWebAccSubsanar() {
		return this.webAccSubsanar;
	}

	public void setWebAccSubsanar(char webAccSubsanar) {
		this.webAccSubsanar = webAccSubsanar;
	}

	@Column(name = "web_par_his_comentario", nullable = false, length = 120)
	public String getWebParHisComentario() {
		return this.webParHisComentario;
	}

	public void setWebParHisComentario(String webParHisComentario) {
		this.webParHisComentario = webParHisComentario;
	}

	@Column(name = "web_par_his_accion", nullable = false, length = 120)
	public String getWebParHisAccion() {
		return this.webParHisAccion;
	}

	public void setWebParHisAccion(String webParHisAccion) {
		this.webParHisAccion = webParHisAccion;
	}

	@Column(name = "web_tie_rojo", nullable = false)
	public int getWebTieRojo() {
		return this.webTieRojo;
	}

	public void setWebTieRojo(int webTieRojo) {
		this.webTieRojo = webTieRojo;
	}

	@Column(name = "web_tie_amarillo", nullable = false)
	public int getWebTieAmarillo() {
		return this.webTieAmarillo;
	}

	public void setWebTieAmarillo(int webTieAmarillo) {
		this.webTieAmarillo = webTieAmarillo;
	}

	@Column(name = "web_flg_arc_adjuntos", nullable = false, length = 1)
	public char getWebFlgArcAdjuntos() {
		return this.webFlgArcAdjuntos;
	}

	public void setWebFlgArcAdjuntos(char webFlgArcAdjuntos) {
		this.webFlgArcAdjuntos = webFlgArcAdjuntos;
	}

	@Column(name = "web_flg_arc_adicionales", nullable = false, length = 1)
	public char getWebFlgArcAdicionales() {
		return this.webFlgArcAdicionales;
	}

	public void setWebFlgArcAdicionales(char webFlgArcAdicionales) {
		this.webFlgArcAdicionales = webFlgArcAdicionales;
	}

	@Column(name = "web_nom_configuracion", length = 120)
	public String getWebNomConfiguracion() {
		return this.webNomConfiguracion;
	}

	public void setWebNomConfiguracion(String webNomConfiguracion) {
		this.webNomConfiguracion = webNomConfiguracion;
	}

	@Column(name = "tipo_vista", length = 1)
	public Character getTipoVista() {
		return this.tipoVista;
	}

	public void setTipoVista(Character tipoVista) {
		this.tipoVista = tipoVista;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tarea")
	public Set<TareaAtrCompletar> getTareaAtrCompletars() {
		return this.tareaAtrCompletars;
	}

	public void setTareaAtrCompletars(Set<TareaAtrCompletar> tareaAtrCompletars) {
		this.tareaAtrCompletars = tareaAtrCompletars;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tarea")
	public Set<TareaAtrCancelar> getTareaAtrCancelars() {
		return this.tareaAtrCancelars;
	}

	public void setTareaAtrCancelars(Set<TareaAtrCancelar> tareaAtrCancelars) {
		this.tareaAtrCancelars = tareaAtrCancelars;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "tarea_rol_potencial", schema = "soul", joinColumns = { @JoinColumn(name = "cod_tarea", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "cod_rol", nullable = false, updatable = false) })
	public Set<Rol> getRols() {
		return this.rols;
	}

	public void setRols(Set<Rol> rols) {
		this.rols = rols;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tarea")
	public Set<TareaAtrRechazar> getTareaAtrRechazars() {
		return this.tareaAtrRechazars;
	}

	public void setTareaAtrRechazars(Set<TareaAtrRechazar> tareaAtrRechazars) {
		this.tareaAtrRechazars = tareaAtrRechazars;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tarea")
	public Set<TareaAtrObservar> getTareaAtrObservars() {
		return this.tareaAtrObservars;
	}

	public void setTareaAtrObservars(Set<TareaAtrObservar> tareaAtrObservars) {
		this.tareaAtrObservars = tareaAtrObservars;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "tarea_rol_administrador", schema = "soul", joinColumns = { @JoinColumn(name = "cod_tarea", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "cod_rol", nullable = false, updatable = false) })
	public Set<Rol> getRols_1() {
		return this.rols_1;
	}

	public void setRols_1(Set<Rol> rols_1) {
		this.rols_1 = rols_1;
	}

}
