package pe.com.captiva.dao.entity;
// Generated 01/12/2015 04:35:12 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * TareaResumenSubSeccion generated by hbm2java
 */
@Entity
@Table(name = "tarea_resumen_sub_seccion", schema = "soul")
public class TareaResumenSubSeccion implements java.io.Serializable {

	private TareaResumenSubSeccionId id;
	private String nombre;

	public TareaResumenSubSeccion() {
	}

	public TareaResumenSubSeccion(TareaResumenSubSeccionId id, String nombre) {
		this.id = id;
		this.nombre = nombre;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "codTarea", column = @Column(name = "cod_tarea", nullable = false) ),
			@AttributeOverride(name = "codSubSeccion", column = @Column(name = "cod_sub_seccion", nullable = false) ) })
	public TareaResumenSubSeccionId getId() {
		return this.id;
	}

	public void setId(TareaResumenSubSeccionId id) {
		this.id = id;
	}

	@Column(name = "nombre", nullable = false, length = 100)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

}
