package pe.com.captiva.dao.entity;

// Generated 22/10/2015 09:43:27 PM by Hibernate Tools 4.3.1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TareaAtrCancelar generated by hbm2java
 */
@Entity
@Table(name = "tarea_atr_cancelar", schema = "soul")
public class TareaAtrCancelar implements java.io.Serializable {

	private TareaAtrCancelarId id;
	private Atributo atributo;
	private Tarea tarea;
	private String javValOmision;
	private Character webFlgValidacion;

	public TareaAtrCancelar() {
	}

	public TareaAtrCancelar(TareaAtrCancelarId id, Atributo atributo,
			Tarea tarea) {
		this.id = id;
		this.atributo = atributo;
		this.tarea = tarea;
	}

	public TareaAtrCancelar(TareaAtrCancelarId id, Atributo atributo,
			Tarea tarea, String javValOmision, Character webFlgValidacion) {
		this.id = id;
		this.atributo = atributo;
		this.tarea = tarea;
		this.javValOmision = javValOmision;
		this.webFlgValidacion = webFlgValidacion;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "codProceso", column = @Column(name = "cod_proceso", nullable = false)),
			@AttributeOverride(name = "codTarea", column = @Column(name = "cod_tarea", nullable = false)),
			@AttributeOverride(name = "codAtributo", column = @Column(name = "cod_atributo", nullable = false)) })
	public TareaAtrCancelarId getId() {
		return this.id;
	}

	public void setId(TareaAtrCancelarId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cod_atributo", nullable = false, insertable = false, updatable = false)
	public Atributo getAtributo() {
		return this.atributo;
	}

	public void setAtributo(Atributo atributo) {
		this.atributo = atributo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "cod_tarea", referencedColumnName = "cod_proceso", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "cod_proceso", referencedColumnName = "cod_tarea", nullable = false, insertable = false, updatable = false) })
	public Tarea getTarea() {
		return this.tarea;
	}

	public void setTarea(Tarea tarea) {
		this.tarea = tarea;
	}

	@Column(name = "jav_val_omision", length = 250)
	public String getJavValOmision() {
		return this.javValOmision;
	}

	public void setJavValOmision(String javValOmision) {
		this.javValOmision = javValOmision;
	}

	@Column(name = "web_flg_validacion", length = 1)
	public Character getWebFlgValidacion() {
		return this.webFlgValidacion;
	}

	public void setWebFlgValidacion(Character webFlgValidacion) {
		this.webFlgValidacion = webFlgValidacion;
	}

}
