package pe.com.captiva.dao.entity;
// Generated 01/12/2015 04:35:12 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * TareaAccionSubSeccion generated by hbm2java
 */
@Entity
@Table(name = "tarea_accion_sub_seccion", schema = "soul")
public class TareaAccionSubSeccion implements java.io.Serializable {

	private TareaAccionSubSeccionId id;

	public TareaAccionSubSeccion() {
	}

	public TareaAccionSubSeccion(TareaAccionSubSeccionId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "codTarea", column = @Column(name = "cod_tarea") ),
			@AttributeOverride(name = "codSeccion", column = @Column(name = "cod_seccion", nullable = false, length = 20) ),
			@AttributeOverride(name = "codSubSeccion", column = @Column(name = "cod_sub_seccion", nullable = false) ),
			@AttributeOverride(name = "nombre", column = @Column(name = "nombre", nullable = false, length = 100) ) })
	public TareaAccionSubSeccionId getId() {
		return this.id;
	}

	public void setId(TareaAccionSubSeccionId id) {
		this.id = id;
	}

}
