package pe.com.captiva.dao.entity;
// Generated 01/12/2015 04:35:12 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TareaResumenSubSeccionId generated by hbm2java
 */
@Embeddable
public class TareaResumenSubSeccionId implements java.io.Serializable {

	private int codTarea;
	private int codSubSeccion;

	public TareaResumenSubSeccionId() {
	}

	public TareaResumenSubSeccionId(int codTarea, int codSubSeccion) {
		this.codTarea = codTarea;
		this.codSubSeccion = codSubSeccion;
	}

	@Column(name = "cod_tarea", nullable = false)
	public int getCodTarea() {
		return this.codTarea;
	}

	public void setCodTarea(int codTarea) {
		this.codTarea = codTarea;
	}

	@Column(name = "cod_sub_seccion", nullable = false)
	public int getCodSubSeccion() {
		return this.codSubSeccion;
	}

	public void setCodSubSeccion(int codSubSeccion) {
		this.codSubSeccion = codSubSeccion;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TareaResumenSubSeccionId))
			return false;
		TareaResumenSubSeccionId castOther = (TareaResumenSubSeccionId) other;

		return (this.getCodTarea() == castOther.getCodTarea())
				&& (this.getCodSubSeccion() == castOther.getCodSubSeccion());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCodTarea();
		result = 37 * result + this.getCodSubSeccion();
		return result;
	}

}
