package pe.com.captiva.dao.entity;

// Generated 25/10/2015 06:07:58 AM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TareaId generated by hbm2java
 */
@Embeddable
public class TareaId implements java.io.Serializable {

	private int codProceso;
	private int codTarea;

	public TareaId() {
	}

	public TareaId(int codProceso, int codTarea) {
		this.codProceso = codProceso;
		this.codTarea = codTarea;
	}

	@Column(name = "cod_proceso", nullable = false)
	public int getCodProceso() {
		return this.codProceso;
	}

	public void setCodProceso(int codProceso) {
		this.codProceso = codProceso;
	}

	@Column(name = "cod_tarea", nullable = false)
	public int getCodTarea() {
		return this.codTarea;
	}

	public void setCodTarea(int codTarea) {
		this.codTarea = codTarea;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TareaId))
			return false;
		TareaId castOther = (TareaId) other;

		return (this.getCodProceso() == castOther.getCodProceso())
				&& (this.getCodTarea() == castOther.getCodTarea());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCodProceso();
		result = 37 * result + this.getCodTarea();
		return result;
	}

}
