package pe.com.captiva.dao.entity;
// Generated 26/11/2015 04:49:30 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TareaResumenPlantillaAtributoId generated by hbm2java
 */
@Embeddable
public class TareaResumenPlantillaAtributoId implements java.io.Serializable {

	private String codPlantilla;
	private int codSubSeccion;
	private int codTareaResumenPlantillaAtributo;

	public TareaResumenPlantillaAtributoId() {
	}

	public TareaResumenPlantillaAtributoId(String codPlantilla, int codSubSeccion,
			int codTareaResumenPlantillaAtributo) {
		this.codPlantilla = codPlantilla;
		this.codSubSeccion = codSubSeccion;
		this.codTareaResumenPlantillaAtributo = codTareaResumenPlantillaAtributo;
	}

	@Column(name = "cod_plantilla", nullable = false, length = 20)
	public String getCodPlantilla() {
		return this.codPlantilla;
	}

	public void setCodPlantilla(String codPlantilla) {
		this.codPlantilla = codPlantilla;
	}

	@Column(name = "cod_sub_seccion", nullable = false)
	public int getCodSubSeccion() {
		return this.codSubSeccion;
	}

	public void setCodSubSeccion(int codSubSeccion) {
		this.codSubSeccion = codSubSeccion;
	}

	@Column(name = "cod_tarea_resumen_plantilla_atributo", nullable = false)
	public int getCodTareaResumenPlantillaAtributo() {
		return this.codTareaResumenPlantillaAtributo;
	}

	public void setCodTareaResumenPlantillaAtributo(int codTareaResumenPlantillaAtributo) {
		this.codTareaResumenPlantillaAtributo = codTareaResumenPlantillaAtributo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TareaResumenPlantillaAtributoId))
			return false;
		TareaResumenPlantillaAtributoId castOther = (TareaResumenPlantillaAtributoId) other;

		return ((this.getCodPlantilla() == castOther.getCodPlantilla()) || (this.getCodPlantilla() != null
				&& castOther.getCodPlantilla() != null && this.getCodPlantilla().equals(castOther.getCodPlantilla())))
				&& (this.getCodSubSeccion() == castOther.getCodSubSeccion())
				&& (this.getCodTareaResumenPlantillaAtributo() == castOther.getCodTareaResumenPlantillaAtributo());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getCodPlantilla() == null ? 0 : this.getCodPlantilla().hashCode());
		result = 37 * result + this.getCodSubSeccion();
		result = 37 * result + this.getCodTareaResumenPlantillaAtributo();
		return result;
	}

}
