package pe.com.captiva.dao.entity;
// Generated 26/11/2015 04:49:30 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * TareaResumenPlantilla generated by hbm2java
 */
@Entity
@Table(name = "tarea_resumen_plantilla", schema = "soul")
public class TareaResumenPlantilla implements java.io.Serializable {

	private TareaResumenPlantillaId id;

	public TareaResumenPlantilla() {
	}

	public TareaResumenPlantilla(TareaResumenPlantillaId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "codPlantilla", column = @Column(name = "cod_plantilla", length = 20) ),
			@AttributeOverride(name = "nombre", column = @Column(name = "nombre", length = 100) ) })
	public TareaResumenPlantillaId getId() {
		return this.id;
	}

	public void setId(TareaResumenPlantillaId id) {
		this.id = id;
	}

}
