package pe.com.captiva.dao.entity;
// Generated 26/11/2015 04:49:30 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TareaResumenId generated by hbm2java
 */
@Embeddable
public class TareaResumenId implements java.io.Serializable {

	private int codTarea;
	private int codSubSeccion;
	private int codTareaResumen;

	public TareaResumenId() {
	}

	public TareaResumenId(int codTarea, int codSubSeccion, int codTareaResumen) {
		this.codTarea = codTarea;
		this.codSubSeccion = codSubSeccion;
		this.codTareaResumen = codTareaResumen;
	}

	@Column(name = "cod_tarea", nullable = false)
	public int getCodTarea() {
		return this.codTarea;
	}

	public void setCodTarea(int codTarea) {
		this.codTarea = codTarea;
	}

	@Column(name = "cod_sub_seccion", nullable = false)
	public int getCodSubSeccion() {
		return this.codSubSeccion;
	}

	public void setCodSubSeccion(int codSubSeccion) {
		this.codSubSeccion = codSubSeccion;
	}

	@Column(name = "cod_tarea_resumen", nullable = false)
	public int getCodTareaResumen() {
		return this.codTareaResumen;
	}

	public void setCodTareaResumen(int codTareaResumen) {
		this.codTareaResumen = codTareaResumen;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TareaResumenId))
			return false;
		TareaResumenId castOther = (TareaResumenId) other;

		return (this.getCodTarea() == castOther.getCodTarea())
				&& (this.getCodSubSeccion() == castOther.getCodSubSeccion())
				&& (this.getCodTareaResumen() == castOther.getCodTareaResumen());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCodTarea();
		result = 37 * result + this.getCodSubSeccion();
		result = 37 * result + this.getCodTareaResumen();
		return result;
	}

}
