package pe.com.captiva.dao.entity;
// Generated 01/12/2015 04:35:12 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TareaAccionSubSeccionId generated by hbm2java
 */
@Embeddable
public class TareaAccionSubSeccionId implements java.io.Serializable {

	private Integer codTarea;
	private String codSeccion;
	private int codSubSeccion;
	private String nombre;

	public TareaAccionSubSeccionId() {
	}

	public TareaAccionSubSeccionId(String codSeccion, int codSubSeccion, String nombre) {
		this.codSeccion = codSeccion;
		this.codSubSeccion = codSubSeccion;
		this.nombre = nombre;
	}

	public TareaAccionSubSeccionId(Integer codTarea, String codSeccion, int codSubSeccion, String nombre) {
		this.codTarea = codTarea;
		this.codSeccion = codSeccion;
		this.codSubSeccion = codSubSeccion;
		this.nombre = nombre;
	}

	@Column(name = "cod_tarea")
	public Integer getCodTarea() {
		return this.codTarea;
	}

	public void setCodTarea(Integer codTarea) {
		this.codTarea = codTarea;
	}

	@Column(name = "cod_seccion", nullable = false, length = 20)
	public String getCodSeccion() {
		return this.codSeccion;
	}

	public void setCodSeccion(String codSeccion) {
		this.codSeccion = codSeccion;
	}

	@Column(name = "cod_sub_seccion", nullable = false)
	public int getCodSubSeccion() {
		return this.codSubSeccion;
	}

	public void setCodSubSeccion(int codSubSeccion) {
		this.codSubSeccion = codSubSeccion;
	}

	@Column(name = "nombre", nullable = false, length = 100)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TareaAccionSubSeccionId))
			return false;
		TareaAccionSubSeccionId castOther = (TareaAccionSubSeccionId) other;

		return ((this.getCodTarea() == castOther.getCodTarea()) || (this.getCodTarea() != null
				&& castOther.getCodTarea() != null && this.getCodTarea().equals(castOther.getCodTarea())))
				&& ((this.getCodSeccion() == castOther.getCodSeccion()) || (this.getCodSeccion() != null
						&& castOther.getCodSeccion() != null && this.getCodSeccion().equals(castOther.getCodSeccion())))
				&& (this.getCodSubSeccion() == castOther.getCodSubSeccion())
				&& ((this.getNombre() == castOther.getNombre()) || (this.getNombre() != null
						&& castOther.getNombre() != null && this.getNombre().equals(castOther.getNombre())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getCodTarea() == null ? 0 : this.getCodTarea().hashCode());
		result = 37 * result + (getCodSeccion() == null ? 0 : this.getCodSeccion().hashCode());
		result = 37 * result + this.getCodSubSeccion();
		result = 37 * result + (getNombre() == null ? 0 : this.getNombre().hashCode());
		return result;
	}

}
