package pe.com.captiva.dao.entity;
// Generated 26/11/2015 04:49:30 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * TareaResumenPlantillaSubSeccion generated by hbm2java
 */
@Entity
@Table(name = "tarea_resumen_plantilla_sub_seccion", schema = "soul")
public class TareaResumenPlantillaSubSeccion implements java.io.Serializable {

	private TareaResumenPlantillaSubSeccionId id;
	private String nombre;

	public TareaResumenPlantillaSubSeccion() {
	}

	public TareaResumenPlantillaSubSeccion(TareaResumenPlantillaSubSeccionId id, String nombre) {
		this.id = id;
		this.nombre = nombre;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "codPlantilla", column = @Column(name = "cod_plantilla", nullable = false, length = 20) ),
			@AttributeOverride(name = "codSubSeccion", column = @Column(name = "cod_sub_seccion", nullable = false) ) })
	public TareaResumenPlantillaSubSeccionId getId() {
		return this.id;
	}

	public void setId(TareaResumenPlantillaSubSeccionId id) {
		this.id = id;
	}

	@Column(name = "nombre", nullable = false, length = 100)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

}
