package pe.com.captiva.dao.entity;
// Generated 01/12/2015 04:35:12 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * TareaResumen generated by hbm2java
 */
@Entity
@Table(name = "tarea_resumen", schema = "soul")
public class TareaResumen implements java.io.Serializable {

	private TareaResumenId id;
	private int codAtributo;
	private String webEtiqueta;

	public TareaResumen() {
	}

	public TareaResumen(TareaResumenId id, int codAtributo, String webEtiqueta) {
		this.id = id;
		this.codAtributo = codAtributo;
		this.webEtiqueta = webEtiqueta;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "codTarea", column = @Column(name = "cod_tarea", nullable = false) ),
			@AttributeOverride(name = "codSubSeccion", column = @Column(name = "cod_sub_seccion", nullable = false) ),
			@AttributeOverride(name = "codTareaResumen", column = @Column(name = "cod_tarea_resumen", nullable = false) ) })
	public TareaResumenId getId() {
		return this.id;
	}

	public void setId(TareaResumenId id) {
		this.id = id;
	}

	@Column(name = "cod_atributo", nullable = false)
	public int getCodAtributo() {
		return this.codAtributo;
	}

	public void setCodAtributo(int codAtributo) {
		this.codAtributo = codAtributo;
	}

	@Column(name = "web_etiqueta", nullable = false)
	public String getWebEtiqueta() {
		return this.webEtiqueta;
	}

	public void setWebEtiqueta(String webEtiqueta) {
		this.webEtiqueta = webEtiqueta;
	}

}
