package pe.com.captiva.dao.entity;

// Generated 11/11/2015 09:33:32 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TareaRolPotencialId generated by hbm2java
 */
@Embeddable
public class TareaRolPotencialId implements java.io.Serializable {

	private int codTarea;
	private String codRol;

	public TareaRolPotencialId() {
	}

	public TareaRolPotencialId(int codTarea, String codRol) {
		this.codTarea = codTarea;
		this.codRol = codRol;
	}

	@Column(name = "cod_tarea", nullable = false)
	public int getCodTarea() {
		return this.codTarea;
	}

	public void setCodTarea(int codTarea) {
		this.codTarea = codTarea;
	}

	@Column(name = "cod_rol", nullable = false, length = 120)
	public String getCodRol() {
		return this.codRol;
	}

	public void setCodRol(String codRol) {
		this.codRol = codRol;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TareaRolPotencialId))
			return false;
		TareaRolPotencialId castOther = (TareaRolPotencialId) other;

		return (this.getCodTarea() == castOther.getCodTarea())
				&& ((this.getCodRol() == castOther.getCodRol()) || (this
						.getCodRol() != null && castOther.getCodRol() != null && this
						.getCodRol().equals(castOther.getCodRol())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCodTarea();
		result = 37 * result
				+ (getCodRol() == null ? 0 : this.getCodRol().hashCode());
		return result;
	}

}
