package pe.com.captiva.dao.entity;

// Generated 21/10/2015 10:31:13 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name = "usuario", schema = "soul")
public class Usuario implements java.io.Serializable {

	private String codUsuario;
	private String clave;
	private String nombre;
	private String perfil;
	private String descripcion;

	public Usuario() {
	}

	public Usuario(String codUsuario, String clave, String nombre, String perfil) {
		this.codUsuario = codUsuario;
		this.clave = clave;
		this.nombre = nombre;
		this.perfil = perfil;
	}

	public Usuario(String codUsuario, String clave, String nombre,
			String perfil, String descripcion) {
		this.codUsuario = codUsuario;
		this.clave = clave;
		this.nombre = nombre;
		this.perfil = perfil;
		this.descripcion = descripcion;
	}

	@Id
	@Column(name = "cod_usuario", unique = true, nullable = false, length = 50)
	public String getCodUsuario() {
		return this.codUsuario;
	}

	public void setCodUsuario(String codUsuario) {
		this.codUsuario = codUsuario;
	}

	@Column(name = "clave", nullable = false, length = 100)
	public String getClave() {
		return this.clave;
	}

	public void setClave(String clave) {
		this.clave = clave;
	}

	@Column(name = "nombre", nullable = false, length = 100)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "perfil", nullable = false, length = 50)
	public String getPerfil() {
		return this.perfil;
	}

	public void setPerfil(String perfil) {
		this.perfil = perfil;
	}

	@Column(name = "descripcion", length = 250)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

}
